Repository logseq/logseq, pull requests merged in 2022-05, with the labels that each got.

#5214 Enhance: Adds emacs keybindings to other up/down movements
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/enhancement

#5220 fix(ux): initial renderer not working for Katex extension hooks
  src/main/frontend/extensions/latex.cljs
Labels: :type/bug-fix

#5124 fix(draw): invalid dom element
  src/main/frontend/extensions/excalidraw.cljs
Labels: :type/bug-fix, fix

#5237 enhance: update login url
  src/main/frontend/config.cljs
Labels: :type/enhancement

#5236 Fix/UI page of shortcuts crashed when parsing unsupported binding key
  libs/src/LSPlugin.ts
  src/main/frontend/modules/shortcut/core.cljs
  src/main/frontend/modules/shortcut/data_helper.cljs
Labels: :type/bug-fix

#5244 Disable two outliner tests which fail intermittently the most
  src/test/frontend/modules/outliner/core_test.cljs
Labels: :type/dev

#5248 fix(sync): update rsapi to 0.0.9
  resources/package.json
  src/electron/electron/file_sync_rsapi.cljs
  yarn.lock
Labels: fix

#5250 fix: missing title properties when page name contains `/` or reserved chars
  src/main/frontend/components/block.cljs
  src/main/frontend/format/block.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/extract.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/modules/file/core.cljs
  src/main/frontend/util.cljc
  src/test/frontend/handler/repo_test.cljs
Labels: :type/bug-fix

#5271 fix(login): auth-callback&auth-refresh-token return json type resp
  src/main/frontend/handler/user.cljs
Labels: :type/bug-fix

#5241 enhance(sync): ws ping, update sync init process
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#5279 Rm fs-watcher debug print
  src/main/frontend/handler/events.cljs
Labels: fix

#5276 enhance(sync): add ::queued-local->remote-files file-sync state
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#5281 enhance(sync): update prod config, add :pre for update-graphs-txid
  src/main/frontend/config.cljs
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#5290 fix hidden files removing failure on mobile
  src/main/frontend/handler/repo.cljs
Labels: :type/bug-fix

#5163 fix: modals positions once again
  src/main/frontend/components/editor.cljs
Labels: :type/bug-fix

#5289 enhance(sync): auto start sync when switching graphs
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/state.cljs
Labels: :type/enhancement

#5307 fix(ui): wrong position of page preview tip
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#5299 Enhance: Migrate block and extract to graph parser
  .clj-kondo/config.edn
  src/main/frontend/commands.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/content.cljs
  src/main/frontend/components/file.cljs
  src/main/frontend/components/journal.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/components/reference.cljs
  src/main/frontend/components/search.cljs
  src/main/frontend/config.cljs
  src/main/frontend/date.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/db/query_dsl.cljs
  src/main/frontend/db/query_react.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/extensions/html_parser.cljs
  src/main/frontend/format.cljs
  src/main/frontend/format/block.cljs
  src/main/frontend/format/mldoc.cljs
  src/main/frontend/fs/watcher_handler.cljs
  src/main/frontend/handler/block.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/export.cljs
  src/main/frontend/handler/external.cljs
  src/main/frontend/handler/file.cljs
  src/main/frontend/handler/graph.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/handler/route.cljs
  src/main/frontend/handler/ui.cljs
  src/main/frontend/mobile/intent.cljs
  src/main/frontend/modules/outliner/tree.cljs
  src/main/frontend/search.cljs
  src/main/frontend/security.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  src/main/frontend/util/drawer.cljs
  src/main/frontend/util/marker.cljs
  src/main/frontend/util/priority.cljs
  src/main/frontend/util/property.cljs
  src/main/frontend/util/thingatpt.cljs
  src/main/logseq/graph_parser/block.cljc
  src/main/logseq/graph_parser/config.cljs
  src/main/logseq/graph_parser/date_time_util.cljs
  src/main/logseq/graph_parser/extract.cljc
  src/main/logseq/graph_parser/property.cljs
  src/main/logseq/graph_parser/util.cljs
  src/test/frontend/db/conn.clj
  src/test/frontend/handler/block_test.cljs
  src/test/frontend/modules/outliner/core_test.cljs
  src/test/frontend/react.cljc
  src/test/frontend/react_test.cljs
  src/test/frontend/test/docs_graph_helper.cljs
  src/test/frontend/util/property_test.cljs
  src/test/logseq/graph_parser/block_test.cljs
  src/test/logseq/graph_parser/extract_test.cljs
  src/test/logseq/graph_parser/nbb_test_runner.cljs
  src/test/logseq/graph_parser/property_test.cljs
Labels: :type/enhancement

#5332 chore(release): bump version 0.6.9
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#5349 fix(sync): check current-user-uuid against nil
  e2e-tests/code-editing.spec.ts
  src/main/frontend/fs/sync.cljs
Labels: fix

#4741 feat: custom theme switching
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  libs/src/helpers.ts
  resources/js/lsplugin.core.js
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/theme.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/logseq/api.cljs
Labels: feature

#5364 fix: load legacy theme
  src/main/frontend/ui.cljs
Labels: fix

#5367 fix(plugin): not apply custom theme when LSP disabled
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#5369 fix(publishing): use release build for publishing js
  package.json
Labels: fix

#5377 fix(ui): page blink caused by query lazy load skeleton
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#5404 fix Zoom Display issue on iOS
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Utils.m
  ios/App/App/Utils.swift
  src/main/frontend/components/header.css
  src/main/frontend/mobile/core.cljs
  src/main/frontend/mobile/index.css
  src/main/frontend/mobile/util.cljs
Labels: :type/bug-fix

#5415 fix(plugin): page crash when checking plugin updates with some network issues
  src/main/frontend/components/plugins.cljs
Labels: :type/bug-fix

#5416 chore(release): bump version 0.7.0
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#5486 fix(ui): left menu style
  src/main/frontend/components/header.cljs
Labels: fix

#5247 Feature/onboarding Quick tour
  e2e-tests/sidebar.spec.ts
  resources/css/common.css
  resources/css/shepherd.css
  resources/js/shepherd.min.js
  src/main/frontend/components/header.cljs
  src/main/frontend/components/header.css
  src/main/frontend/components/onboarding/index.css
  src/main/frontend/components/onboarding/quick_tour.cljs
  src/main/frontend/components/page.css
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
  src/main/frontend/page.cljs
  tailwind.all.css
  templates/config.edn
Labels: :type/feature

#5496 fix(ui): adjust bg color of left sidebar from mobile
  src/main/frontend/components/sidebar.css
Labels: :type/bug-fix
