Repository logseq/logseq, pull requests merged in 2022-10, with the labels that each got.

#6868 fix(build): windows7 compatibility
  src/electron/electron/file_sync_rsapi.cljs
Labels: :type/bug-fix

#6488 Enhance/api storages for graph assets
  libs/package.json
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  libs/src/modules/LSPlugin.Storage.ts
  resources/js/lsplugin.core.js
  src/electron/electron/handler.cljs
  src/electron/electron/plugin.cljs
  src/electron/electron/utils.cljs
  src/electron/electron/utils.js
  src/main/frontend/config.cljs
  src/main/logseq/api.cljs
Labels: :type/enhancement

#6897 fix(mobile): use .m4a for mobile audio record
  src/main/frontend/mobile/record.cljs
Labels: fix

#6894 Enhance: Activation settings
  src/main/frontend/components/command_palette.css
  src/main/frontend/components/settings.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/ui.cljs
Labels: :type/enhancement

#6821 Enhance: Color system
  resources/css/common.css
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/content.cljs
  src/main/frontend/components/encryption.cljs
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/file_sync.css
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page.css
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/reference.cljs
  src/main/frontend/components/svg.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/extensions/pdf/pdf.css
  src/main/frontend/extensions/zotero.cljs
  src/main/frontend/ui.cljs
  tailwind.all.css
  tailwind.config.js
Labels: :type/enhancement, css, ux, accessibility

#6890 Fix: stuck re-index when there're multiple whiteboards have the same UUID
  deps/graph-parser/src/logseq/graph_parser/extract.cljc
  deps/graph-parser/src/logseq/graph_parser/util.cljs
  deps/graph-parser/test/logseq/graph_parser_test.cljs
  src/main/frontend/handler/common/file.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/file.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/modules/file/core.cljs
  src/main/frontend/modules/outliner/file.cljs
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#6915 fix: refresh tokens when almost-expired-or-expired
  src/main/frontend/handler/user.cljs
Labels: :type/bug-fix

#6475 Enhance/pdf improvements
  .clj-kondo/config.edn
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  libs/.npmignore
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  package.json
  resources/js/pdfjs/pdf.js
  resources/js/pdfjs/pdf.worker.js
  resources/js/pdfjs/pdf_viewer.js
  resources/js/preload.js
  src/electron/electron/core.cljs
  src/electron/electron/file_sync_rsapi.cljs
  src/electron/electron/utils.cljs
  src/main/frontend/components/assets.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/onboarding/quick_tour.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/select.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/svg.cljs
  src/main/frontend/config.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/extensions/lightbox.cljs
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/pdf/finder.js
  src/main/frontend/extensions/pdf/highlights.cljs
  src/main/frontend/extensions/pdf/pdf.css
  src/main/frontend/extensions/pdf/toolbar.cljs
  src/main/frontend/extensions/pdf/utils.cljs
  src/main/frontend/extensions/pdf/utils.js
  src/main/frontend/fs/capacitor_fs.cljs
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/assets.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/mobile/intent.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/dicts.cljc
  src/main/frontend/spec/storage.cljc
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/util.cljc
  src/main/frontend/utils.js
  src/test/frontend/extensions/pdf/assets_test.cljs
  yarn.lock
Labels: :type/enhancement

#6934 fix(plugin): enter to break line not work for textarea settings item
  src/main/frontend/components/plugins_settings.cljs
Labels: :type/bug-fix

#6947 fix(mobile): missing tabler icon components resource
  public/index.html
Labels: :type/bug-fix

#6939 Feat: Add icons to context menu
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
Labels: :type/feature

#6938 Fix: Remove hidden task properties that weren't used
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  src/main/frontend/util/marker.cljs
Labels: :type/bug-fix

#6957 fix(ui): alignment of some svg icons
  src/main/frontend/components/file_sync.cljs
Labels: :type/bug-fix

#6956 fix: don't create journal's file when it was initialized by a template
  src/main/frontend/handler/editor.cljs
  src/main/frontend/modules/outliner/pipeline.cljs
Labels: :type/bug-fix

#6961 fix(sync): allow to sync-start when txid=nil(in graphs-txid.edn)
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#6962 fix(excalidraw): grid mode status not correctly shown
  src/main/frontend/extensions/excalidraw.cljs
Labels: fix

#6982 Fix #6965 caused by button unable to handle href
  src/main/frontend/components/header.cljs
Labels: :type/bug-fix

#6984 fix(pdf): built-in contents links not working
  src/main/frontend/extensions/pdf/highlights.cljs
Labels: :type/bug-fix

#6974 Fix: Up/down arrow navigation
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#6968 enhance(sync): check remoteapi exceptions
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#6911 Feat: Reproducible plugin configuration
  .clj-kondo/config.edn
  bb.edn
  deps.edn
  docs/dev-practices.md
  scripts/src/logseq/tasks/malli.clj
  src/electron/electron/plugin.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/config.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/extensions/latex.cljs
  src/main/frontend/extensions/pdf/highlights.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/common/plugin.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/handler/plugin_config.cljs
  src/main/frontend/idb.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/dicts.cljc
  src/main/frontend/schema/handler/plugin_config.cljc
  src/main/frontend/ui.cljs
  src/main/logseq/api.cljs
  src/test/frontend/fs/test_node.cljs
  src/test/frontend/fs_test.cljs
  src/test/frontend/handler/export_test.cljs
  src/test/frontend/handler/plugin_config_test.cljs
  src/test/frontend/handler/repo_conversion_test.cljs
  src/test/frontend/modules/outliner/core_test.cljs
  src/test/frontend/test/fixtures.cljs
  src/test/frontend/test/helper.clj
  src/test/frontend/test/helper.cljs
Labels: :type/feature

#7025 fix(ui): input style of page title when editing.
  resources/css/common.css
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page.css
  src/main/frontend/components/whiteboard.css
Labels: :type/bug-fix

#7029 Fix: Disallow tags as property names
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  deps/graph-parser/test/logseq/graph_parser_test.cljs
Labels: :type/bug-fix

#7044 Fix: block-uuid on page-reference
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#7052 Fix: Not showing all content when editing a long page (pdf)
  src/main/frontend/fs/watcher_handler.cljs
Labels: :type/bug-fix

#7053 fix(windows): remove encoding assets protocol path temporarily
  src/main/frontend/handler/assets.cljs
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#6892 feat: support locale sensitive string comparisons for table sorting
  src/main/frontend/components/query_table.cljs
  src/test/frontend/components/query_table_test.cljs
Labels: awaiting-response

#7070 fix(ui): main content container overflow when page title too long
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page.css
  src/main/frontend/components/whiteboard.css
Labels: :type/bug-fix

#7115 fix(page): title has height 0 when length of editing title is 0
  src/main/frontend/components/page.css
Labels: fix

#7110 Fix: File links creating garbage pages
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/test/logseq/graph_parser_test.cljs
Labels: :type/bug-fix

#7096 fix: several issues on clicking the whiteboard shape ref
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix, 🎨 :feat/whiteboard

#7130 fix(ui): headerbar position on iPhone14x
  src/main/frontend/components/header.css
  src/main/frontend/mobile/util.cljs
Labels: :type/bug-fix

#7131 fix(ios): encode file path for capacitor fs
  package.json
  src/main/frontend/fs/capacitor_fs.cljs
  src/main/frontend/mobile/record.cljs
  yarn.lock
Labels: :type/bug-fix
