Repository logseq/logseq, pull requests merged in 2022-02, with the labels that each got.

#4130 enhance(ui): setup default context menu with right click
  package.json
  src/electron/electron/core.cljs
Labels: :type/enhancement

#3941 Cut memory usage
  docs/mobile.md
  package.json
  shadow-cljs.edn
  src/main/frontend/components/block.cljs
  src/main/frontend/components/command_palette.cljs
  src/main/frontend/components/content.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/encryption.cljs
  src/main/frontend/components/export.cljs
  src/main/frontend/components/file.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/journal.cljs
  src/main/frontend/components/onboarding.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/search.cljs
  src/main/frontend/components/select.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/shortcut.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/widgets.cljs
  src/main/frontend/context/i18n.cljs
  src/main/frontend/db.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/db/outliner.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/db/utils.cljs
  src/main/frontend/extensions/pdf/highlights.cljs
  src/main/frontend/format/block.cljs
  src/main/frontend/format/mldoc.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/extract.cljs
  src/main/frontend/handler/file.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/handler/search.cljs
  src/main/frontend/handler/web/nfs.cljs
  src/main/frontend/modules/outliner/core.cljs
  src/main/frontend/modules/outliner/file.cljs
  src/main/frontend/modules/outliner/state.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/page.cljs
  src/main/frontend/search/db.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/util/pool.cljs
  src/main/frontend/util/property.cljs
  src/main/frontend/worker/parser.cljs
  src/main/logseq/api.cljs
  yarn.lock
Labels: :type/enhancement

#4162 Remove unused vars and get us back to green
  src/main/frontend/config.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/search/db.cljs
  src/main/frontend/text.cljs
Labels: :type/dev

#4104 Add graph removal and add commands
  .clj-kondo/config.edn
  .github/workflows/build.yml
  bb.edn
  docs/contributing-to-translations.md
  scripts/src/logseq/tasks/lang.clj
  scripts/src/logseq/tasks/rewrite_clj.clj
  src/main/frontend/components/block.cljs
  src/main/frontend/components/select.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/dict.cljs
Labels: :type/feature

#4168 chore(dev): add more pr labeler rules
  .github/pr-labeler.yml
Labels: :type/dev, chore

#4159 fix(properties): disable blank alias
  src/main/frontend/handler/extract.cljs
Labels: :type/bug-fix, fix

#4126 Add Linter for large vars
  .github/workflows/build.yml
  docs/dev-practices.md
  scripts/large_vars.clj
  scripts/src/logseq/tasks/lang.clj
  scripts/src/logseq/tasks/rewrite_clj.clj
  src/main/frontend/components/block.cljs
  src/main/frontend/components/content.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/onboarding.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/query_table.cljs
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/search.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/db/query_dsl.cljs
  src/main/frontend/db_schema.cljs
  src/main/frontend/dicts.cljs
  src/main/frontend/extensions/html_parser.cljs
  src/main/frontend/extensions/pdf/highlights.cljs
  src/main/frontend/format/block.cljs
  src/main/frontend/fs/nfs.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/dict.cljs
  src/main/frontend/state.cljs
  src/test/frontend/db/query_dsl_test.cljs
Labels: :type/dev

#4179 fix: text goes beneath toolbar in large block on iOS
  src/main/frontend/components/editor.cljs
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4186 test(e2e): add test case for #4178
  e2e-tests/page-refs.spec.ts
Labels: :type/dev

#4193 Add pt-BR translations thx to ansjdn37 on discord
  src/main/frontend/dicts.cljs
  src/main/frontend/modules/shortcut/dict.cljs
Labels: :type/enhancement

#3976 enhance(ui): refine page title renaming dialog
  src/main/frontend/components/page.cljs
Labels: :type/enhancement, filenames

#4087 fix: long page stall loading and collapsed state
  src/main/frontend/components/block.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util.cljc
Labels: :type/bug-fix

#4200 Updated the EU Portuguese translation.
  src/main/frontend/dicts.cljs
Labels: :type/enhancement

#4167 fix(mobile): format only selected string as page reference
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4035 Enhance/Settings UI of plugins
  libs/package.json
  libs/src/LSPlugin.caller.ts
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  libs/src/helpers.ts
  libs/yarn.lock
  resources/js/lsplugin.core.js
  src/electron/electron/handler.cljs
  src/electron/electron/plugin.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/plugins_settings.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/components/theme.css
  src/main/frontend/db/model.cljs
  src/main/frontend/dicts.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
  src/main/logseq/api.cljs
Labels: :type/enhancement

#4231 fix(ui): unwanted left padding when pdf viewer active
  src/main/frontend/extensions/pdf/pdf.css
Labels: :type/bug-fix

#4236 Fixed some typos on the EU Portuguese translation
  src/main/frontend/dicts.cljs
Labels: :type/enhancement

#4226 enhance(iOS): ensure important files to be downloaded from iCloud
  ios/App/App/DownloadiCloudFiles.swift
Labels: :type/enhancement

#4247 fix(ui): checkbox floats above button
  src/main/frontend/components/page.css
Labels: fix

#4249 chore: bump minor version of libs package
  libs/package.json
  resources/js/lsplugin.user.js
Labels: :type/enhancement

#4245 enhance(mobile): editing in large block
  package.json
  src/main/frontend/components/editor.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/editor/lifecycle.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/ui.cljs
  src/main/frontend/util.cljc
Labels: :type/enhancement

#4253 perf: reduce pull-many quries for get-page-blocks
  src/main/frontend/db/model.cljs
  src/main/frontend/db/react.cljs
Labels: :type/performance

#4248 chore: bump version 0.6.0
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#4264 fix(mobile): tweet component loading fails
  package.json
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#4284 fix: srs cards can't be edited during preview or in /cards queries
  src/main/frontend/components/content.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/extensions/srs.cljs
Labels: :type/bug-fix

#4299 fix(ui): restrict max width of plugin settings panel
  src/main/frontend/components/plugins.css
Labels: :type/bug-fix

#4291 enhance(ui): ESC to cancel page rename
  resources/css/common.css
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page.css
Labels: :type/enhancement

#4303 fix: missing normalized for file watcher ipc
  src/main/frontend/fs/watcher_handler.cljs
Labels: :type/bug-fix

#4309 enhance(ui): refine electron context-menu
  src/electron/electron/context_menu.cljs
Labels: :type/enhancement

#4286 fix(android): app crashes
  src/main/frontend/config.cljs
  src/main/frontend/fs/capacitor_fs.cljs
  src/main/frontend/handler/file.cljs
  src/main/frontend/handler/web/nfs.cljs
  src/test/frontend/fs/capacitor_fs_test.cljs
Labels: :type/bug-fix

#4330 Add command to save graph to disk
  src/main/frontend/handler/events.cljs
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/feature

#3048 Load more journal entries
  .gitignore
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/route.cljs
  src/main/frontend/state.cljs
Labels: :type/hold

#4360 fix(ui): exit edit mode when prompt
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/bug-fix, fix

#4364 Add shadow test runner that provides most test-runner like options
  .carve/ignore
  deps.edn
  docs/dev-practices.md
  shadow-cljs.edn
  src/test/frontend/test_runner.cljs
Labels: :type/dev

#4322 test(e2e) for #4320: recent list is not updated
  e2e-tests/sidebar.spec.ts
  e2e-tests/utils.ts
Labels: fix

#4385 fix: sourcemap cannot load when developing
  shadow-cljs.edn
Labels: :type/bug-fix

#4367 feat: remember right sidebar width after resizing
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/handler/ui.cljs
Labels: feature

#4407 Avoid annoying javascript alert window for error debug
  src/main/frontend/fs/capacitor_fs.cljs
Labels: :type/dev
