Repository logseq/logseq, pull requests merged in 2022-08, with the labels that each got.

#6217 Spanish language strings added
  src/main/frontend/dicts.cljc
  templates/dummy-notes-es.md
  templates/tutorial-es.md
Labels: :type/feature

#6144 fix: recent in sidebar do not remember it's state
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#6214 Fix: Property completion for hidden properties and property ordering
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/test/logseq/graph_parser_test.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/search.cljs
Labels: :type/bug-fix

#6141 fix(style): cursor of restart text
  src/main/frontend/components/header.css
Labels: fix

#5964 Fix pasting race condition
  e2e-tests/editor.spec.ts
  e2e-tests/utils.ts
  package.json
  src/main/frontend/handler/editor.cljs
  src/main/frontend/ui.cljs
  yarn.lock
Labels: :type/bug-fix

#6199 fix: add :feature/enable-search-remove-accents
  src/main/frontend/components/search.cljs
  src/main/frontend/search.cljs
  src/main/frontend/search/db.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  templates/config.edn
Labels: :type/feature

#5995 fix(zotero): remove absolute file path from linked file path
  src/main/frontend/extensions/zotero/extractor.cljs
Labels: :type/bug-fix

#6176 fix: only show property search modal when current line is wrapped by . #6146
  src/main/frontend/handler/editor.cljs
  src/test/frontend/handler/editor_test.cljs
Labels: fix

#6296 fix: navigation with multiple selected blocks
  src/main/frontend/handler/editor.cljs
Labels: fix

#6299 fix(electron): handle corrupted search db
  src/electron/electron/search.cljs
Labels: fix

#6304 fix(ref): block embedded error
  src/main/frontend/components/block.cljs
Labels: fix

#6303 chore: bump version 0.8.0
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6032 Upgrade electron to 19
  package.json
  resources/package.json
  yarn.lock
Labels: upstream, :type/bug-fix

#6328 fix(android): handle home uri when picking folder
  android/app/src/main/java/com/logseq/app/FileUtil.java
Labels: :type/bug-fix

#6311 fix: cursor position cannot be moved when editing a page title
  src/main/frontend/handler/editor.cljs
Labels: fix

#6277 Fix wrapped-by? utility function
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util/text.cljs
  src/test/frontend/util/text_test.cljs
Labels: :type/bug-fix

#6256 fix: keep the favorites item when publishing
  src/main/frontend/components/sidebar.cljs
Labels: fix

#6085 fix: alias of page in sidebar did not redirect to the original page
  src/main/frontend/components/sidebar.cljs
Labels: :type/bug-fix

#6348 fix(plugin): initial plugin core with fatal argument of empty logseq dot root
  src/electron/electron/utils.cljs
  src/main/frontend/handler/plugin.cljs
Labels: :type/bug-fix

#6364 fix: roam export error caused by typo
  src/main/frontend/external/roam_export.cljs
Labels: :type/bug-fix

#6331 improve(custom.css): support import current graph assets file
  src/main/frontend/config.cljs
  src/main/frontend/handler/ui.cljs
Labels: :type/enhancement

#6369 chore: bump version 0.8.1
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6373 feat(settings): add plugin id to buttons and panel
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins_settings.cljs
  src/main/frontend/components/settings.cljs
Labels: feature

#6433 fix(editor): skip empty block when cycle todo
  src/main/frontend/handler/editor.cljs
Labels: fix

#6431 fix(shortcut): refine keyname trans
  src/main/frontend/modules/shortcut/data_helper.cljs
Labels: fix

#6439 chore: bump version 0.8.2
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6336 Feat: Config option to allow for longer, richer property values
  .carve/ignore
  deps/graph-parser/.carve/ignore
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/src/logseq/graph_parser/cli.cljs
  deps/graph-parser/src/logseq/graph_parser/config.cljs
  deps/graph-parser/src/logseq/graph_parser/mldoc.cljc
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  deps/graph-parser/src/logseq/graph_parser/text.cljs
  deps/graph-parser/src/logseq/graph_parser/util.cljs
  deps/graph-parser/src/logseq/graph_parser/util/page_ref.cljs
  deps/graph-parser/test/logseq/graph_parser/property_test.cljs
  deps/graph-parser/test/logseq/graph_parser/text_test.cljs
  deps/graph-parser/test/logseq/graph_parser_test.cljs
  shadow-cljs.edn
  src/main/frontend/components/block.cljs
  src/main/frontend/db/query_dsl.cljs
  src/test/frontend/db/query_dsl_test.cljs
  src/test/frontend/test/frontend_node_test_runner.cljs
  src/test/frontend/test/helper.clj
  src/test/frontend/test/node_test_runner.cljs
  templates/config.edn
Labels: :type/feature

#6461 fix: shift-click on recently searched page
  src/main/frontend/components/search.cljs
Labels: fix

#6469 Fix: Electron only commands should only show up in electron
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/bug-fix

#6474 fix(android): handle path with spaces
  android/app/src/main/java/com/logseq/app/FolderPicker.java
  android/app/src/main/java/com/logseq/app/FsWatcher.java
  src/main/frontend/fs/capacitor_fs.cljs
Labels: mobile:android, fix

#6473 enhance: Hide icon page property
  src/main/frontend/components/block.cljs
Labels: :type/enhancement

#6484 Chore: Document dwim config introduced in #2975
  templates/config.edn
Labels: :type/dev

#6482 fix(editor): handle delete image with no actual file
  src/main/frontend/components/block.cljs
Labels: fix

#6496 Improve backtick autopairing
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util/text.cljs
Labels: :type/enhancement

#6504 fix(build): use compatible escape for commands
  package.json
Labels: fix

#6489 Enhance: Whiteboards
  resources/css/common.css
  tldraw/.editorconfig
  tldraw/apps/tldraw-logseq/package.json
  tldraw/apps/tldraw-logseq/src/app.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/index.ts
  tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/constants.ts
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/lib/TLViewport.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/TLSelectTool.tsx
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/ContextMenuState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/IdleState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/index.ts
  tldraw/packages/core/src/utils/index.ts
  tldraw/packages/react/src/components/ContextBarContainer/ContextBarContainer.tsx
  tldraw/packages/react/src/constants.ts
  tldraw/yarn.lock
Labels: :type/enhancement

#6520 fix: tabindex console react warnings
  src/main/frontend/components/block.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/extensions/code.cljs
Labels: :type/bug-fix

#6510 Fix/custom css not reload
  src/main/frontend/components/file.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/extensions/code.cljs
  src/main/frontend/handler/ui.cljs
Labels: :type/bug-fix

#6522 fix(build): codesign on windows
  .github/workflows/build-desktop-release.yml
Labels: :type/bug-fix

#6526 feat: select element on context menu
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/ContextMenuState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/IdleState.ts
Labels: :type/feature

#6501 Adding E2E test for scenario with text after a soft return
  e2e-tests/editor.spec.ts
Labels: :type/dev

#6537 chore: bump version 0.8.3
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore
