Repository logseq/logseq, pull requests merged in 2022-01, with the labels that each got.

#3531 feat: add a secret global flag to load graph progammtically
  .gitignore
  e2e-tests/basic.spec.ts
  e2e-tests/fixtures.ts
  e2e-tests/utils.ts
  resources/js/preload.js
  src/electron/electron/core.cljs
  src/electron/electron/handler.cljs
  src/main/frontend/fs/node.cljs
  src/main/frontend/handler/export.cljs
  src/main/frontend/util.cljc
Labels: :type/dev

#3758 fix: graph view hang due to node / edge duplication
  src/main/frontend/extensions/graph/pixi.cljs
Labels: :type/bug-fix

#3770 fix(ci): wrong yml format
  .github/release.yml
Labels: :type/dev

#3771 CI: rename release title
  .github/release.yml
  .github/workflows/build-desktop-release.yml
Labels: :type/dev

#3776 fix(ui): missing padding in mark element
  resources/css/common.css
  src/main/frontend/components/search.cljs
Labels: :type/bug-fix

#3686 Enhance/marketplace
  e2e-tests/basic.spec.ts
  libs/src/LSPlugin.core.ts
  resources/js/lsplugin.core.js
  src/electron/electron/handler.cljs
  src/electron/electron/plugin.cljs
  src/main/frontend/components/command_palette.cljs
  src/main/frontend/components/command_palette.css
  src/main/frontend/components/header.cljs
  src/main/frontend/components/header.css
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/dicts.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
  src/main/frontend/util.cljc
Labels: :type/enhancement

#3810 ci: add pr labeler
  .github/pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: :type/dev

#3811 feat(debug): add debug func `defn`
  src/main/frontend/debug.clj
  src/main/frontend/debug.cljs
Labels: :type/dev

#3742 fix: some style enhancements to block-control
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/ui.cljs
Labels: :type/enhancement

#3831 fix(deps): bad colors.js
  package.json
  resources/package.json
Labels: :type/dev

#3838 enhance(ui): warning when journals date format chagne
  src/main/frontend/components/settings.cljs
Labels: :type/enhancement

#3784 fix(ui): layout css tweak
  src/main/frontend/components/header.css
  src/main/frontend/components/settings.css
  src/main/frontend/ui.css
Labels: :type/enhancement

#3858 fix(iOS): clicking unlinked reference blanks out
  src/main/frontend/db/model.cljs
Labels: :type/bug-fix

#3869 fix(electron): only show add to dictionary when misspelling
  src/electron/electron/window.cljs
Labels: :type/bug-fix

#3876 enhance(electron): support uncaught exceptions handler for main process
  src/electron/electron/core.cljs
  src/electron/electron/exceptions.cljs
  src/electron/electron/window.cljs
Labels: :type/enhancement

#3892 Fix ci(build): rename job
  .github/workflows/build.yml
Labels: fix

#3889 fix(electron): do not save cache for demo graph
  src/electron/electron/handler.cljs
Labels: :type/bug-fix

#3899 dev: fix gulp-watch cpu usage
  gulpfile.js
Labels: :type/dev

#3904 enhance(marketplace): plugin readme page ui position
  resources/marketplace.html
Labels: :type/enhancement

#3924 fix(lint): bad condition branch
  src/main/frontend/handler/plugin.cljs
Labels: :type/bug-fix

#3883 fix: datascript error blocks file watching
  src/main/frontend/components/block.cljs
  src/main/frontend/handler/extract.cljs
  src/main/frontend/handler/file.cljs
Labels: :type/bug-fix, need-to-refactor

#3926 test(e2e): allow test with newly opened graph
  e2e-tests/fixtures.ts
  e2e-tests/utils.ts
Labels: :type/dev

#3925 fix(editor): move block with top option (as before option for plugin api)
  src/main/frontend/handler/dnd.cljs
Labels: :type/bug-fix

#3855 Improve long page editing performance
  .github/workflows/build.yml
  e2e-tests/basic.spec.ts
  e2e-tests/basic.with-diacritics.spec.ts
  e2e-tests/code-editing.spec.ts
  e2e-tests/fixtures.ts
  package.json
  src/electron/electron/handler.cljs
  src/electron/electron/utils.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/repo.cljs
  src/main/frontend/db.cljs
  src/main/frontend/db/migrate.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/db/query_react.cljs
  src/main/frontend/db/utils.cljs
  src/main/frontend/db_schema.cljs
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/format/block.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/modules/file/core.cljs
  src/main/frontend/modules/outliner/core.cljs
  src/main/frontend/modules/outliner/file.cljs
  src/main/frontend/modules/outliner/tree.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  src/main/logseq/api.cljs
Labels: :type/enhancement

#3934 fix(ui): wrong precondition for open button
  src/main/frontend/components/header.cljs
Labels: :type/bug-fix

#3940 enhance(iPad): right sidebar resizer
  src/main/frontend/components/header.css
Labels: :type/enhancement

#3949 fix(editor): reorder auto-complete items
  src/main/frontend/components/editor.cljs
Labels: :type/enhancement, fix

#3954 chore: bump version 0.5.9
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev, chore

#3977 fix: add title property when necessary
  src/main/frontend/handler/page.cljs
  src/main/frontend/util.cljc
Labels: :type/regression, :type/bug-fix, fix

#3947 feat(ios): status bar style changes with logseq theme
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  src/main/frontend/utils.js
Labels: :type/feature

#3957 feat(android): enable write/refresh files when switching apps
  src/main/frontend/mobile/core.cljs
Labels: :type/enhancement

#4008 fix: custom js not work
  src/main/frontend/handler/ui.cljs
Labels: :type/bug-fix

#4009 Add a command to switch graphs
  src/main/frontend/components/command_palette.css
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/select.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/widgets.cljs
  src/main/frontend/config.cljs
  src/main/frontend/dicts.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
Labels: :type/feature

#4016 fix(iOS): make status bar style change in release mode
  src/main/frontend/util.cljc
  src/main/frontend/utils.js
Labels: :type/bug-fix

#4051 Fix block collapse state not being saved
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4043 feat: update chinese translation
  src/main/frontend/components/settings.cljs
  src/main/frontend/dicts.cljs
Labels: :type/enhancement

#4018 fix: ignore changes in bak folder
  src/electron/electron/fs_watcher.cljs
  src/electron/electron/utils.cljs
  src/main/frontend/handler/web/nfs.cljs
  src/main/frontend/util.cljc
  src/main/frontend/util/fs.cljs
Labels: :type/bug-fix

#3975 fix: title prop with double quotes
  src/main/frontend/handler/extract.cljs
  src/main/frontend/text.cljs
Labels: :type/bug-fix, fix

#3997 improve(plugin): api of `get_block` with shallow children uuid results
  src/main/logseq/api.cljs
Labels: :type/bug-fix

#4077 chore: update issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: :type/dev

#4080 Fix grammar and typos in issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: :type/dev

#4072 Add dicts CI job and dev tasks
  .github/workflows/build.yml
  bb.edn
  docs/contributing-to-translations.md
  scripts/src/logseq/rewrite_clj.clj
  scripts/src/logseq/tasks/dev.clj
  scripts/src/logseq/tasks/lang.clj
  scripts/src/logseq/tasks/util.clj
  src/main/frontend/components/header.cljs
  src/main/frontend/dicts.cljs
Labels: :type/feature
