Repository logseq/logseq, pull requests merged in 2022-06, with the labels that each got.

#5506 feat(electron): refine app menu
  src/electron/electron/core.cljs
Labels: feature

#5500 fix(editor): copy with both plain and rich text
  src/main/frontend/components/export.cljs
  src/main/frontend/handler/common.cljs
  src/main/frontend/util.cljc
  src/main/frontend/utils.js
Labels: fix

#5508 fix(deps): link static vcruntime under windows
  resources/package.json
Labels: fix

#5524 fix(electron): use different app menu for macos and others
  src/electron/electron/core.cljs
Labels: fix

#5479 Predefined view and transform
  src/main/frontend/components/block.cljs
  src/main/frontend/db/query_react.cljs
  src/main/frontend/extensions/sci.cljs
  templates/config.edn
Labels: query, settings

#5553 fix(graph-parser): avoid parsing illegal id
  deps/graph-parser/src/logseq/graph_parser/block.cljc
Labels: fix

#5554 fix(pdf): highlight refs lose association with related pdf
  src/main/frontend/extensions/pdf/assets.cljs
Labels: :type/enhancement

#5494 Feat/add age encrypt to sync
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/FileSync/AgeEncryption.swift
  ios/App/App/FileSync/Data+ChaChaPoly.swift
  ios/App/App/FileSync/Extensions.swift
  ios/App/App/FileSync/FileSync.m
  ios/App/App/FileSync/FileSync.swift
  ios/App/App/FileSync/SyncClient.swift
  ios/App/App/capacitor.config.json
  ios/App/LogseqSpecs/AgeEncryption.podspec
  ios/App/Podfile
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/file_sync.cljs
Labels: feature

#5557 Fix: toolbar not showing when using Apple Pencil and external keyboard on iPad
  src/main/frontend/mobile/footer.cljs
  src/main/frontend/mobile/mobile_bar.cljs
Labels: :type/bug-fix

#5576 chore: bump version 0.7.2
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#5628 fix: hard to reverse right swipe
  src/main/frontend/handler/block.cljs
Labels: :type/bug-fix

#5630 enhance(ui): force inline layout of block ref elements
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
Labels: :type/enhancement

#5629 fix(electron): register accelerator for mod+n
  src/electron/electron/core.cljs
Labels: fix

#5673 fix app not working on iOS 13
  package.json
  public/index.html
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#5655 enhance(ui): extra white space of code block from top
  src/main/frontend/extensions/code.css
Labels: :type/enhancement

#5671 enhance(plugin): change marketplace metadata requests to node fetch client
  src/electron/electron/handler.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/handler/plugin.cljs
Labels: :type/enhancement

#5699 fix: trim spaces when sanitizing page name
  src/main/frontend/extensions/pdf/assets.cljs
Labels: fix

#5715 fix(encryption): allow enter key when prompt passwd
  src/main/frontend/components/encryption.cljs
Labels: fix

#5717 enhance(ui): restore to show code block lang when narrow screen
  src/main/frontend/extensions/code.css
Labels: :type/enhancement

#5732 fix(editor): handle windows crlf in clipboard
  src/main/frontend/handler/paste.cljs
Labels: fix

#5744 Enhance: Allow graph-parser to also return ast data
  deps/graph-parser/.clj-kondo/config.edn
  deps/graph-parser/src/logseq/graph_parser.cljs
  deps/graph-parser/src/logseq/graph_parser/cli.cljs
  deps/graph-parser/src/logseq/graph_parser/extract.cljc
  deps/graph-parser/test/logseq/graph_parser/cli_test.cljs
  deps/graph-parser/test/logseq/graph_parser/extract_test.cljs
  src/main/frontend/handler/file.cljs
Labels: :type/enhancement

#5716 improve(plugin): fetch marketplace plugins list via system proxy if no proxy configured
  src/main/frontend/components/plugins.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/state.cljs
Labels: :type/enhancement

#5787 fix(editor): use denied tags in html to md conversion
  src/main/frontend/extensions/html_parser.cljs
Labels: fix

#5801 fix(android): handle quick deletion then creating
  android/app/src/main/java/com/logseq/app/FsWatcher.java
Labels: fix

#5804 fix(test): add delay to e2e testing
  e2e-tests/basic.spec.ts
Labels: fix

#5803 fix(electron): check destroyed window before access property
  src/electron/electron/window.cljs
Labels: fix

#5765 add bb tasks for mobile app development
  android/README.md
  bb.edn
  docs/develop-logseq-on-mobile.md
  docs/mobile.md
  ios/README.md
  scripts/set-system-env.sh
  scripts/src/logseq/tasks/dev.clj
Labels: :type/dev

#5823 fix bilibili video progress bar display
  src/main/frontend/components/block.cljs
Labels: fix

#5800 fix: block properties order missing #5788
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#5830 fix bilibili embed issues
  src/main/frontend/components/block.cljs
  src/main/frontend/util/text.cljs
Labels: :type/bug-fix

#5838 fix(editor): wrong cycle todo when heading symbol on the same line
  src/main/frontend/util/marker.cljs
Labels: fix

#5878 Fix: Close modal before opening more results
  src/main/frontend/components/search.cljs
Labels: :type/bug-fix

#5881 fix calc output position
  src/main/frontend/extensions/code.css
Labels: :type/bug-fix
