Repository logseq/logseq, pull requests merged in 2022-11, with the labels that each got.

#7111 Feat: Whiteboards color system
  resources/css/common.css
  resources/img/checker.png
  src/main/frontend/components/whiteboard.css
  tldraw/apps/tldraw-logseq/package.json
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
  tldraw/apps/tldraw-logseq/src/components/inputs/ColorInput.tsx
  tldraw/apps/tldraw-logseq/src/lib/color.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/BoxShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/EllipseShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/HighlighterShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/IFrameShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/LineShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/PenShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/PencilShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/PolygonShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/TextShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/style-props.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/cljs-demo/src/main/playground/tldraw.cljs
  tldraw/demo/src/App.jsx
  tldraw/packages/core/src/lib/shapes/TLShape/TLShape.tsx
  tldraw/packages/core/src/types/types.ts
  tldraw/packages/core/src/utils/ColorUtils.ts
  tldraw/packages/core/src/utils/index.ts
  tldraw/yarn.lock
Labels: :type/feature

#7193 Add french translations for shorcuts
  src/main/frontend/modules/shortcut/dicts.cljc
Labels: feature

#7207 Fix: Allow custom protocols
  src/main/frontend/security.cljs
Labels: :type/bug-fix

#7215 enhance(sync): filter pages whose page-name is too long
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#7219 Fix: Appimage desktop file entries
  resources/forge.config.js
  resources/package.json
Labels: :type/bug-fix

#7225 fix: make header component reactive on user/info state
  src/main/frontend/components/header.cljs
Labels: :type/bug-fix

#7227 fix: sync crashes
  src/main/frontend/components/encryption.cljs
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/core.cljs
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/file_sync.cljs
Labels: :type/bug-fix

#7238 fix total time calculation
  src/main/frontend/util/clock.cljs
  src/test/frontend/util/clocktime_test.cljs
Labels: fix

#7253 fix: unlink wrong graphs
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/repo.cljs
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/file_sync.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#7267 enhance(sync): check token not expired before api-calls
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/file_sync.cljs
  src/main/frontend/handler/user.clj
  src/main/frontend/handler/user.cljs
Labels: :type/enhancement

#7198 feat(paste): toggle between pasting text or file when they both exist
  src/main/frontend/components/settings.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/handler/config.cljs
  src/main/frontend/handler/paste.cljs
  src/main/frontend/state.cljs
Labels: feature

#7178 Always render the invalid block ref regardless of contents
  src/main/frontend/components/block.cljs
Labels: :type/feature

#7279 fix(mobile): show url-decoded filenames when re-indexing
  src/main/frontend/components/sidebar.cljs
Labels: fix

#7280 fix(mobile): use safe uri decode fn
  src/main/frontend/components/sidebar.cljs
Labels: fix

#7308 fix: journal pages write failed
  src/main/frontend/modules/file/core.cljs
Labels: :type/bug-fix

#7319 Small fix in documentation for browser development.
  docs/develop-logseq.md
Labels: fix

#7314 build: autoprefixer for generated css
  package.json
  postcss.config.js
  yarn.lock
Labels: :type/dev

#7339 fix: disable plugins system
  src/main/frontend/components/settings.cljs
  src/main/frontend/config.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#7353 fix(build): use npx to run tsup
  tldraw/apps/tldraw-logseq/build.mjs
Labels: fix

#7354 fix(build): android file sync prod env
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
Labels: :type/bug-fix

#7361 Add option to insert block without focusing it afterwards
  libs/src/LSPlugin.ts
  src/main/logseq/api.cljs
Labels: feature

#7373 fix: error while backup global config under windows
  src/main/frontend/fs/watcher_handler.cljs
Labels: fix

#7358 Feat (Whiteboards): Add main color panel and rearrange tools
  e2e-tests/whiteboards.spec.ts
  resources/css/common.css
  tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
  tldraw/apps/tldraw-logseq/src/components/GeometryTools/GeometryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/GeometryTools/index.ts
  tldraw/apps/tldraw-logseq/src/components/PrimaryTools/PrimaryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/ToolButton/ToolButton.tsx
  tldraw/apps/tldraw-logseq/src/components/ToolButton/index.ts
  tldraw/apps/tldraw-logseq/src/components/icons/LogseqIcon.tsx
  tldraw/apps/tldraw-logseq/src/components/icons/index.ts
  tldraw/apps/tldraw-logseq/src/components/inputs/ColorInput.tsx
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/BoxShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/style-props.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/BoxTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/EraseTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/HighlighterTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/LineTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/LogseqPortalTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/states/CreatingState.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/PencilTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/TextTool.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/lib/TLApi/TLApi.ts
  tldraw/packages/core/src/lib/TLSettings.ts
  tldraw/packages/core/src/lib/shapes/TLShape/TLShape.tsx
  tldraw/packages/core/src/lib/tools/TLBoxTool/states/CreatingState.tsx
  tldraw/packages/core/src/lib/tools/TLDrawTool/states/CreatingState.tsx
  tldraw/packages/core/src/lib/tools/TLLineTool/states/CreatingState.tsx
  tldraw/packages/core/src/lib/tools/TLMoveTool/TLMoveTool.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/TLSelectTool.tsx
  tldraw/packages/core/src/lib/tools/TLTextTool/states/CreatingState.tsx
Labels: :type/feature

#7352 chore(whiteboard): update dependencies
  tldraw/apps/tldraw-logseq/package.json
  tldraw/demo/package.json
  tldraw/demo/vite.config.js
  tldraw/packages/core/package.json
  tldraw/packages/react/package.json
  tldraw/yarn.lock
Labels: :type/dev

#7336 fix(whiteboard): whiteboard ux issues
  src/main/electron/listener.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/content.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/mobile/index.css
  src/main/frontend/modules/file/core.cljs
  src/main/frontend/ui.cljs
  tldraw/apps/tldraw-logseq/src/components/Devtools/Devtools.tsx
  tldraw/apps/tldraw-logseq/src/components/StatusBar/StatusBar.tsx
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
  tldraw/apps/tldraw-logseq/src/lib/preview-manager.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/ImageShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/YouTubeShape.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/demo/postcss.config.js
  tldraw/demo/src/App.jsx
  tldraw/packages/core/src/lib/TLSettings.ts
  tldraw/packages/core/src/utils/ColorUtils.ts
  tldraw/packages/react/package.json
  tldraw/packages/react/src/components/ui/Grid/Grid.tsx
  tldraw/packages/react/src/hooks/useGestureEvents.ts
  tldraw/packages/react/src/hooks/useStylesheet.ts
  tldraw/yarn.lock
Labels: :type/bug-fix

#7385 Fix: android nav bar and status bar color
  android/app/capacitor.build.gradle
  android/app/src/main/assets/capacitor.plugins.json
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  android/capacitor.settings.gradle
  ios/App/Podfile
  package.json
  src/main/frontend/handler.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  yarn.lock
Labels: fix

#7386 Fix: Title bar drag region
  src/main/frontend/components/header.cljs
  src/main/frontend/components/header.css
Labels: :type/bug-fix

#7320 enhance(ux): make dynamic width of absolute modal container to fit for widen screen.
  src/main/frontend/components/editor.cljs
Labels: :type/enhancement

#7343 Fixes shift+click on "all pages" launching a new browser window
  src/main/frontend/components/page.cljs
Labels: fix

#7375 fix #7283: customUUID not converted to UUID type
  src/main/logseq/api.cljs
Labels: fix

#7393 fix: copying whiteboard shapes into outliner
  src/main/frontend/handler/paste.cljs
Labels: :type/bug-fix

#7403 Enhance/api block UUID
  src/main/logseq/api.cljs
Labels: :type/enhancement

#7412 fix: skip whiteboard tests for now
  e2e-tests/whiteboards.spec.ts
Labels: :type/dev

#7415 fix(ios): apply path normalize for file-sync
  .github/workflows/build-ios.yml
  package.json
  yarn.lock
Labels: fix

#6945 Enhance / Plugin APIs
  e2e-tests/random.spec.ts
  e2e-tests/utils.ts
  libs/.npmignore
  libs/CHANGELOG.md
  libs/babel.config.json
  libs/package.json
  libs/src/LSPlugin.caller.ts
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  libs/src/modules/LSPlugin.Experiments.ts
  libs/src/modules/LSPlugin.Search.ts
  libs/webpack.config.js
  libs/yarn.lock
  resources/js/lsplugin.core.js
  resources/js/lsplugin.user.js
  src/electron/electron/plugin.cljs
  src/main/frontend/components/lazy_editor.cljs
  src/main/frontend/components/search.cljs
  src/main/frontend/components/search.css
  src/main/frontend/components/svg.cljs
  src/main/frontend/extensions/code.cljs
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/handler/search.cljs
  src/main/frontend/mobile/graph_picker.cljs
  src/main/frontend/search.cljs
  src/main/frontend/search/agency.cljs
  src/main/frontend/search/plugin.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/logseq/api.cljs
Labels: :type/enhancement

#7419 fix(ui): unexcept full widen container of demo home page
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
Labels: :type/bug-fix

#7426 fix(editor): do not wrap space when pasting <code>
  src/main/frontend/extensions/html_parser.cljs
Labels: fix

#7395 feat(whiteboard): shape links
  deps/graph-parser/src/logseq/graph_parser/whiteboard.cljs
  resources/css/tabler-extension.css
  resources/fonts/tabler-icons-extension.woff2
  src/main/electron/listener.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/handler/route.cljs
  src/main/frontend/handler/whiteboard.cljs
  src/main/frontend/modules/outliner/pipeline.cljs
  src/main/frontend/state.cljs
  tldraw/apps/tldraw-logseq/src/app.tsx
  tldraw/apps/tldraw-logseq/src/components/BlockLink/BlockLink.tsx
  tldraw/apps/tldraw-logseq/src/components/BlockLink/index.ts
  tldraw/apps/tldraw-logseq/src/components/Button/Button.tsx
  tldraw/apps/tldraw-logseq/src/components/Button/CircleButton.tsx
  tldraw/apps/tldraw-logseq/src/components/Button/index.ts
  tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/components/PopoverButton/PopoverButton.tsx
  tldraw/apps/tldraw-logseq/src/components/PopoverButton/index.ts
  tldraw/apps/tldraw-logseq/src/components/PrimaryTools/PrimaryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/QuickLinks/QuickLinks.tsx
  tldraw/apps/tldraw-logseq/src/components/QuickLinks/index.ts
  tldraw/apps/tldraw-logseq/src/components/QuickSearch/QuickSearch.tsx
  tldraw/apps/tldraw-logseq/src/components/QuickSearch/index.ts
  tldraw/apps/tldraw-logseq/src/components/StatusBar/StatusBar.tsx
  tldraw/apps/tldraw-logseq/src/components/icons/TablerIcon.tsx
  tldraw/apps/tldraw-logseq/src/components/inputs/ColorInput.tsx
  tldraw/apps/tldraw-logseq/src/components/inputs/ShapeLinksInput.tsx
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
  tldraw/apps/tldraw-logseq/src/lib/logseq-context.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/LineShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/TextShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/arrow/Arrow.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/index.ts
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/demo/src/App.jsx
  tldraw/demo/src/index.css
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/lib/shapes/TLLineShape/TLLineShape.tsx
  tldraw/packages/core/src/lib/shapes/TLShape/TLShape.tsx
  tldraw/packages/core/src/lib/tools/TLDrawTool/states/index.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/IdleState.ts
  tldraw/packages/core/src/types/types.ts
  tldraw/packages/core/src/utils/ColorUtils.ts
  tldraw/packages/react/src/components/Canvas/Canvas.tsx
  tldraw/packages/react/src/components/ContextBarContainer/ContextBarContainer.tsx
  tldraw/packages/react/src/components/ReferencesCountContainer copy/QuickLinksContainer.tsx
  tldraw/packages/react/src/components/ReferencesCountContainer copy/index.ts
  tldraw/packages/react/src/components/ReferencesCountContainer/ReferencesCountContainer.tsx
  tldraw/packages/react/src/components/ReferencesCountContainer/index.ts
  tldraw/packages/react/src/components/Renderer/RendererContext.tsx
  tldraw/packages/react/src/components/ui/Grid/Grid.tsx
  tldraw/packages/react/src/hooks/useStylesheet.ts
  tldraw/packages/react/src/types/component-props.ts
Labels: :type/feature

#7368 fix(props): show hierarchy for page alias
  deps/graph-parser/src/logseq/graph_parser/text.cljs
  src/main/frontend/components/hierarchy.cljs
Labels: fix

#7430 fix(test): e2e fail due to opened new-page dialog
  e2e-tests/page-search.spec.ts
Labels: fix

#7434 enhance(ui): add class options for icon ui component
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#7433 fix: notify users if page name already exists when parsing files
  src/main/frontend/handler/common/file.cljs
  src/main/frontend/handler/repo.cljs
Labels: :type/bug-fix

#7438 enhance: check instrument payload
  src/main/frontend/handler/events.cljs
Labels: :type/enhancement

#7445 ci(ios): add testflight build
  .github/workflows/build-ios-release.yml
  ios/App/fastlane/Appfile
  ios/App/fastlane/Fastfile
  ios/App/fastlane/README.md
Labels: :type/dev

#7449 fix: filename format revert manual title check
  src/main/frontend/handler/conversion.cljs
  src/test/frontend/db/name_sanity_test.cljs
Labels: fix

#7453 enhance(sync): add IRemoteControlAPI
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#7463 chore(ios): config keys of non-exmpect encryption
  ios/App/App/Info.plist
Labels: chore

#7464 fix(sync): add fake size for the fake event
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#7447 enhance(sync): remove sync-stop-chan and simplify the stop process
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#7466 fix(mobile): missing urlencode when sharing asset url
  src/main/frontend/components/block.cljs
Labels: fix

#7468 fix(pdf): missing min max value of page number
  src/main/frontend/extensions/pdf/toolbar.cljs
Labels: fix

#7469 Fix/sync download s3 404 by unnormalized path
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#7472 fix(ios): ipad toolbar position when hiding keyboard
  src/main/frontend/handler/events.cljs
Labels: fix

#7490 fix(ui): use default font family for headings
  resources/css/common.css
Labels: fix

#7493 fix(sync): won't refresh tokens&remote-graphs after started app
  src/main/frontend/handler/user.cljs
Labels: :type/bug-fix

#7494 improve(ui): icons of file sync indicator
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/file_sync.css
Labels: :type/enhancement

#7487 fix: zoom menu trigger should not gain focus on close LOG-1962
  tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
  tldraw/packages/react/src/components/Canvas/Canvas.tsx
Labels: :type/bug-fix

#7488 fix: optimize block link reference display in whiteboard
  tldraw/apps/tldraw-logseq/src/components/BlockLink/BlockLink.tsx
  tldraw/apps/tldraw-logseq/src/components/QuickLinks/QuickLinks.tsx
  tldraw/apps/tldraw-logseq/src/components/inputs/ShapeLinksInput.tsx
  tldraw/packages/core/src/lib/TLSettings.ts
Labels: :type/feature

#7491 fix: hovered or selected shape should have higher zindex
  tldraw/packages/react/src/components/Canvas/Canvas.tsx
Labels: :type/feature

#7496 fix: decrease Object Action Bar distance when below portal
  tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx
  tldraw/packages/react/src/index.ts
Labels: :type/feature

#7504 fix: can't paste nested blocks into an empty block
  src/main/frontend/handler/editor.cljs
  src/main/frontend/modules/outliner/core.cljs
  src/test/frontend/modules/outliner/core_test.cljs
Labels: :type/bug-fix

#7516 fix(ci): use LOGSEQ_CI instead of reserved CI
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  shadow-cljs.edn
Labels: :type/bug-fix

#7521 fix: build local file metadatas
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#7526 fix: remove false alarm of the event to force ios path
  src/main/frontend/fs/capacitor_fs.cljs
Labels: :type/bug-fix

#7523 enhance: sent graphs-txid in sentry events
  src/main/frontend/format/block.cljs
  src/main/frontend/handler/events.cljs
Labels: :type/enhancement

#7440 Feat: Whiteboards onboarding
  resources/img/whiteboard-welcome-dark.png
  resources/img/whiteboard-welcome-light.png
  src/main/frontend/components/onboarding/quick_tour.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/components/whiteboard.css
  src/main/frontend/dicts.cljc
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/user.cljs
  src/main/frontend/state.cljs
Labels: :type/feature

#7535 fix: sync stopped working after taking a photo
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#7534 fix(mobile): refactor mobile camera toolbar command
  src/main/frontend/handler/editor.cljs
  src/main/frontend/mobile/camera.cljs
Labels: fix

#7537 fix: sync icon disappear with unstable network
  src/main/frontend/handler/events.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix
