Repository logseq/logseq, pull requests merged in 2022-03, with the labels that each got.

#4383 fix: set timestamp to another editing block
  src/main/frontend/components/datetime.cljs
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4373 enhance(electron): add custom https proxy options for settings
  resources/package.json
  src/electron/electron/core.cljs
  src/electron/electron/handler.cljs
  src/electron/electron/plugin.cljs
  src/electron/electron/utils.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/dicts.cljs
  static/yarn.lock
Labels: :type/enhancement

#4413 enhance: add zh-Hans-CN check in zh-CN-supported command
  src/main/frontend/util.cljc
Labels: :type/enhancement

#4396 enhance(dev): not sync static files in development to decrease cup usage
  gulpfile.js
  shadow-cljs.edn
Labels: :type/enhancement

#4384 fix wrong block marker toggle if its reference is in editing
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4422 Feat: be able to collapse keyboard on mobile
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/editor.css
Labels: :type/feature

#4382 fix: wrong logbook creation
  src/main/frontend/commands.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util/marker.cljs
  src/test/frontend/util/marker_test.cljs
Labels: :type/bug-fix

#4433 fix(android): backspace can't delete empty block
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4432 Dev: Rewrite tests from #4382 to use with-redefs
  shadow-cljs.edn
  src/test/frontend/handler/editor_test.cljs
  src/test/frontend/util/marker_test.cljs
Labels: :type/dev

#4434 Fix: Display error if dsl query fails hard
  src/main/frontend/db/query_dsl.cljs
  src/main/frontend/db/query_react.cljs
Labels: :type/bug-fix

#4418 fix(mobile): unable to load and render excalidraw file
  src/main/frontend/fs/capacitor_fs.cljs
Labels: :type/bug-fix

#4444 fix italic syntax typo in help
  src/main/frontend/components/shortcut.cljs
Labels: :type/bug-fix

#4446 fix(android): unable to display asset image
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4371 feat(ios): add polling based file watcher
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/DownloadiCloudFiles.m
  ios/App/App/FileContainer.swift
  ios/App/App/FsWatcher.m
  ios/App/App/FsWatcher.swift
  src/main/frontend/fs.cljs
  src/main/frontend/fs/capacitor_fs.cljs
  src/main/frontend/handler/file.cljs
  src/main/frontend/handler/web/nfs.cljs
  src/main/frontend/mobile/util.cljs
Labels: :type/feature

#4453 fix(ios): nil timer in fs watcher
  ios/App/App/FsWatcher.swift
Labels: :type/bug-fix, fix

#4451 feat: ✨ notifications-content support \n
  src/main/frontend/ui.cljs
Labels: :type/enhancement

#4470 fix: List properties out of order when contain more than 8 elements
  src/main/frontend/format/block.cljs
  src/main/frontend/text.cljs
Labels: :type/bug-fix

#4480 Test for wrong namespace routes fix
  src/main/frontend/db/model.cljs
  src/test/frontend/db/model_test.cljs
Labels: :type/bug-fix

#4424 Optimizing nested query rules for graph traversal
  src/main/frontend/db/model.cljs
  src/main/frontend/db/rules.cljs
Labels: :type/enhancement

#4485 Fix/wrong namespace routes
  src/main/frontend/db/model.cljs
  src/test/frontend/db/model_test.cljs
Labels: :type/bug-fix

#4472 enhance(ui): persist widen mode state
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
  src/main/frontend/handler/ui.cljs
  src/main/frontend/state.cljs
Labels: :type/enhancement

#4459 fix: id link in orgmode format
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#4469 fix: remove assets/draws from All Pages
  src/main/frontend/format/block.cljs
  src/main/frontend/handler/page.cljs
Labels: :type/bug-fix

#4473 feat: support block-embed alias in OrgMode
  src/main/frontend/components/block.cljs
Labels: :type/feature

#4474 enhance: ignore logbook and default properties in unlinked reference
  src/main/frontend/db/model.cljs
Labels: :type/enhancement

#4420 Fix page-property bug
  deps.edn
  src/main/frontend/db/query_dsl.cljs
  src/main/frontend/db/query_react.cljs
  src/main/frontend/db/rules.cljs
  src/test/frontend/db/query_dsl_test.cljs
  src/test/frontend/node_test_runner.cljs
Labels: :type/bug-fix

#4441 Fix: task and priority query bug
  src/main/frontend/db/query_dsl.cljs
  src/main/frontend/db/rules.cljs
  src/test/frontend/db/query_dsl_test.cljs
Labels: :type/bug-fix

#4492 chore: bump version 0.6.2
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#4496 fix(api): return value of move block #4409
  src/main/logseq/api.cljs
Labels: :type/bug-fix

#4512 fix(dev): sourcemap path in electron while dev
  package.json
  shadow-cljs.edn
Labels: :type/dev

#4514 fix(electron): unwatch dir when needed
  src/electron/electron/fs_watcher.cljs
  src/electron/electron/handler.cljs
Labels: fix

#4524 fix(editor): error whilte cycling todos
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix, fix

#4525 fix(query): yesterday should be a date
  src/main/frontend/db/query_react.cljs
Labels: fix

#4535 Feature: flashcards random mode
  gulpfile.js
  package.json
  resources/css/tabler-icons.min.css
  resources/fonts/tabler-icons.eot
  resources/fonts/tabler-icons.woff
  resources/fonts/tabler-icons.woff2
  src/main/frontend/extensions/srs.cljs
  static/yarn.lock
  yarn.lock
Labels: :type/feature

#4515 chore: bump version 0.6.3
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#4545 fix(tablet): toolbar width
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/editor.css
Labels: :type/bug-fix

#4567 fix(code): avoid calling saving handler too often
  src/main/frontend/extensions/code.cljs
Labels: fix

#4561 fix: cloze selector
  src/main/frontend/components/block.css
Labels: fix

#4536 fix: block disappears when drag to another block
  src/main/frontend/handler/dnd.cljs
Labels: :type/bug-fix

#4573 fix #+keyword issues in orgmode
  src/main/frontend/components/block.cljs
  src/main/frontend/format/mldoc.cljs
  src/main/frontend/text.cljs
  templates/config.edn
Labels: :type/enhancement

#4589 fix: cycle marker will remove `#` unexpectedly
  src/main/frontend/util/marker.cljs
  src/test/frontend/util/marker_test.cljs
Labels: fix

#4591 fix: replace-block-reference-with-content-at-point not working
  e2e-tests/editor.spec.ts
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4602 fix: use the correct variable in (seq coll)
  src/main/frontend/components/repo.cljs
Labels: fix

#4618 fix: sentry
  package.json
  resources/package.json
  src/main/frontend/modules/instrumentation/sentry.cljs
  yarn.lock
Labels: :type/bug-fix

#4621 enhance: separate desktop and mobile in Sentry for better issue management
  src/main/frontend/modules/instrumentation/sentry.cljs
Labels: :type/dev

#4630 fix: broken links in docs
  docs/contributing-to-translations.md
  docs/develop-logseq.md
Labels: fix

#4627 Fix: rules to advanced query and outdated yarn.lock
  .github/workflows/build.yml
  src/main/frontend/db/query_custom.cljs
  src/test/frontend/db/query_custom_test.cljs
  static/yarn.lock
Labels: :type/bug-fix

#4631 Fix sentry platform not showing up on issues
  src/main/frontend/modules/instrumentation/sentry.cljs
Labels: :type/bug-fix

#4629 fix(mobile): ignore bak and recycle in fs watcher
  android/app/src/main/java/com/logseq/app/FsWatcher.java
  ios/App/App/FsWatcher.swift
Labels: fix

#4633 fix(ci): add sentry sourcemaps
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
Labels: fix

#4615 Chore: bump version 0.6.4
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev, chore

#4450 remove refresh button / updated notifications on mobile
  ios/App/App/DownloadiCloudFiles.m
  ios/App/App/DownloadiCloudFiles.swift
  src/main/frontend/components/header.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/mobile/core.cljs
  src/main/frontend/mobile/util.cljs
Labels: :type/enhancement

#4664 fix(code): avoid calling .focus when editor close
  src/main/frontend/extensions/code.cljs
Labels: :type/bug-fix, fix

#4667 fix(editor): error while toggling fav in journals
  src/main/frontend/handler/page.cljs
Labels: :type/bug-fix, fix

#4691 fix: detect the first block in a page
  src/main/frontend/handler/editor.cljs
Labels: fix

#4710 fix(build): sourcemap in release
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
  src/main/frontend/modules/instrumentation/sentry.cljs
Labels: fix

#4694 chore: bump version 0.6.5
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#4716 fix(build): dugite arch under macOS arm64
  .github/workflows/build-desktop-release.yml
Labels: fix

#4703 Fix clicking on all in srs cards - close #4687
  src/main/frontend/extensions/srs.cljs
Labels: :type/bug-fix

#4652 BREAKING CHANGE: unify light mode identifier
  resources/css/common.css
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  src/main/logseq/api.cljs
Labels: chore

#4727 fix(build): deps for macos arm64 build
  .github/workflows/build-desktop-release.yml
Labels: fix

#4726 chore: reduce extra rendering
  src/main/frontend/components/block.cljs
Labels: chore

#4599 feat(mobile): share intent
  android/app/capacitor.build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/capacitor.plugins.json
  android/app/src/main/java/com/logseq/app/MainActivity.java
  android/capacitor.settings.gradle
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/App.entitlements
  ios/App/App/AppDebug.entitlements
  ios/App/App/AppDelegate.swift
  ios/App/App/Info.plist
  ios/App/Podfile
  ios/App/ShareViewController/Base.lproj/MainInterface.storyboard
  ios/App/ShareViewController/Info.plist
  ios/App/ShareViewController/ShareViewController.entitlements
  ios/App/ShareViewController/ShareViewController.swift
  package.json
  src/main/frontend/config.cljs
  src/main/frontend/mobile/core.cljs
  src/main/frontend/mobile/intent.cljs
  templates/config.edn
  yarn.lock
Labels: :type/feature

#4681 Patch tutorial i18n
  src/main/frontend/dicts.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/modules/shortcut/dict.cljs
  templates/dummy-notes-ja.md
  templates/tutorial-ja.md
Labels: :type/enhancement

#4773 fix: some unique "key" prop issues
  src/main/frontend/components/block.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#4769 Enhance: Add error screen for root component
  src/main/frontend/page.cljs
  src/main/frontend/ui.css
Labels: :type/feature
