Repository logseq/logseq, pull requests merged in 2022-04, with the labels that each got.

#4753 Enhance: Allow translations throughout the application
  .clj-kondo/config.edn
  bb.edn
  docs/contributing-to-translations.md
  scripts/src/logseq/tasks/lang.clj
  scripts/src/logseq/tasks/rewrite_clj.clj
  src/main/frontend/components/search.cljs
  src/main/frontend/context/i18n.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/handler.cljs
  src/main/frontend/handler/command_palette.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/data_helper.cljs
  src/main/frontend/modules/shortcut/dict.cljs
  src/main/frontend/modules/shortcut/dicts.cljc
  src/main/frontend/modules/shortcut/macro.cljc
  src/main/frontend/spec.cljs
  src/test/frontend/context/i18n_test.cljs
Labels: :type/enhancement

#4784 Enhance: validate local storage
  bb.edn
  docs/dev-practices.md
  scripts/src/logseq/tasks/spec.clj
  src/main/frontend/components/settings.cljs
  src/main/frontend/handler/config.cljs
  src/main/frontend/spec.cljs
  src/main/frontend/spec/storage.cljc
  src/main/frontend/storage.cljs
Labels: :type/enhancement

#4789 fix: preview image file with capitalized extension
  src/main/frontend/util.cljc
Labels: :type/bug-fix

#4790 fix redundant relative path when inserting orgmode page reference
  src/main/frontend/handler/page.cljs
Labels: :type/bug-fix

#4794 feat(list): enable checkbox toggle
  src/main/frontend/components/block.cljs
  src/main/frontend/handler/editor.cljs
Labels: :type/feature

#4580 Feature/Setups of Onboarding Process
  .carve/ignore
  e2e-tests/basic.spec.ts
  e2e-tests/fixtures.ts
  e2e-tests/utils.ts
  resources/css/common.css
  resources/img/file-edn.png
  resources/img/folder-logo.png
  resources/img/folder.png
  shadow-cljs.edn
  src/main/frontend/components/block.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/header.css
  src/main/frontend/components/journal.cljs
  src/main/frontend/components/onboarding.cljs
  src/main/frontend/components/onboarding.css
  src/main/frontend/components/onboarding/index.css
  src/main/frontend/components/onboarding/setups.cljs
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/svg.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/components/widgets.cljs
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/extensions/video/youtube.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/handler/user.cljs
  src/main/frontend/handler/web/nfs.cljs
  src/main/frontend/routes.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  templates/tutorial-en.md
Labels: :type/feature

#4802 fix(editor): cannot create journal
  src/main/frontend/db/model.cljs
Labels: :type/regression, fix

#3839 feat: file sync
  android/app/build.gradle
  android/app/src/main/java/com/logseq/app/GraphFileSync.java
  android/file-sync/.gitignore
  android/file-sync/build.gradle
  android/file-sync/consumer-rules.pro
  android/file-sync/proguard-rules.pro
  android/file-sync/src/androidTest/java/com/logseq/file_sync/ExampleInstrumentedTest.java
  android/file-sync/src/main/AndroidManifest.xml
  android/file-sync/src/main/java/com/logseq/file_sync/FileSync.java
  android/file-sync/src/main/jniLibs/arm64-v8a/libfilesync.so
  android/file-sync/src/main/jniLibs/armeabi-v7a/libfilesync.so
  android/file-sync/src/main/jniLibs/x86/libfilesync.so
  android/file-sync/src/main/jniLibs/x86_64/libfilesync.so
  android/file-sync/src/test/java/com/logseq/file_sync/ExampleUnitTest.java
  android/settings.gradle
  resources/forge.config.js
  resources/package.json
  src/electron/electron/core.cljs
  src/electron/electron/file_sync_rsapi.cljs
  src/electron/electron/handler.cljs
  src/main/electron/listener.cljs
  src/main/frontend/commands.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/svg.cljs
  src/main/frontend/config.cljs
  src/main/frontend/core.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/file_sync.cljs
  src/main/frontend/handler/user.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  src/main/frontend/util/persist_var.cljs
  static/yarn.lock
Labels: :type/feature

#4813 Made error page look more designed
  src/main/frontend/components/page.css
  src/main/frontend/page.cljs
Labels: :type/enhancement

#4800 fix(i18n): rename translate key
  src/main/frontend/components/page.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/dicts.cljc
Labels: fix

#4823 fix(publishing): order of scripts
  src/main/frontend/publishing/html.cljs
Labels: fix

#4846 Fix a few onboarding logseq capitalizations
  src/main/frontend/components/onboarding/setups.cljs
Labels: :type/bug-fix

#4847 Enhance: Better issue links
  src/main/frontend/components/onboarding.cljs
  src/main/frontend/mobile/intent.cljs
  src/main/frontend/page.cljs
  src/main/frontend/ui.cljs
Labels: :type/enhancement

#4850 fix(ui): wrong condition for rendering heading
  src/main/frontend/components/block.cljs
Labels: fix

#4870 fix: do not persist var under demo graph
  src/main/frontend/util/persist_var.cljs
Labels: fix

#4869 feat(sync): support dev&prod env
  resources/package.json
  src/electron/electron/file_sync_rsapi.cljs
  src/electron/electron/handler.cljs
  src/main/frontend/config.cljs
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/user.cljs
Labels: :type/feature

#4878 fix(mobile): page blank when switching graph
  src/main/frontend/handler/events.cljs
Labels: fix

#4787 feat(mobile): dynamically reorder toolbar commands by click counts
  src/main/frontend/components/editor.cljs
Labels: :type/feature

#4766 Feat: record audio on mobile
  android/app/capacitor.build.gradle
  android/app/src/main/assets/capacitor.config.json
  android/app/src/main/assets/capacitor.plugins.json
  android/capacitor.settings.gradle
  capacitor.config.ts
  ios/App/App/Info.plist
  ios/App/App/capacitor.config.json
  ios/App/Podfile
  package.json
  resources/css/common.css
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/editor.css
  src/main/frontend/components/header.cljs
  src/main/frontend/components/header.css
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page.css
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/config.cljs
  src/main/frontend/extensions/code.cljs
  src/main/frontend/extensions/code.css
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/mobile/camera.cljs
  src/main/frontend/mobile/core.cljs
  src/main/frontend/mobile/footer.cljs
  src/main/frontend/mobile/index.css
  src/main/frontend/mobile/intent.cljs
  src/main/frontend/mobile/record.cljs
  src/main/frontend/state.cljs
  src/main/frontend/text.cljs
  src/main/frontend/ui.css
  src/main/frontend/util.cljc
  yarn.lock
Labels: :type/feature

#4887 fix: increase `td` width to prevent content overflow
  src/main/frontend/components/page.cljs
Labels: fix

#4899 fix quick capture template not working
  src/main/frontend/mobile/intent.cljs
Labels: :type/bug-fix

#4905 fix(plugin): sometimes settings GUI of plugin not work when entry from app settings pane
  src/main/frontend/components/plugins_settings.cljs
Labels: :type/bug-fix

#4903 fix(sync): fix unfinishable sync loop
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#4921 don't create new contents file when changing format
  src/main/frontend/handler/repo.cljs
Labels: :type/bug-fix

#4915 fix pasting in src block not working on iOS
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#4917 fix playing video goes into editing mode on iOS
  src/main/frontend/components/block.cljs
  src/main/frontend/util.cljc
Labels: :type/bug-fix

#4913 fix mobile toolbar order not persisting after restart
  src/main/frontend/components/editor.cljs
Labels: :type/bug-fix

#4924 fix(ui): warn about illegal git commit interval
  src/main/frontend/components/settings.cljs
Labels: fix

#4925 style(settings): line-space of general/journals
  src/main/frontend/components/settings.cljs
Labels: fix

#4922 chore: bump version 0.6.6
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#4955 fix(electron): wrong graph-identifier condition
  src/electron/electron/url.cljs
Labels: fix

#4961 fix(editor): missing variable in macro expansion
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix, fix

#4880 Core outliner operations refactoring
  e2e-tests/editor-random.spec.ts
  e2e-tests/editor.spec.ts
  e2e-tests/utils.ts
  src/main/electron/listener.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/content.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/db.cljs
  src/main/frontend/db/conn.cljs
  src/main/frontend/db/debug.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/db/outliner.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/db/utils.cljs
  src/main/frontend/db_schema.cljs
  src/main/frontend/extensions/code.cljs
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/external/roam_export.cljs
  src/main/frontend/format/block.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/block.cljs
  src/main/frontend/handler/dnd.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/export.cljs
  src/main/frontend/handler/external.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/mobile/footer.cljs
  src/main/frontend/mobile/intent.cljs
  src/main/frontend/mobile/record.cljs
  src/main/frontend/modules/editor/undo_redo.cljs
  src/main/frontend/modules/outliner/core.cljs
  src/main/frontend/modules/outliner/datascript.cljc
  src/main/frontend/modules/outliner/transaction.cljc
  src/main/frontend/modules/outliner/utils.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  src/main/frontend/util/page_property.cljs
  src/main/logseq/api.cljs
  src/test/frontend/core_test.cljs
  src/test/frontend/db/query_dsl_test.cljs
  src/test/frontend/modules/outliner/core_test.cljs
  src/test/frontend/modules/outliner/ds_test.cljs
  src/test/frontend/test/fixtures.cljs
Labels: :type/enhancement

#4933 enhance(card): refine card ui
  src/main/frontend/extensions/srs.cljs
Labels: :type/enhancement

#4981 fix: code block in published graph is not copyable
  src/main/frontend/extensions/code.cljs
Labels: :type/bug-fix

#5005 fix(sync): check current graph belongs to current logged-in user
  src/main/frontend/config.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#5006 feat: custom query title may also render rich texts
  src/main/frontend/components/block.cljs
Labels: feature

#4992 fix(utils): classname utils for string input
  src/main/frontend/util.cljc
Labels: :type/bug-fix

#4977 feat: expose start-of-week to plugins
  libs/src/LSPlugin.ts
  src/main/logseq/api.cljs
Labels: :type/feature

#4995 fix: search modal jumps on mobile
  src/main/frontend/components/command_palette.css
  src/main/frontend/components/search.cljs
Labels: :type/bug-fix

#4828 Enhance/more ns plugin api
  libs/.prettierrc.js
  libs/package.json
  libs/src/LSPlugin.caller.ts
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.shadow.ts
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  libs/src/callable.apis.ts
  libs/src/helpers.ts
  libs/src/modules/LSPlugin.Experiments.ts
  libs/src/modules/LSPlugin.Storage.ts
  libs/src/postmate/index.ts
  libs/webpack.config.js
  libs/yarn.lock
  resources/js/lsplugin.core.js
  src/electron/electron/git.cljs
  src/electron/electron/handler.cljs
  src/electron/electron/plugin.cljs
  src/electron/electron/utils.js
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/hierarchy.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/plugins_settings.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/notification.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/handler/shell.cljs
  src/main/frontend/loader.cljs
  src/main/frontend/modules/outliner/pipeline.cljs
  src/main/frontend/state.cljs
  src/main/logseq/api.cljs
Labels: :type/enhancement

#5022 fix: Cmd-v sometimes pastes wrong content
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#5030 fix: should not display onboarding card in published graph
  src/main/frontend/components/sidebar.cljs
Labels: fix

#4990 add shortcuts for opening file in default app and directory
  src/main/frontend/modules/shortcut/config.cljs
Labels: feature

#4947 enhance(iOS): add a modal to instruct users to select valid directory
  ios/App/App/FolderPicker.swift
  src/main/frontend/fs/capacitor_fs.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/ui.css
Labels: :type/enhancement

#5061 fix: page crash when navigating to home if default home is a custom page
  src/main/frontend/handler/route.cljs
Labels: :type/bug-fix

#5072 fix scroll lags on iOS images
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#5152 chore: bump version 0.6.7
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore
