Repository logseq/logseq, pull requests merged in 2022-09, with the labels that each got.

#6542 fix: do not loading persist vars when nil graph
  src/main/frontend/config.cljs
Labels: fix

#6534 Enhance: Whiteboards
  tldraw/apps/tldraw-logseq/build.mjs
  tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/react/src/components/ContextBarContainer/ContextBarContainer.tsx
Labels: :type/enhancement

#6551 fix(android): crash at start, accessing illegal path
  src/main/frontend/fs/capacitor_fs.cljs
  src/main/frontend/handler.cljs
Labels: fix

#6550 fix(ux): sometimes hamburger not responding on mobile
  src/main/frontend/components/sidebar.css
Labels: :type/bug-fix

#6546 fix: aways clean all load state when nfs open
  src/main/frontend/handler/web/nfs.cljs
Labels: fix

#6553 improve(ui): nested scroll container for left sidebar dynamic modules
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
Labels: :type/bug-fix

#6555 fix: cloud icon is not shown when restarting the app
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
Labels: :type/bug-fix

#6560 fix: confirm that file exists to unlink
  tldraw/apps/tldraw-logseq/build.mjs
Labels: :type/bug-fix

#6552 chore: bump version 0.8.4
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6568 fix(api): returns of raw datascript query
  src/main/logseq/api.cljs
Labels: :type/bug-fix

#6570 feat: zoom buttons
  tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx
  tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
Labels: :type/feature

#6582 fix: remove monitor-dirs
  src/main/frontend/fs/sync.cljs
  src/test/frontend/fs/sync_test.cljs
  templates/config.edn
Labels: :type/bug-fix

#6583 chore: remove outdated comments
  src/main/frontend/fs/sync.cljs
Labels: :type/dev

#6597 fix: remove tricky check for sync
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#6598 fix: get graph-uuid from graphs-txid.edn
  src/main/frontend/handler/file_sync.cljs
Labels: :type/bug-fix

#6599 fix: FileMetadata add iequiv and ihash
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#6601 fix: FileMetadata support keyword access
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#6602 Fix: Whiteboards scroll zoom event
  tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/LogseqPortalTool.tsx
  tldraw/packages/core/src/lib/TLViewport.ts
  tldraw/packages/core/src/lib/tools/TLMoveTool/states/PinchingState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/PinchingState.ts
Labels: :type/bug-fix

#6573 Introduce e2e tests for whiteboards
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/components/whiteboard.cljs
  tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx
  tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
Labels: :type/enhancement

#6130 fix(ui): dsl-query style
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#6605 fix: remove unused check
  src/main/frontend/fs/sync.cljs
Labels: :type/dev

#6606 Fix: Linkable built in properties should not display as rich properties
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#6632 fix: persist var init promise
  src/main/frontend/util/persist_var.cljs
Labels: fix

#6646 fix(search): cannot batch insert to search db
  src/main/frontend/search.cljs
Labels: :type/regression, fix

#6650 fix(sync): api calls fail when network offline
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/user.cljs
Labels: :type/bug-fix

#6659 Dev: Enable two disabled kondo linters and bump kondo deps
  .clj-kondo/config.edn
  deps.edn
  deps/db/deps.edn
  deps/graph-parser/deps.edn
  src/electron/electron/handler.cljs
  src/main/electron/listener.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/encryption.cljs
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/plugins_settings.cljs
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/ui.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/util/cursor.cljs
  src/main/logseq/api.cljs
Labels: :type/dev

#6664 fix(mobile): loading stuck caused by global config loading
  ios/App/App/FileSync/FileSync.swift
  src/main/frontend/handler.cljs
  src/main/frontend/handler/global_config.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/mobile/core.cljs
Labels: fix

#6672 fix(ui): mobile left sidebar overflow hidden
  src/main/frontend/components/sidebar.css
Labels: fix

#6696 chore(dev): rm unused workspace card
  .github/workflows/build-android.yml
  Dockerfile
  deps.edn
  public/workspaces/index.html
  shadow-cljs.edn
  src/workspaces/workspaces/cards.cljs
  src/workspaces/workspaces/main.cljs
Labels: chore

#6699 Fix: 3 user actions broken by global-config in mobile or web
  src/main/frontend/handler/file.cljs
  src/main/frontend/handler/global_config.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/handler/web/nfs.cljs
Labels: :type/bug-fix

#6703 fix(ios): file-sync reload when running
  ios/App/App/FileSync/FileSync.m
  ios/App/App/FileSync/FileSync.swift
  src/main/frontend/encrypt.cljs
Labels: :type/bug-fix

#6706 fix: config cleared if passed content is nil
  src/main/frontend/handler/file.cljs
  src/main/frontend/handler/repo_config.cljs
  src/main/frontend/state.cljs
  templates/config.edn
Labels: :type/bug-fix

#6705 enhance: add "Show password"
  src/main/frontend/components/encryption.cljs
Labels: :type/enhancement

#6708 chore: bump version 0.8.6
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6725 fix(ios): use .default qos for encription
  ios/App/App/FileSync/FileSync.swift
Labels: fix

#6724 fix: clicking sync icon restarts the file sync
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/handler/file_sync.cljs
Labels: :type/bug-fix

#6726 Revert "chore: increase the max width of main container"
  resources/css/common.css
Labels: :type/bug-fix

#6731 chore: bump version 0.8.7
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6749 Fix: Make resizer draggable on desktop only
  src/main/frontend/components/sidebar.css
Labels: :type/bug-fix

#6693 [WIP] Feat: Create element on drag n drop
  src/main/frontend/extensions/tldraw.cljs
  tldraw/apps/tldraw-logseq/src/app.tsx
  tldraw/apps/tldraw-logseq/src/components/Devtools/Devtools.tsx
  tldraw/apps/tldraw-logseq/src/hooks/useDrop.ts
  tldraw/apps/tldraw-logseq/src/hooks/useFileDrop.ts
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
  tldraw/apps/tldraw-logseq/src/lib/logseq-context.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/BindingIndicator.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/BoxShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/ImageShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/lib/TLApi/TLApi.ts
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/lib/TLBaseLineBindingState.ts
  tldraw/packages/core/src/types/types.ts
  tldraw/packages/core/src/utils/BindingUtils.ts
  tldraw/packages/core/src/utils/index.ts
  tldraw/packages/react/src/hooks/index.ts
  tldraw/packages/react/src/hooks/useCanvasEvents.ts
  tldraw/packages/react/src/hooks/useSetup.ts
  tldraw/packages/react/src/index.ts
  tldraw/packages/react/src/types/TLReactSubscriptions.tsx
Labels: :type/feature

#6772 Fix: Resizer position
  src/main/frontend/components/sidebar.css
Labels: :type/bug-fix

#6742 enhance(sync): add get-deletion-logs
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#6766 Fix & refine Polish (`pl`) translations
  src/main/frontend/dicts.cljc
  templates/tutorial-pl.md
Labels: fix

#6707 Feat: Create button on sidebar and command panel enhancements
  resources/css/common.css
  resources/css/tabler-extension.css
  resources/fonts/tabler-icons-extension.woff2
  src/main/frontend/components/command_palette.css
  src/main/frontend/components/header.css
  src/main/frontend/components/search.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/handler/whiteboard.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/data_helper.cljs
  src/main/frontend/modules/shortcut/dicts.cljc
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
Labels: :type/feature

#6790 Prefer text type on dnd
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
Labels: :type/bug-fix

#6765 Fix sort-by filter for simple queries
  src/main/frontend/components/query_table.cljs
  src/main/frontend/db/query_dsl.cljs
  src/test/frontend/db/query_dsl_test.cljs
Labels: :type/bug-fix

#6791 Dev: Add linter to deps to document namespaces
  .github/workflows/db.yml
  .github/workflows/graph-parser.yml
  deps/db/bb.edn
  deps/db/src/logseq/db.cljs
  deps/db/src/logseq/db/default.cljs
  deps/db/src/logseq/db/schema.cljs
  deps/graph-parser/bb.edn
  deps/graph-parser/src/logseq/graph_parser.cljs
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/src/logseq/graph_parser/config.cljs
  deps/graph-parser/src/logseq/graph_parser/extract.cljc
  deps/graph-parser/src/logseq/graph_parser/log.cljs
  deps/graph-parser/src/logseq/graph_parser/mldoc.cljc
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  deps/graph-parser/src/logseq/graph_parser/text.cljs
  deps/graph-parser/src/logseq/graph_parser/utf8.cljs
  deps/graph-parser/src/logseq/graph_parser/util/block_ref.cljs
  deps/graph-parser/src/logseq/graph_parser/util/page_ref.cljs
  docs/dev-practices.md
Labels: :type/dev

#6803 chore(build): file-sync production env as default
  shadow-cljs.edn
Labels: build

#6662 Feat: sync progress for electron
  gulpfile.js
  package.json
  resources/css/common.css
  resources/package.json
  src/electron/electron/file_sync_rsapi.cljs
  src/electron/electron/handler.cljs
  src/main/electron/listener.cljs
  src/main/frontend/components/encryption.cljs
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/file_sync.css
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/file_sync.cljs
  src/main/frontend/handler/metadata.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/handler/web/nfs.cljs
  src/main/frontend/modules/outliner/file.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  yarn.lock
Labels: :type/feature

#6812 Dev: Use catch :default for default error handling in cljs
  src/electron/electron/configs.cljs
  src/electron/electron/core.cljs
  src/electron/electron/git.cljs
  src/electron/electron/handler.cljs
  src/electron/electron/utils.cljs
  src/electron/electron/window.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/date.cljs
  src/main/frontend/db.cljs
  src/main/frontend/db/outliner.cljs
  src/main/frontend/db/query_react.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/db/utils.cljs
  src/main/frontend/diff.cljs
  src/main/frontend/extensions/excalidraw.cljs
  src/main/frontend/extensions/graph/pixi.cljs
  src/main/frontend/extensions/latex.cljs
  src/main/frontend/extensions/pdf/utils.cljs
  src/main/frontend/extensions/sci.cljs
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/format/mldoc.cljs
  src/main/frontend/fs/watcher_handler.cljs
  src/main/frontend/handler/block.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/editor/lifecycle.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/external.cljs
  src/main/frontend/handler/image.cljs
  src/main/frontend/handler/metadata.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/handler/ui.cljs
  src/main/frontend/mixins.cljs
  src/main/frontend/modules/datascript_report/core.cljs
  src/main/frontend/modules/instrumentation/posthog.cljs
  src/main/frontend/modules/outliner/datascript.cljc
  src/main/frontend/modules/outliner/file.cljs
  src/main/frontend/modules/shortcut/core.cljs
  src/main/frontend/modules/shortcut/data_helper.cljs
  src/main/frontend/page.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/util.cljc
  src/main/frontend/util/clock.cljs
  src/main/frontend/util/drawer.cljs
  src/main/frontend/util/persist_var.cljs
  src/main/logseq/api.cljs
Labels: :type/dev

#6802 Feat: Alignment and distribution actions on context menu
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/handler/whiteboard.cljs
  src/main/frontend/modules/shortcut/config.cljs
  tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextBar/ContextBar.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/components/PrimaryTools/PrimaryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/Toolbar/ToolBar.tsx
  tldraw/apps/tldraw-logseq/src/components/Toolbar/index.ts
  tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/types/types.ts
  tldraw/packages/core/src/utils/BoundsUtils.ts
  tldraw/packages/core/src/utils/SvgPathUtils.ts
Labels: :type/feature

#6832 fix(ui): polish alignments of svg icons
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
Labels: :type/bug-fix

#6833 fix(sync): synced pictures not reload on mobile
  deps/graph-parser/src/logseq/graph_parser/config.cljs
Labels: :type/bug-fix

#6856 fix(android): key code nil sometimes
  src/main/frontend/handler/editor.cljs
Labels: fix

#6837 Fix: Container scrolling on sidebar editing
  src/main/frontend/util.cljc
Labels: :type/bug-fix

#6850 Enhance: Whiteboards UX
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
  src/main/frontend/ui.cljs
  tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/BoxTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/DotTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/EllipseTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/EraseTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/HighlighterTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/LineTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/LogseqPortalTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/PencilTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/PolygonTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/TextTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/YouTubeTool.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/lib/tools/TLMoveTool/TLMoveTool.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/TLSelectTool.tsx
  tldraw/packages/react/src/hooks/index.ts
Labels: :type/enhancement
