Repository logseq/logseq, pull requests merged in 2022-07, with the labels that each got.

#5908 (chore): Update getAllPages typescript
  libs/src/LSPlugin.ts
Labels: chore

#5912 fix(ui) trailing space of search-auto-complete
  src/main/frontend/components/search.cljs
Labels: fix

#5914 fix(editor): bad format copy from html
  src/main/frontend/extensions/html_parser.cljs
Labels: fix

#5915 fix(editor): more support for html convertion
  src/main/frontend/extensions/html_parser.cljs
Labels: fix

#5934 fix(ui): remove plugin ui items manager from pagebar
  src/main/frontend/components/plugins.cljs
Labels: :type/bug-fix

#5884 only validate documents url when it non-nils
  ios/App/App/FileContainer.swift
Labels: :type/bug-fix

#5935 fix(editor): reorder items in page search auto-complete
  src/main/frontend/components/editor.cljs
Labels: fix

#5966 fix(editor): new-page auto-completion under non-en environment
  src/main/frontend/handler/page.cljs
Labels: fix

#5958 Add heading in plugin settings
  libs/src/LSPlugin.ts
  src/main/frontend/components/plugins.css
  src/main/frontend/components/plugins_settings.cljs
Labels: feature

#5960 fix: quick capture across desktops
  src/electron/electron/core.cljs
  src/electron/electron/url.cljs
  src/electron/electron/utils.cljs
Labels: :type/bug-fix

#5973 Another fix for page bouncing for lazy loading
  src/main/frontend/components/block.cljs
  src/main/frontend/components/journal.cljs
  src/main/frontend/components/reference.cljs
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#5936 fix commands menu not updating on Android
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#5990 fix flashcards not working
  src/main/frontend/extensions/srs.cljs
Labels: :type/bug-fix

#6000 don't enter editing when click query table
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#5889 fix key duplicates caused by key case when insert page property
  src/main/frontend/util/page_property.cljs
Labels: :type/bug-fix

#6016 fix click not working on cards preview mode
  src/main/frontend/extensions/srs.cljs
Labels: :type/bug-fix

#5997 fix: export as html issue
  resources/js/preload.js
Labels: :type/bug-fix

#6024 Enhance: Property page enhancements
  .github/workflows/graph-parser.yml
  deps/graph-parser/.carve/ignore
  deps/graph-parser/README.md
  deps/graph-parser/package.json
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
  deps/graph-parser/test/logseq/graph_parser/block_test.cljs
  deps/graph-parser/test/logseq/graph_parser/cli_test.cljs
  e2e-tests/page-search.spec.ts
  src/main/frontend/components/block.cljs
  src/main/frontend/config.cljs
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/util/property.cljs
  templates/config.edn
Labels: :type/bug-fix

#6045 Plugin settings add data-key
  src/main/frontend/components/plugins_settings.cljs
Labels: feature

#6061 fix(references): block references crash
  src/main/frontend/db/model.cljs
Labels: :type/bug-fix

#6063 Fix/boolean in query table
  src/main/frontend/components/query_table.cljs
Labels: :type/bug-fix

#6103 fix: should only log query when debug is enabled
  src/main/frontend/db/query_dsl.cljs
  src/main/frontend/db/query_react.cljs
Labels: :type/bug-fix

#6015 Bump version 0.7.7
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6062 feat: added property exclude-in-graph
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/handler/graph.cljs
Labels: feature

#6118 fix(build): codesign error
  resources/package.json
Labels: :type/dev

#6119 chore: bump version 0.7.8
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6129 fix(ui): inline code style
  resources/css/common.css
Labels: fix

#6132 feat(file-sync): impl updateLocalVersionFiles for ios
  ios/App/App/FileSync/FileSync.swift
  ios/App/App/FileSync/SyncClient.swift
  src/main/frontend/fs/sync.cljs
Labels: feature

#6127 fix alignment of macOS icon
  resources/icons/logseq_big_sur.icns
  resources/icons/logseq_big_sur.ico
  resources/icons/logseq_big_sur.png
Labels: :type/bug-fix

#6139 Enhance: Add command to re-index graph
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/dicts.cljc
Labels: :type/enhancement

#6113 don't enter editing state when click query table result on iOS
  src/main/frontend/components/block.cljs
  src/main/frontend/components/query_table.cljs
Labels: :type/bug-fix

#6138 Fix: page properties not reading property-pages config
  deps/db/package.json
  deps/db/yarn.lock
  deps/graph-parser/package.json
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/src/logseq/graph_parser/extract.cljc
  deps/graph-parser/test/logseq/graph_parser/extract_test.cljs
  deps/graph-parser/yarn.lock
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/page.cljs
Labels: :type/bug-fix

#6158 fix: make the title of sidebar item clickable. #4983
  src/main/frontend/components/right_sidebar.cljs
Labels: fix

#6120 feat: hide journals in page graph
  src/main/frontend/components/page.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/handler/graph.cljs
  src/test/frontend/db/model_test.cljs
Labels: feature

#6183 fix(pdf): missing cmaps resources
  src/main/frontend/extensions/pdf/_viewer.css
  src/main/frontend/extensions/pdf/highlights.cljs
Labels: :type/bug-fix

#6188 fix(android): unlink file crashes app
  src/main/frontend/fs/capacitor_fs.cljs
Labels: fix

#6168 chore(release): bump version 0.7.9
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: chore

#6212 improve(pdf): friendly breakline for multiple language highlights text
  src/main/frontend/extensions/pdf/utils.cljs
Labels: :type/enhancement

#6115 fix: remove links for each level of the namespaces hierarchy pages in global graph view
  src/main/frontend/db/model.cljs
  src/test/frontend/db/model_test.cljs
Labels: fix
