Repository logseq/logseq, pull requests merged in 2022-12, with the labels that each got.

#7542 test(e2e): refine test cases
  e2e-tests/editor.spec.ts
  e2e-tests/fixtures.ts
  e2e-tests/util/keyboard-events.ts
Labels: :type/bug-fix

#7545 fix: bug report url on native mobile
  .github/ISSUE_TEMPLATE/bug_report.yaml
  capacitor.config.ts
  src/main/frontend/components/header.cljs
Labels: :type/bug-fix

#7394 fix: handle illegal global config
  src/main/frontend/state.cljs
Labels: fix

#7552 fix(conf): global config should failback to repo config
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#7553 chore/suppress lint
  src/main/frontend/util.cljc
Labels: :type/dev

#7554 fix(pdf): wrong default page number when first open
  src/main/frontend/extensions/pdf/highlights.cljs
Labels: :type/bug-fix

#7556 fix(electron): quick captured text is cleared when editing current
  src/main/electron/listener.cljs
Labels: :type/bug-fix

#7544 chore(dev): cleanup unused package.json entries
  .github/workflows/build-android.yml
  .github/workflows/build.yml
  package.json
  resources/package.json
  yarn.lock
Labels: :type/dev

#7571 fix(editor): missing hierarchy in parent page
  src/main/frontend/components/hierarchy.cljs
Labels: :type/bug-fix

#7577 e2e: reenable whiteboard e2e
  e2e-tests/whiteboards.spec.ts
Labels: :type/bug-fix

#7549 feat(api): add keepUUID option to insertBatchBlock
  libs/src/LSPlugin.ts
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/handler/editor.cljs
  src/main/logseq/api.cljs
Labels: feature

#7598 Fix macOS release build
  .gitignore
  static/yarn.lock
Labels: :type/bug-fix

#7583 feat: animate canvas camera movement
  tldraw/apps/tldraw-logseq/src/components/ZoomMenu/ZoomMenu.tsx
  tldraw/apps/tldraw-logseq/src/hooks/useQuickAdd.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/states/CreatingState.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/lib/TLApi/TLApi.ts
  tldraw/packages/core/src/lib/TLViewport.ts
Labels: :type/feature

#7609 Deprecate: use g c to git commit instead of `c`
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/bug-fix

#7492 Enhance/mobile UX
  resources/css/common.css
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/header.cljs
  src/main/frontend/components/header.css
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page.css
  src/main/frontend/components/reference.cljs
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/sidebar.css
  src/main/frontend/components/theme.css
  src/main/frontend/handler/config.cljs
  src/main/frontend/mobile/index.css
  src/main/frontend/state.cljs
  src/main/frontend/ui.css
  src/main/frontend/util.cljc
Labels: :type/enhancement

#7616 fix(typo): wrong case of macOS
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: fix

#7625 refactor!(shortcut): use mod+g c for git commit
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/bug-fix

#7473 Feat (Whiteboards): Support text overlay on shapes
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
  tldraw/apps/tldraw-logseq/src/components/GeometryTools/GeometryTools.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/BoxShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/EllipseShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/LineShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/PolygonShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/text/TextLabel.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
Labels: :type/feature

#7617 feat: dnd sidebar to whiteboard
  src/main/frontend/components/block.cljs
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/whiteboard.cljs
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
Labels: :type/feature

#7629 fix(sync): sort-file-metadata-fn take custom journal dir into account
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#7632 Dev: Update rewrite-edn and hickory deps
  deps.edn
  shadow-cljs.edn
  src/main/frontend/extensions/hickory.cljc
  src/main/frontend/extensions/html_parser.cljs
  src/test/frontend/extensions/zotero/extractor_test.cljs
Labels: :type/dev

#7646 fix: stop file sync when re-index
  src/main/frontend/handler/events.cljs
Labels: :type/bug-fix

#7659 chore: provide i18n for settings-page
  src/main/frontend/components/settings.cljs
  src/main/frontend/dicts.cljc
Labels: chore

#7685 fix: skip parent-left check when exporting for whiteboards
  src/main/frontend/db/model.cljs
Labels: :type/bug-fix

#7643 Feat: Use tooltips instead of titles on whiteboard buttons
  e2e-tests/whiteboards.spec.ts
  tldraw/apps/tldraw-logseq/package.json
  tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx
  tldraw/apps/tldraw-logseq/src/components/Button/Button.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/components/GeometryTools/GeometryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/PrimaryTools/PrimaryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/ToolButton/ToolButton.tsx
  tldraw/apps/tldraw-logseq/src/components/Tooltip/Tooltip.tsx
  tldraw/apps/tldraw-logseq/src/components/Tooltip/index.ts
  tldraw/apps/tldraw-logseq/src/components/inputs/ColorInput.tsx
  tldraw/apps/tldraw-logseq/src/components/inputs/SelectInput.tsx
  tldraw/apps/tldraw-logseq/src/components/inputs/ShapeLinksInput.tsx
  tldraw/apps/tldraw-logseq/src/components/inputs/ToggleGroupInput.tsx
  tldraw/apps/tldraw-logseq/src/components/inputs/ToggleInput.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/BoxTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/EraseTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/HighlighterTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/LineTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/LogseqPortalTool/LogseqPortalTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/PencilTool.tsx
  tldraw/apps/tldraw-logseq/src/lib/tools/TextTool.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/demo/src/App.jsx
  tldraw/packages/core/src/lib/tools/TLMoveTool/TLMoveTool.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/TLSelectTool.tsx
  tldraw/yarn.lock
Labels: :type/feature

#7688 Fix: Tooltip without shortcuts
  tldraw/apps/tldraw-logseq/src/components/ToolButton/ToolButton.tsx
Labels: :type/bug-fix

#7651 fix: allows empty config.edn
  src/main/frontend/handler/global_config.cljs
Labels: :type/bug-fix

#7698 fix(ui): missing padding of the modal container on mobile
  src/main/frontend/handler/events.cljs
  src/main/frontend/ui.css
Labels: :type/bug-fix

#7701 fix: fs/readdir return no-such-dir exception
  src/main/frontend/handler/file_sync.cljs
Labels: :type/bug-fix

#7650 fix: open inline block refs by default when zoom in a block
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#7717 enhance(ux): precise interaction region for right fold-down button
  src/main/frontend/components/theme.css
Labels: :type/enhancement

#7660 fix(dev): indeterminate warning
  src/main/frontend/components/page.cljs
Labels: fix

#7727 fix(dev): do not use posthog when dev
  src/main/frontend/modules/instrumentation/posthog.cljs
Labels: :type/dev

#7690 fixes for PDF context menu
  src/main/frontend/extensions/pdf/highlights.cljs
Labels: fix

#7713 feat: grouping & ungrouping shapes
  src/main/frontend/handler/paste.cljs
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/lib/preview-manager.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/BoxShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/GroupShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/PolygonShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/index.ts
  tldraw/demo/src/App.jsx
  tldraw/packages/core/src/constants.ts
  tldraw/packages/core/src/lib/TLApi/TLApi.ts
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/lib/TLHistory.ts
  tldraw/packages/core/src/lib/shapes/TLDotShape/TLDotShape.test.ts
  tldraw/packages/core/src/lib/shapes/TLGroupShape/TLGroupShape.tsx
  tldraw/packages/core/src/lib/shapes/TLGroupShape/index.ts
  tldraw/packages/core/src/lib/shapes/index.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/BrushingState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/ContextMenuState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/PointingShapeBehindBoundsState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/PointingShapeState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/TranslatingState.ts
  tldraw/packages/react/src/components/AppCanvas.tsx
  tldraw/packages/react/src/components/Canvas/Canvas.tsx
Labels: :type/feature

#7723 fix: db/entity with interger id is not nil with non-exist block
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/db/utils.cljs
  src/main/frontend/handler/editor.cljs
  src/test/frontend/db/model_test.cljs
Labels: :type/bug-fix

#7732 fix: copy block-ref instantly after input text lost block content
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#7721 fix: stop sync when re-index
  src/main/frontend/handler/web/nfs.cljs
Labels: :type/bug-fix

#7735 enhance(dev): add `cljs:dev-release-electron`
  package.json
Labels: build, :type/dev

#7742 fix(electron): windows path in fswatcher
  src/electron/electron/handler.cljs
Labels: :type/bug-fix

#7745 fix: backup the file in db when moving a file with a different case
  src/main/frontend/fs.cljs
  src/main/frontend/handler/common/file.cljs
Labels: :type/bug-fix

#7767 fix: don't send pixi exceptions to sentry
  src/main/frontend/extensions/graph/pixi.cljs
Labels: :type/bug-fix

#7555 Enhance/plugin APIs
  libs/CHANGELOG.md
  libs/package.json
  libs/src/LSPlugin.caller.ts
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  libs/src/helpers.ts
  libs/src/postmate/index.ts
  resources/js/lsplugin.core.js
  resources/js/lsplugin.user.js
  resources/package.json
  src/electron/electron/configs.cljs
  src/electron/electron/handler.cljs
  src/electron/electron/shell.cljs
  src/electron/electron/utils.cljs
  src/main/frontend/commands.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/shell.cljs
  src/main/frontend/extensions/pdf/highlights.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/handler/shell.cljs
  src/main/frontend/modules/layout/core.cljs
  src/main/frontend/state.cljs
  src/main/logseq/api.cljs
  static/yarn.lock
Labels: :type/enhancement

#7777 chore(build): use token from ci env for sentry and posthog
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
  .github/workflows/build-ios-release.yml
  shadow-cljs.edn
  src/main/frontend/modules/instrumentation/posthog.cljs
  src/main/frontend/modules/instrumentation/sentry.cljs
Labels: :type/dev

#7776 fix: block Reference only return the first level of data
  src/main/frontend/components/block.cljs
  src/main/frontend/db/model.cljs
Labels: :type/bug-fix

#7781 fix: pencil issue when drawing quickly
  tldraw/packages/react/src/hooks/useCanvasEvents.ts
Labels: :type/bug-fix

#7793 fix: linked References Filter Empty
  src/main/frontend/db/model.cljs
Labels: :type/bug-fix

#7751 Fix: query table sorting
  src/main/frontend/components/query_table.cljs
  src/test/frontend/components/query_table_test.cljs
Labels: :type/bug-fix

#7801 Fix: Provide consistent page links for web and publishing
  src/main/frontend/handler/route.cljs
  src/test/frontend/handler/route_test.cljs
Labels: :type/bug-fix

#7774 Enable iOS file sharing for transfer files with the Finder or iTunes
  ios/App/App/Info.plist
Labels: feature

#7820 fix(plugin): correct parameters of datascript query api
  libs/CHANGELOG.md
  libs/package.json
  libs/src/LSPlugin.user.ts
  libs/webpack.config.js
Labels: :type/bug-fix

#7836 fix(editor): move caret for the block right-boundary in the journals list page
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#7779 enhance: replace util/distinct-by
  deps/graph-parser/deps.edn
  deps/graph-parser/src/logseq/graph_parser/util.cljs
  src/electron/electron/search.cljs
  src/main/frontend/util.cljc
Labels: :type/enhancement

#8126 improve(ui): right sidebar visibility based on response layout
  src/main/frontend/components/right_sidebar.cljs
Labels: :type/enhancement

#8116 enhance: memoize electron?, mobile?, etc
  src/main/frontend/util.cljc
Labels: :type/enhancement

#8140 enhancement: change page/version-history wording
  src/main/frontend/dicts.cljc
Labels: :type/enhancement, looking-for-review

#8132 feature: Display full search result in the web app
  src/main/frontend/components/search.cljs
Labels: :type/feature, feature

#8146 fix(fs): normalize path when readdir
  src/main/frontend/fs.cljs
Labels: :type/bug-fix

#8147 fix(rsapi): add fname unicode normalization
  package.json
  resources/package.json
  src/electron/electron/file_sync_rsapi.cljs
  static/yarn.lock
  yarn.lock
Labels: :type/bug-fix

#8139 enhancement: add several internationalizations to the right-click menu
  src/main/frontend/components/content.cljs
Labels: :type/enhancement, i18n

#8153 fix: set min width for modal
  src/main/frontend/components/commit.cljs
  src/main/frontend/ui.css
Labels: :type/bug-fix

#8151 fix: skip saving files if those files were just deleted from db
  src/main/frontend/fs/watcher_handler.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/modules/outliner/pipeline.cljs
Labels: :type/bug-fix

#7803 feat: mod+a to select parent up to the whole page
  src/main/frontend/handler/editor.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/dicts.cljc
  src/main/frontend/state.cljs
Labels: :type/feature

#8156 Feat: close stale issues action
  .github/stale-issues.yml
  .github/workflows/stale-issues.yml
Labels: :type/feature, :type/dev

#8166 enhance(sync): reduce ws ping messages
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#8162 fix(stale-issues.yml): add awaiting-respose step
  .github/workflows/stale-issues.yml
Labels: :type/dev, looking-for-review, fix
