Repository logseq/logseq, pull requests merged in 2023-07, with the labels that each got.

#9704 fix(ui): revise graph name dropdown
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/select.cljs
  src/main/frontend/util/text.cljs
Labels: :type/bug-fix

#9828 fix(ios): empty repo-url on first-boot(logged)
  src/main/frontend/util/text.cljs
Labels: :type/bug-fix

#9831 fix(sync): tune merge priority, current change first
  src/main/frontend/fs/diff_merge.cljs
  src/test/frontend/fs/diff_merge_test.cljs
Labels: :type/bug-fix

#9847 fix(plugin): hook fenced code renderer for multiple providers
  src/main/frontend/handler/plugin.cljs
Labels: :type/bug-fix

#9857 Add note about unsafe exposed port for dockker commands
  docs/docker-web-app-guide.md
Labels: :type/bug-fix

#9861 Fix: Header button drag region
  src/main/frontend/components/header.css
Labels: :type/bug-fix

#9882 fix(ui): close context menu when page navs
  src/main/frontend/handler.cljs
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#9854 chore(deps): Fix CVE-2023-2931 in Electron 24 [minor change]
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: chore

#9878 fix(server): sometimes the API server autostart not working
  src/main/frontend/handler.cljs
Labels: :type/bug-fix

#9881 Chore: release 0.9.11
  android/app/build.gradle
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#9933 fix(sync): page history on mobile platforms
  src/main/frontend/handler/file_sync.cljs
  src/main/frontend/util/fs.cljs
Labels: :type/bug-fix

#9932 fix(fs): editing global config on windows
  src/main/frontend/components/file.cljs
Labels: :type/bug-fix

#9945 Fix (draw): Remove outdated styles
  resources/css/common.css
Labels: :type/bug-fix

#9951 chore(deps): update diff-merge
  ios/App/App.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: :type/dev

#9959 Fix: Setting default sidebar pages on config
  src/main/frontend/components/container.cljs
Labels: :type/bug-fix

#9919 Fix (Draw): Persist when updating existing elements
  src/main/frontend/extensions/excalidraw.cljs
Labels: :type/bug-fix
