Repository logseq/logseq, pull requests merged in 2023-04, with the labels that each got.

#8983 fix(fs): whiteboards drop file on win32
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#8982 fix(editor): assets link resolve
  src/main/frontend/handler/assets.cljs
Labels: :type/bug-fix

#8966 fix: decode username for jwt
  src/main/frontend/handler/user.cljs
Labels: :type/bug-fix

#9013 fix: disable backspace from the start and delete at the end for query
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#9025 enhance(ux): add an apply button to multiple selects in query builder
  src/main/frontend/components/query/builder.cljs
  src/main/frontend/components/select.cljs
Labels: :type/enhancement

#9042 fix(api): sometimes the http api server not auto restart
  src/main/frontend/components/server.cljs
Labels: :type/bug-fix

#9041 fix(ui): unwanted reset style from amplify ui
  packages/amplify/src/amplify.ts
  packages/amplify/src/styles.css
  resources/css/amplify.css
Labels: :type/bug-fix

#9050 Enhance: Improve Russian (ru) translations
  src/main/frontend/dicts.cljc
  templates/dummy-notes-ru.md
  templates/tutorial-ru.md
Labels: i18n

#9072 enhance(ui): add hint class for the blank content block
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
Labels: :type/enhancement

#9026 enhance: show custom title instead of live query for custom queries
  src/main/frontend/components/block.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/query.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/format/mldoc.cljs
  src/main/frontend/handler/editor.cljs
Labels: :type/enhancement

#9078 Correct a comment in config.edn
  templates/config.edn
Labels: feature

#9074 fix: buggy selection hightlights
  src/main/frontend/components/block.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#9037 Feat: Export to image
  deps/publishing/src/logseq/publishing/html.cljs
  public/index.html
  resources/css/common.css
  resources/electron.html
  resources/index.html
  resources/js/html2canvas.min.js
  src/main/frontend/components/content.cljs
  src/main/frontend/components/export.cljs
  src/main/frontend/components/export.css
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/utils.js
  tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx
  tldraw/apps/tldraw-logseq/src/components/Button/CircleButton.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/components/PrimaryTools/PrimaryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/StatusBar/StatusBar.tsx
  tldraw/apps/tldraw-logseq/src/lib/logseq-context.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/LogseqPortalShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/YouTubeShape.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/constants.ts
  tldraw/packages/react/src/components/Canvas/Canvas.tsx
  tldraw/packages/react/src/components/ContextBarContainer/ContextBarContainer.tsx
  tldraw/packages/react/src/components/Indicator/Indicator.tsx
  tldraw/packages/react/src/components/QuickLinksContainer/QuickLinksContainer.tsx
  tldraw/packages/react/src/components/SelectionDetailContainer/SelectionDetailContainer.tsx
  tldraw/packages/react/src/components/Shape/Shape.tsx
  tldraw/packages/react/src/components/ui/DirectionIndicator/DirectionIndicator.tsx
  tldraw/packages/react/src/components/ui/Grid/Grid.tsx
  tldraw/packages/react/src/components/ui/SelectionBackground/SelectionBackground.tsx
Labels: :type/feature

#8787 Enhance: plugin-related improvements
  bb.edn
  libs/CHANGELOG.md
  libs/package.json
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  public/index.html
  resources/electron.html
  resources/index.html
  resources/js/lsplugin.core.js
  src/electron/electron/plugin.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/plugins_settings.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/file_sync.cljs
  src/main/frontend/handler/notification.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/handler/plugin_config.cljs
  src/main/frontend/handler/shell.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
  src/main/logseq/api.cljs
  src/main/logseq/sdk/assets.cljs
  src/main/logseq/sdk/core.cljs
  src/main/logseq/sdk/debug.cljs
  src/main/logseq/sdk/git.cljs
  src/main/logseq/sdk/ui.cljs
  src/main/logseq/sdk/utils.cljs
Labels: :type/enhancement

#9085 fix(ui): breadcrumb fragments overflow in query results container
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
Labels: :type/bug-fix

#9084 fix: scheduled and deadline
  src/main/frontend/db/model.cljs
Labels: :type/bug-fix

#9118 fix(ui): incorrect position of mobile bar
  src/main/frontend/mobile/index.css
Labels: :type/bug-fix

#9119 fix: query searching for two or more properties is extremely slow
  deps/db/src/logseq/db/rules.cljc
Labels: :type/bug-fix

#9117 fix: insert properties will truncate other properties if there's any empty property
  deps/graph-parser/src/logseq/graph_parser/text.cljs
  src/main/frontend/util/property.cljs
  src/test/frontend/handler/repo_conversion_test.cljs
  src/test/frontend/util/property_test.cljs
Labels: :type/bug-fix

#9164 fix(editor): wrong xml prettify implementation
  src/main/frontend/utils.js
Labels: :type/bug-fix

#9154 fix: mobile app crashes while trying to swipe the block that has any collapsed block
  src/main/frontend/mobile/action_bar.cljs
Labels: :type/bug-fix

#9122 fix(fs): image renaming op when resizing pdf hl area
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/fs.cljs
Labels: :type/bug-fix

#9184 Chore: Add test to prevent regression on property query
  deps/db/src/logseq/db/rules.cljc
  src/test/frontend/db/query_dsl_test.cljs
Labels: :type/dev

#9192 Feat (Whiteboards): Shape conversion
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
  tldraw/apps/tldraw-logseq/src/components/GeometryTools/GeometryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/PrimaryTools/PrimaryTools.tsx
  tldraw/apps/tldraw-logseq/src/components/ToolButton/ToolButton.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/lib/TLApi/TLApi.ts
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/types/types.ts
Labels: :type/feature

#9139 fix: lazy loading shakes
  src/main/frontend/components/block.cljs
  src/main/frontend/components/journal.cljs
  src/main/frontend/components/query.cljs
  src/main/frontend/components/scheduled_deadlines.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/db_mixins.cljs
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#9141 Feat: ordered(number) list blocks
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  src/main/frontend/commands.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/content.cljs
  src/main/frontend/handler/block.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/events.cljs
Labels: :type/feature

#9231 enhance(api): restore editing cursor state only for the input element in viewport
  src/main/frontend/util.cljc
  src/main/frontend/utils.js
  src/main/logseq/api.cljs
Labels: :type/enhancement

#9233 Fix: no collapse control on collapsed query block for mobile
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#9215 chore(release): bump version 0.9.4
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#9229 Enhance: Add :remove-block-children? query option for advanced queries and an advanced query :template fix
  src/main/frontend/components/query/result.cljs
  src/main/frontend/components/query_table.cljs
  src/test/frontend/components/query/result_test.cljs
Labels: :type/enhancement

#9236 Fix: Search in page position
  src/main/frontend/components/container.cljs
  src/main/frontend/components/find_in_page.cljs
Labels: :type/bug-fix

#9222 enhance(ux): keep the item position from the installed plugins list when toggling enable/disable button
  src/main/frontend/components/plugins.cljs
Labels: :type/enhancement

#9247 fix: Improve error handling in `mkdir` function
  src/main/frontend/fs.cljs
  src/main/frontend/fs/node.cljs
Labels: fix

#9259 Fix (Whiteboards): Page name sanitization
  src/main/frontend/handler/whiteboard.cljs
Labels: :type/bug-fix

#9255 fix(editor): copy page url with shortcut
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/bug-fix
