Repository logseq/logseq, pull requests merged in 2023-09, with the labels that each got.

#10134 Enhance(sync): serveral enhancements in sync
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/file_sync.cljs
  src/main/frontend/handler/user.cljs
Labels: :type/enhancement

#10141 enhance(fs): check graph folder for bad name and nested graph
  deps/common/src/logseq/common/path.cljs
  src/main/frontend/handler/web/nfs.cljs
Labels: :type/enhancement

#10147 enhance(sync): refine network checking
  src/main/frontend/components/plugins.cljs
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#10049 Enhance (UX): Electron loading
  src/electron/electron/handler.cljs
  src/electron/electron/window.cljs
  src/main/frontend/components/theme.cljs
Labels: :type/enhancement

#10127 Enhance/plugins apis
  libs/src/LSPlugin.ts
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/route.cljs
  src/main/logseq/api.cljs
Labels: :type/enhancement

#10145 Fix: Close button visibility
  src/main/frontend/components/container.css
Labels: :type/bug-fix

#10163 fix(sync): missing cross-origin handling for conn check
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#10167 chore: add timestamp to log
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#10201 Enhance (UX): Electron loading (fixed)
  src/electron/electron/handler.cljs
  src/electron/electron/window.cljs
  src/main/frontend/components/theme.cljs
Labels: :type/enhancement

#9930 youtube.cljs: allow for single-digit minutes and seconds in youtube-timestamp (addresses #9920)
  src/main/frontend/extensions/video/youtube.cljs
Labels: looking-for-review

#10209 chore(electron): use logger instead of console.log
  src/electron/electron/configs.cljs
  src/electron/electron/handler.cljs
Labels: :type/dev

#10190 Enhance: Introduce customizable close window shortcut
  src/main/frontend/components/window_controls.cljs
  src/main/frontend/handler/whiteboard.cljs
  src/main/frontend/handler/window.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/resources/dicts/en.edn
Labels: :type/enhancement

#10175 fix(plugin): incorrect mouse point payload for the plugin hook of the editor input selection
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#10191 fix(fs): support asset filenames with percent encoding
  resources/js/preload.js
Labels: :type/bug-fix

#10223 enhance(electron): close notification message when test proxy setting
  src/main/frontend/components/plugins.cljs
Labels: :type/enhancement

#10224 fix: fix backslash characters unable to be keybound in #10218 with rewrite-edn update
  deps.edn
Labels: :type/dev

#10232 fix(mobile): incorrect asset resource path for custom css
  src/main/frontend/config.cljs
Labels: :type/bug-fix

#10253 fix(fs): disable graph name warning
  src/main/frontend/handler/web/nfs.cljs
Labels: :type/bug-fix

#10242 chore: bump version 0.9.18
  android/app/build.gradle
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#9822 chore(deps): bump CodeMirror from 5.58.1 to 5.65.15
  package.json
  yarn.lock
Labels: chore

#10292 fix(editor): drag and drop to dummy page
  src/main/frontend/components/page.cljs
  src/main/frontend/handler/dnd.cljs
Labels: :type/bug-fix

#10222 Feat (Whiteboards): Pen mode (palm rejection)
  src/main/frontend/components/container.css
  src/main/frontend/components/whiteboard.css
  src/resources/dicts/en.edn
  tldraw/apps/tldraw-logseq/src/components/ActionBar/ActionBar.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/lib/TLApi/TLApi.ts
  tldraw/packages/core/src/lib/TLSettings.ts
  tldraw/packages/react/src/components/AppCanvas.tsx
  tldraw/packages/react/src/components/Canvas/Canvas.tsx
  tldraw/packages/react/src/hooks/useCanvasEvents.ts
  tldraw/packages/react/src/hooks/useShapeEvents.ts
Labels: :type/feature

#10298 fix(ui): incorrect auto-complete modal position for overflow editor content input
  src/main/frontend/components/editor.cljs
Labels: :type/bug-fix
