Repository logseq/logseq, pull requests merged in 2023-03, with the labels that each got.

#8727 chore(release): bump version 0.8.18
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#8731 fix(rsapi): use system certs
  resources/package.json
  static/yarn.lock
Labels: :type/bug-fix

#8636 fix (Whiteboard): Paste shape
  e2e-tests/headings.spec.ts
  e2e-tests/utils.ts
  e2e-tests/whiteboards.spec.ts
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
Labels: :type/bug-fix

#8741 fix(electron): global config dir name under windows
  src/electron/electron/utils.cljs
Labels: fix

#8736 Fix: Plugins menu item not opening from plugins dashboard
  src/main/frontend/handler/plugin_config.cljs
Labels: :type/bug-fix

#8752 fix: shrink on-click range of sidebar-item
  src/main/frontend/components/right_sidebar.cljs
Labels: :type/bug-fix

#8747 Fix (Whiteboards): Autocomplete on portals
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/react/src/components/ui/SelectionForeground/SelectionForeground.tsx
Labels: :type/bug-fix

#8720 Chore: Add deprecation for :editor/command-trigger config
  resources/css/common.css
  src/main/frontend/handler/common/config_edn.cljs
  src/main/frontend/handler/file.cljs
  src/main/frontend/ui.cljs
  src/test/frontend/handler/common/config_edn_test.cljs
Labels: :type/dev

#8753 Enhance (Whiteboards): Paste and dnd behavior (also add a placeholder to shape labels)
  src/main/frontend/components/block.cljs
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/LineShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/text/TextLabel.tsx
  tldraw/packages/core/src/lib/TLPage/TLPage.ts
Labels: :type/enhancement

#8773 fix: display page's original name when possible
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#8778 fix(test): e2e fail due to page search
  e2e-tests/page-search.spec.ts
Labels: fix

#8772 enhance(pdf): UI lag for the case of large highlights data
  deps.edn
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/pdf/core.cljs
Labels: :type/enhancement

#8808 enhance(ux): optimize active state of the auto-complete component for mouse interaction
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
Labels: :type/enhancement

#8813 enhance(i18n): Update Korean translation
  src/main/frontend/dicts.cljc
  src/main/frontend/modules/shortcut/dicts.cljc
Labels: help-wanted

#8839 Add option to handle default block refs expanding behaviour
  src/main/frontend/components/block.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/handler/config.cljs
  src/main/frontend/schema/handler/common_config.cljc
  src/main/frontend/state.cljs
  templates/config.edn
Labels: fix

#8842 fix(editor): wrong cookie render
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#8826 fix(ui): incorrect position of absolute modal on some mobile platforms
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/editor.css
Labels: :type/bug-fix

#8829 enhance: add mldoc ast schema
  bb.edn
  deps/graph-parser/.carve/ignore
  deps/graph-parser/src/logseq/graph_parser/mldoc.cljc
  deps/graph-parser/src/logseq/graph_parser/schema/mldoc.cljc
  scripts/src/logseq/tasks/malli.clj
  src/main/frontend/handler/export/common.cljs
  src/main/frontend/handler/export/text.cljs
Labels: :type/enhancement

#8797 Enhance (Whiteboards): UX
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/components/block.cljs
  tldraw/apps/tldraw-logseq/src/components/AppUI.tsx
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
  tldraw/apps/tldraw-logseq/src/components/Devtools/Devtools.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/BoxShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/LineShape.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/BrushingState.ts
  tldraw/packages/core/src/utils/index.ts
  tldraw/packages/react/src/hooks/useZoom.ts
Labels: :type/enhancement

#8774 feat: simple query builder
  .clj-kondo/config.edn
  deps/db/src/logseq/db/default.cljs
  deps/db/src/logseq/db/schema.cljs
  deps/graph-parser/src/logseq/graph_parser/util.cljs
  resources/css/common.css
  scripts/src/logseq/tasks/lang.clj
  src/main/frontend/commands.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/datetime.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins_settings.cljs
  src/main/frontend/components/query/builder.cljs
  src/main/frontend/components/query/builder.css
  src/main/frontend/components/query_table.cljs
  src/main/frontend/components/select.cljs
  src/main/frontend/components/svg.cljs
  src/main/frontend/components/theme.css
  src/main/frontend/db/model.cljs
  src/main/frontend/db/query_dsl.cljs
  src/main/frontend/db/query_react.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/extensions/video/youtube.cljs
  src/main/frontend/handler/command_palette.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/query/builder.cljs
  src/main/frontend/handler/ui.cljs
  src/main/frontend/modules/shortcut/core.cljs
  src/main/frontend/search.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
  src/main/frontend/util.cljc
  src/test/frontend/db/query_dsl_test.cljs
  src/test/frontend/handler/query/builder_test.cljs
Labels: :type/feature

#8833 fix: undo block deletion needs multiple steps
  src/main/frontend/handler/editor.cljs
  src/main/frontend/modules/editor/undo_redo.cljs
  src/main/frontend/modules/outliner/datascript.cljc
  src/main/frontend/modules/outliner/transaction.cljc
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#8855 fix: shape index
  src/main/frontend/handler/whiteboard.cljs
Labels: :type/bug-fix

#8853 Release whiteboard to everyone
  e2e-tests/page-search.spec.ts
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/sidebar.cljs
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/user.cljs
  src/main/frontend/handler/whiteboard.cljs
  src/main/frontend/state.cljs
Labels: :type/dev

#8864 fix: undo cycle todos
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#8872 fix(editor): avoid nav to block with empty uuid
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#8885 Fix (Whiteboards): Shape index and arrow binding issue
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/components/whiteboard.css
  src/main/frontend/handler/whiteboard.cljs
  tldraw/packages/core/src/lib/TLHistory.ts
  tldraw/packages/core/src/lib/TLPage/TLPage.ts
Labels: :type/bug-fix

#8876 enhance(ux): audio and video player render after upload asset command
  src/main/frontend/config.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util.cljc
  src/test/frontend/util_test.cljs
Labels: :type/enhancement

#8874 fix: multiple windows clash
  src/main/electron/listener.cljs
  src/main/frontend/handler/ui.cljs
Labels: :type/bug-fix

#8893 Fix (Whiteboards): An attempt to fix most of the remaining issues
  src/main/frontend/components/block.cljs
  src/main/frontend/handler/whiteboard.cljs
  src/main/frontend/state.cljs
  tldraw/apps/tldraw-logseq/src/lib/preview-manager.tsx
  tldraw/apps/tldraw-logseq/src/styles.css
Labels: :type/bug-fix

#8878 enhance(sync): replace <get-remote-graph by <get-remote-txid
  src/main/frontend/fs/sync.cljs
Labels: :type/enhancement

#8865 Feat: The new login UI
  packages/amplify/.gitignore
  packages/amplify/examples/index.html
  packages/amplify/examples/index.tsx
  packages/amplify/package.json
  packages/amplify/src/LSAuthenticator.tsx
  packages/amplify/src/amplify.ts
  packages/amplify/yarn.lock
  public/index.html
  resources/css/amplify.css
  resources/electron.html
  resources/index.html
  resources/js/amplify.js
  src/electron/electron/url.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/user/config.js
  src/main/frontend/components/user/login.cljs
  src/main/frontend/components/user/login.css
  src/main/frontend/config.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/user.cljs
  src/main/frontend/mobile/deeplink.cljs
  src/main/frontend/routes.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
  tailwind.all.css
Labels: :type/feature

#8909 fix: broken simple queries
  src/main/frontend/components/query/builder.cljs
  src/main/frontend/components/query/builder.css
  src/main/frontend/template.cljs
Labels: :type/bug-fix

#8914 chore(release): bump version 0.9.0
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#8917 fix(ui): incorrect login entry from the settings pane
  src/main/frontend/components/settings.cljs
Labels: :type/bug-fix

#8931 fix(fs): open dir with default app
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/util/page.cljs
Labels: :type/bug-fix

#8936 Fix: Pasting a file when file pasting is preferred
  src/main/frontend/handler/paste.cljs
  src/test/frontend/handler/paste_test.cljs
Labels: :type/bug-fix

#8949 chore: release 0.9.1
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#8954 Fix: Bring back result count for built-in queries
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#8962 Enhance(UI): dynamic layout of the plugin UI items from the app toolbar
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/handler/ui.cljs
Labels: :type/enhancement

#8963 fix(sync): add missing sync event schema
  src/main/frontend/pubsub.cljc
Labels: :type/bug-fix

#8965 fix(config): allow optional key, fix #8964
  src/main/frontend/schema/handler/common_config.cljc
Labels: :type/bug-fix

#8984 fix(plugin): incorrect instance of the plugin ui items list wrap
  src/main/frontend/components/plugins.cljs
Labels: :type/bug-fix
