Repository logseq/logseq, pull requests merged in 2023-08, with the labels that each got.

#9964 chore(release): release 0.9.12
  android/app/build.gradle
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#9967 Fix/markdown heading export
  src/main/frontend/modules/file/core.cljs
Labels: :type/bug-fix

#9969 fix(editor): display of embedded drawing
  src/main/frontend/extensions/excalidraw.cljs
Labels: :type/bug-fix

#9982 fix(pdf): highlights text layer is overlaid by the pdfjs built-in annotation layer
  src/main/frontend/extensions/pdf/pdf.css
Labels: :type/bug-fix

#10002 enhance(pdf): support `shift + enter` to pick the previous searching results highlight
  src/main/frontend/extensions/pdf/toolbar.cljs
Labels: :type/enhancement

#10024 Enhance: Tweak login wording to let users know that email login works
  packages/amplify/src/LSAuthenticator.tsx
  packages/amplify/src/amplify.ts
Labels: :type/enhancement

#10023 fix(editor): avoid nav to empty page name
  src/main/frontend/handler/route.cljs
Labels: :type/bug-fix

#10011 enhance(zotero): polish UI details of the zotero search component
  src/main/frontend/components/svg.cljs
  src/main/frontend/extensions/zotero.cljs
  src/main/frontend/extensions/zotero.css
  src/main/frontend/ui.cljs
Labels: :type/enhancement

#9989 fix: add drag threshold for graph view
  src/main/frontend/components/page.cljs
Labels: :type/bug-fix

#10016 DB version: browser sharedworker support
  deps/persist-db/package.json
  deps/persist-db/src/index.js
  deps/persist-db/webpack.config.js
  deps/persist-db/yarn.lock
  package.json
  resources/js/ls-wa-sqlite/d5348c86bcd3913f2696.wasm
  resources/js/ls-wa-sqlite/persist-db-worker.js
  resources/js/ls-wa-sqlite/persist-db-worker.js.LICENSE.txt
  resources/js/ls-wa-sqlite/persist-db-worker.js.map
  src/main/frontend/config.cljs
  src/main/frontend/db/restore.cljs
  src/main/frontend/db/rtc/op.cljs
  src/main/frontend/fs/nfs.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/modules/outliner/pipeline.cljs
  src/main/frontend/persist_db.cljs
  src/main/frontend/persist_db/README.md
  src/main/frontend/persist_db/browser.cljs
  src/main/frontend/persist_db/node.cljs
  src/main/frontend/persist_db/protocol.cljs
  yarn.lock
Labels: :type/feature

#9972 fix(editor): template expansion if auto-completion ui is blurred
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#10032 Fix (UX): Sub-pixel anti-aliasing
  src/electron/electron/window.cljs
Labels: :type/bug-fix

#10036 Fix: Clicking on recently opened whiteboards
  src/main/frontend/components/container.cljs
  src/main/frontend/handler/route.cljs
Labels: :type/bug-fix

#10026 Chore: release 0.9.14
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10034 enhance(pdf): pdf password support
  src/main/frontend/extensions/pdf/core.cljs
Labels: :type/enhancement

#10071 Fix: Disable sidebar pane content scrolling
  src/main/frontend/components/container.css
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/right_sidebar.css
Labels: :type/bug-fix

#10022 Enhance/plugin APIs x
  src/main/frontend/components/block.cljs
  src/main/frontend/components/query_table.cljs
  src/main/logseq/api/block.cljs
Labels: :type/enhancement

#10078 chore(release): bump version 0.9.15
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10084 fix(pdf): incorrect path of pdfjs cmaps resources
  src/main/frontend/extensions/pdf/core.cljs
Labels: :type/bug-fix

#10092 Fix (PDF): Copy keyboard shortcut
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#10097 fix(ios): crash caused by capacitor saved call
  package.json
  yarn.lock
Labels: :type/bug-fix

#10099 chore (deps): Update static yarn.lock
  static/yarn.lock
Labels: dependencies

#10096 Enhance: Disable close window shortcut
  src/electron/electron/core.cljs
Labels: :type/enhancement

#10116 Fix (draw): Focus container on click
  src/main/frontend/extensions/excalidraw.cljs
Labels: :type/bug-fix

#9803 Enhance/shortcuts
  libs/src/LSPlugin.caller.ts
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  libs/src/helpers.ts
  libs/src/modules/LSPlugin.Experiments.ts
  libs/src/modules/LSPlugin.Request.ts
  libs/src/modules/LSPlugin.Search.ts
  libs/src/modules/LSPlugin.Storage.ts
  libs/src/postmate/index.ts
  resources/js/lsplugin.core.js
  src/main/frontend/components/command_palette.cljs
  src/main/frontend/components/plugins.css
  src/main/frontend/components/plugins_settings.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/components/shortcut.cljs
  src/main/frontend/components/shortcut.css
  src/main/frontend/components/shortcut2.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/extensions/pdf/core.cljs
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/handler/command_palette.cljs
  src/main/frontend/handler/config.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/global_config.cljs
  src/main/frontend/handler/notification.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/mixins.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/core.cljs
  src/main/frontend/modules/shortcut/data_helper.cljs
  src/main/frontend/modules/shortcut/utils.cljs
  src/main/frontend/routes.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/ui/date_picker.cljs
  src/main/frontend/util.cljc
  src/main/logseq/api.cljs
  src/resources/dicts/en.edn
  src/resources/dicts/zh-cn.edn
  src/test/frontend/modules/shortcut/core_test.cljs
  src/test/frontend/util_test.cljs
Labels: :type/enhancement

#9638 fix(ux): make linked references filters reactive when the page properties changed
  src/main/frontend/components/reference.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#10111 fix(bug): #4447
  libs/package.json
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.user.ts
  libs/src/helpers.ts
  libs/yarn.lock
Labels: fix

#10113 fix: input-selection-end is not firing correctly
  src/main/frontend/ui.cljs
Labels: fix

#10121 fix (pdf): Scroll to ref on dark theme
  src/main/frontend/extensions/pdf/pdf.css
Labels: :type/bug-fix

#10112 enhance(sync): add connectivity-testing
  src/main/frontend/config.cljs
  src/main/frontend/fs/sync.cljs
  src/resources/dicts/en.edn
  src/resources/dicts/zh-cn.edn
Labels: :type/enhancement
