Repository logseq/logseq, pull requests merged in 2023-10, with the labels that each got.

#10329 fix(apis): incorrect api call for the electron production bundle
  externs.js
  src/electron/electron/utils.js
Labels: :type/bug-fix

#10325 Fix: Close window while editing
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/bug-fix

#10333 fix(pdf): missing the initial ref highlight block sometimes
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/pdf/core.cljs
Labels: :type/bug-fix

#10336 fix: the first window not closing when there're multiple windows
  src/electron/electron/core.cljs
  src/electron/electron/window.cljs
Labels: :type/bug-fix

#10286 fix(electron): bypass corrupted sqlite search index
  src/electron/electron/search.cljs
Labels: :type/bug-fix

#10290 Enhance / shortcuts
  src/main/frontend/components/shortcut2.cljs
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/enhancement

#10356 chore: bump ios version for tf release
  ios/App/App.xcodeproj/project.pbxproj
Labels: :type/dev

#10380 enhance(ux): disable keymap settings for the mobile
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/settings.css
Labels: :type/enhancement

#10389 ci: deploy web app when release
  .github/workflows/build-stage.yml
Labels: :type/dev

#10390 feat(pdf): add toggle option for the feature of auto opening the highlight context menu from new text selection
  src/main/frontend/extensions/pdf/core.cljs
  src/main/frontend/extensions/pdf/pdf.css
  src/main/frontend/extensions/pdf/toolbar.cljs
  src/main/frontend/state.cljs
  src/resources/dicts/en.edn
  src/resources/dicts/ja.edn
  src/resources/dicts/ko.edn
  src/resources/dicts/zh-cn.edn
  src/resources/dicts/zh-hant.edn
Labels: :type/enhancement

#10387 fix: issue-9380 - #card should only be appended to the title
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/util/block_content.cljs
  src/main/frontend/util/property.cljs
Labels: fix

#10414 chore(deps): upgrade electron v26
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/dev

#8524 Feat: the new handbooks
  resources/js/glide/glide.core.min.css
  resources/js/glide/glide.min.js
  resources/js/glide/glide.theme.min.css
  src/electron/electron/url.cljs
  src/main/electron/listener.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/container.cljs
  src/main/frontend/components/container.css
  src/main/frontend/components/handbooks.cljs
  src/main/frontend/components/onboarding/index.css
  src/main/frontend/extensions/handbooks/core.cljs
  src/main/frontend/extensions/handbooks/handbooks.css
  src/main/frontend/extensions/video/youtube.cljs
  src/main/frontend/handler/ui.cljs
  src/main/frontend/modules/layout/core.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
  src/main/frontend/util.cljc
  src/resources/dicts/en.edn
Labels: :type/feature

#10422 fix: wrong date fn usage in #10350
  src/main/frontend/date.cljs
  src/main/frontend/modules/file/core.cljs
Labels: :type/bug-fix

#10440 fix(linux): downgrade electron to v25
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/bug-fix

#10441 chore(deps): update rsapi
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/dev

#10435 feat(pdf): add zoom via touchpad
  src/main/frontend/extensions/pdf/core.cljs
Labels: feature

#10434 fix(journal): handle non standard journal name page-ref
  src/main/frontend/components/block.cljs
  src/main/frontend/components/search.cljs
Labels: :type/bug-fix

#10428 enhance(sync): make smart merge the default option
  src/main/frontend/state.cljs
Labels: :type/enhancement
