Repository logseq/logseq, pull requests merged in 2023-06, with the labels that each got.

#9550 Fix: Remove deprecated :editor/command-trigger option [minor change]
  src/main/frontend/commands.cljs
  src/main/frontend/handler/common/config_edn.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/state.cljs
  src/test/frontend/handler/common/config_edn_test.cljs
Labels: :type/bug-fix

#9572 chore: Update bug_report.yaml to reassure our policy on questions
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: :type/dev, chore

#9557 dev(e2e): add tests for selecting codeblock language
  e2e-tests/code-editing.spec.ts
Labels: :type/hold, :type/feature

#9589 fix(ios): watcher rel path handling
  ios/App/App/FsWatcher.swift
Labels: :type/bug-fix

#9576 chore: remove false positive translations a.k.a. EN definitions in non EN dicts
  bb.edn
  docs/contributing-to-translations.md
  scripts/src/logseq/tasks/lang.clj
  src/resources/dicts/af.edn
  src/resources/dicts/de.edn
  src/resources/dicts/en.edn
  src/resources/dicts/es.edn
  src/resources/dicts/fr.edn
  src/resources/dicts/it.edn
  src/resources/dicts/ja.edn
  src/resources/dicts/ko.edn
  src/resources/dicts/nb-no.edn
  src/resources/dicts/nl.edn
  src/resources/dicts/pl.edn
  src/resources/dicts/pt-br.edn
  src/resources/dicts/pt-pt.edn
  src/resources/dicts/ru.edn
  src/resources/dicts/tr.edn
  src/resources/dicts/zh-cn.edn
  src/resources/dicts/zh-hant.edn
Labels: chore

#9587 Fix: shift clicking on "Pages tagged with" page link doesn't open in sidebar
  src/main/frontend/components/page.cljs
Labels: looking-for-review, fix

#9596 Fix (Whiteboards): Exporting from context menu
  tldraw/apps/tldraw-logseq/src/components/ContextMenu/ContextMenu.tsx
Labels: :type/bug-fix

#9600 Fix: Alias pages not included in published subgraph
  deps/publishing/src/logseq/publishing/db.cljs
  deps/publishing/test/logseq/publishing/db_test.cljs
Labels: :type/bug-fix

#9494 enhance: Improve UK (Ukrainian) translation
  src/resources/dicts/uk.edn
Labels: :type/hold

#9430 enhance(ux): keymap manager for plugins
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/components/shortcut.cljs
  src/main/frontend/components/shortcut.css
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/core.cljs
  src/main/frontend/modules/shortcut/data_helper.cljs
  src/main/frontend/routes.cljs
  src/main/frontend/ui.css
  src/main/frontend/util.cljc
  src/main/logseq/api.cljs
  src/resources/dicts/en.edn
  tailwind.config.js
Labels: :type/enhancement

#9637 chore(release): bump version 0.9.9
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#9625 chore: update KaTeX from 0.13.18 to 0.16.7
  resources/css/katex.min.css
  resources/js/katex.min.js
Labels: looking-for-review

#9610 Chore (i18n): Make punctuation usage consistent in translations
  docs/contributing-to-translations.md
  docs/dev-practices.md
  e2e-tests/util/search-modal.ts
  e2e-tests/whiteboards.spec.ts
  src/main/electron/listener.cljs
  src/main/frontend/components/assets.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/container.cljs
  src/main/frontend/components/conversion.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/file.cljs
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/search.cljs
  src/main/frontend/extensions/excalidraw.cljs
  src/main/frontend/extensions/latex.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/ui.cljs
  src/resources/dicts/af.edn
  src/resources/dicts/de.edn
  src/resources/dicts/en.edn
  src/resources/dicts/es.edn
  src/resources/dicts/fr.edn
  src/resources/dicts/it.edn
  src/resources/dicts/ja.edn
  src/resources/dicts/ko.edn
  src/resources/dicts/nb-no.edn
  src/resources/dicts/nl.edn
  src/resources/dicts/pl.edn
  src/resources/dicts/pt-br.edn
  src/resources/dicts/pt-pt.edn
  src/resources/dicts/ru.edn
  src/resources/dicts/sk.edn
  src/resources/dicts/tr.edn
  src/resources/dicts/uk.edn
  src/resources/dicts/zh-cn.edn
  src/resources/dicts/zh-hant.edn
Labels: :type/dev

#9595 fix(editor): incorrect behavior for the code editor of file page
  src/main/frontend/handler/code.cljs
Labels: :type/bug-fix

#9590 Enhance(UX): polish details for the plugin fenced code block
  src/main/frontend/components/block.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins.css
Labels: :type/enhancement

#9671 enhance: pub-event! returns a promise
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/state.cljs
Labels: :type/enhancement

#9661 Fix: Hidden editable block properties showing up when user properties present
  src/main/frontend/components/block.cljs
  src/main/frontend/util/property.cljs
  src/test/frontend/util/property_test.cljs
Labels: :type/bug-fix

#9554 Fix: trim block whitespace for markdown files for a specific case
  deps/graph-parser/src/logseq/graph_parser/mldoc.cljc
  deps/graph-parser/test/logseq/graph_parser/mldoc_test.cljs
Labels: :type/bug-fix

#9657 fix: clicking to edit a block from the right sidebar or a whiteboard can't jump to the correct position
  src/main/frontend/components/block.css
  tldraw/apps/tldraw-logseq/src/styles.css
Labels: :type/bug-fix

#9609 Enhance(UX): marketplace
  src/electron/electron/plugin.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/ui.css
  src/resources/dicts/en.edn
  src/resources/dicts/zh-cn.edn
Labels: :type/enhancement

#9520 enhance: IAppProxy, IEditorProxy, BlockEntity and PageEntity have strict interfaces
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
Labels: plugins, looking-for-review

#9701 enhance(plugin): support right sidebar item type as string
  src/main/frontend/components/right_sidebar.cljs
Labels: :type/enhancement

#9699 fix: test intermediate failure
  e2e-tests/code-editing.spec.ts
Labels: :type/feature

#9553 feat: add slash command for the code block
  e2e-tests/code-editing.spec.ts
  src/main/frontend/commands.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/editor.css
Labels: :type/feature

#9717 Fix (Whiteboards): Skip snapping to preserve aspect ratio
  tldraw/packages/core/src/lib/tools/TLBoxTool/states/CreatingState.tsx
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/ResizingState.ts
Labels: :type/bug-fix

#9739 fix: disable hiccup export for heading/footer/etc when paste
  src/main/frontend/extensions/html_parser.cljs
  src/main/frontend/handler/paste.cljs
Labels: :type/bug-fix

#9746 fix(sync): code start base of diff-merge
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#9742 chore(release): bump version 0.9.10
  android/app/build.gradle
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#9751 fix(test): page search fail of e2e
  e2e-tests/util/search-modal.ts
Labels: :type/bug-fix

#9769 chore(deps): update capacitor-diff-merge; fix initial dir create
  ios/App/App.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: :type/dev
