Repository logseq/logseq, pull requests merged in 2023-02, with the labels that each got.

#8475 fix: assets url wrong path
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#8486 Update rsapi, allowing ignore certs
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/dev

#8482 Fix: Page blocks not displaying full property values in query tables
  deps/graph-parser/src/logseq/graph_parser/extract.cljc
  deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
  deps/graph-parser/test/logseq/graph_parser_test.cljs
  src/test/frontend/handler/repo_conversion_test.cljs
Labels: :type/bug-fix

#8495 Enhancement: File and page commands work in more contexts and warn when they don't work
  .clj-kondo/config.edn
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/handler/common/developer.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/util/page.cljs
Labels: :type/enhancement

#8504 fix(sync): revert age upgrade
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/bug-fix

#8508 fix(i18n): wrong translation key for file content
  src/main/frontend/dicts.cljc
Labels: :type/bug-fix

#8515 enhance(sync): add native logging for desktop and android
  package.json
  resources/package.json
  src/electron/electron/file_sync_rsapi.cljs
  static/yarn.lock
  yarn.lock
Labels: :type/dev

#8263 fix(query): cache special value as resolved value
  e2e-tests/fixtures.ts
  src/main/frontend/db/query_react.cljs
  src/test/frontend/db/query_react_test.cljs
Labels: query, :type/bug-fix, looking-for-review, fix

#8300 feat: support Media Fragment URIs with audio
  deps/graph-parser/src/logseq/graph_parser/util.cljs
  deps/graph-parser/test/logseq/graph_parser/util_test.cljs
  src/main/frontend/components/block.cljs
Labels: :type/feature

#8327 Fix: Auto heading on markdown mode
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  src/main/frontend/components/content.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix, looking-for-review

#8541 Chore: Add heading tests
  e2e-tests/headings.spec.ts
Labels: :type/dev

#8548 fix(plugin): remove plugin settings entry when plugin disabled
  src/main/frontend/handler/plugin.cljs
Labels: :type/bug-fix

#8552 Fix: Access to features
  src/main/frontend/handler/user.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#8559 fix(mobile): timestamp submenu of toolbar
  src/main/frontend/mobile/index.css
  src/main/frontend/mobile/mobile_bar.cljs
Labels: :type/bug-fix

#8554 chore: bump version 0.8.17
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#8562 fix(mobile): do not use newer regex flags
  src/main/frontend/mobile/intent.cljs
Labels: :type/bug-fix

#8546 Fix: Command completion triggering too often
  src/main/frontend/handler/editor.cljs
  src/test/frontend/handler/editor_test.cljs
Labels: :type/bug-fix

#8578 fix: don't store broken config in DB
  src/main/frontend/components/file.cljs
  src/main/frontend/handler/file.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#8589 fix(pdf): remove prefix(`@`) checking for links of org mode page
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#8573 Fix: Display error when unexpected invalid repo config.edn occurs
  src/main/frontend/handler/repo_config.cljs
Labels: :type/bug-fix

#8222 docs: Add contributing guidelines
  CONTRIBUTING.md
Labels: :type/dev

#8603 fix (Whiteboards): Toggle collapsed button action
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
Labels: :type/bug-fix

#8588 docs: add repl setup to development document
  docs/develop-logseq.md
Labels: :type/docs

#8584 Feat: auto-completion for config editing
  resources/css/show-hint.css
  src/main/frontend/extensions/code.cljs
  src/main/frontend/schema/handler/common_config.cljc
  tailwind.all.css
Labels: :type/feature

#8618 Fix: shortcuts can be disabled with `false`
  src/main/frontend/schema/handler/common_config.cljc
  templates/config.edn
Labels: :type/bug-fix

#8466 fix: electron menu handler(Redo, Undo, Copy)
  src/electron/electron/core.cljs
  src/main/electron/listener.cljs
Labels: fix

#8631 fix(http-server): bad logger stream for windows
  src/electron/electron/server.cljs
Labels: :type/bug-fix

#8632 fix(copy): cannot copy blank string
  src/electron/electron/context_menu.cljs
Labels: :type/bug-fix

#8639 Fix: git commit command not opening
  src/main/frontend/components/commit.cljs
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/bug-fix

#8630 fix(ui): marker layout of area highlight ref block content
  src/main/frontend/components/block.cljs
  src/main/frontend/extensions/pdf/pdf.css
Labels: :type/bug-fix

#8611 feat (Whiteboards): Auto pan canvas to pointer when out of view
  tldraw/packages/core/src/lib/TLViewport.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/BrushingState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/ResizingState.ts
  tldraw/packages/core/src/lib/tools/TLSelectTool/states/TranslatingState.ts
Labels: :type/feature, 🎨 :feat/whiteboard

#8616 Enhance/pdf enhancements
  src/electron/electron/core.cljs
  src/electron/electron/handler.cljs
  src/electron/electron/window.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/pdf/core.cljs
  src/main/frontend/extensions/pdf/pdf.css
  src/main/frontend/extensions/pdf/toolbar.cljs
  src/main/frontend/extensions/pdf/utils.cljs
  src/main/frontend/extensions/pdf/utils.js
  src/main/frontend/extensions/pdf/windows.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  src/main/frontend/utils.js
Labels: :type/enhancement

#8651 improve(apis): support CORS for http server
  resources/package.json
  src/electron/electron/server.cljs
  static/yarn.lock
Labels: :type/enhancement, http api

#8672 fix(android): disable image resize on android
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#8676 fix: disable macos sign temporarily
  .github/workflows/build-desktop-release.yml
  resources/forge.config.js
Labels: build, :type/bug-fix

#8657 fix: duplicate block ids in same file
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/test/logseq/graph_parser/block_test.cljs
Labels: :type/bug-fix

#8668 fix: duplicated block ids in multiple files
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/src/logseq/graph_parser/extract.cljc
  deps/graph-parser/test/logseq/graph_parser_test.cljs
  src/main/frontend/format/block.cljs
  src/main/frontend/handler/common/file.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/external.cljs
  src/main/frontend/handler/file.cljs
  src/main/frontend/handler/paste.cljs
  src/main/frontend/handler/repo.cljs
Labels: :type/bug-fix

#8642 enhance: paste from clipboard
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/paste.cljs
  src/test/frontend/handler/paste_test.cljs
Labels: :type/enhancement, looking-for-review

#8654 feat(srs): support cloze cues
  src/main/frontend/extensions/srs.cljs
Labels: feature

#8406 chore(dep): bump NodeJS from 16.x to 18.x LTS
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-ios.yml
  .github/workflows/build-stage.yml
  .github/workflows/build.yml
  .github/workflows/db.yml
  .github/workflows/e2e.yml
  .github/workflows/graph-parser.yml
  Dockerfile
  docs/develop-logseq-on-windows.md
  static/yarn.lock
  tldraw/apps/tldraw-logseq/package.json
  tldraw/package.json
  tldraw/packages/core/package.json
  tldraw/packages/react/package.json
  tldraw/yarn.lock
Labels: docker, build, :type/hold, :type/dev, security

#8420 chore(dep): bump Ubuntu image from 18.04 to 22.04
  .github/workflows/build-desktop-release.yml
Labels: :type/hold, :type/dev, ci, security

#8626 Fix: Edit global config.edn
  src/main/frontend/components/file.cljs
Labels: :type/bug-fix

#8683 ci: update actions and build deps
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
  .github/workflows/build-docker.yml
  .github/workflows/build-ios.yml
  .github/workflows/build-stage.yml
  .github/workflows/build.yml
  .github/workflows/db.yml
  .github/workflows/e2e.yml
  .github/workflows/graph-parser.yml
  docs/develop-logseq-on-windows.md
Labels: :type/dev

#8652 improve(ui): make the modals position friendly for the auto-complete component
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/editor.css
Labels: :type/enhancement

#7786 Fix pencil not working if drawing quickly (replace tldraw's undo/redo history with logseq's)
  src/main/frontend/db.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/handler/whiteboard.cljs
  src/main/frontend/modules/editor/undo_redo.cljs
  src/main/frontend/modules/outliner/datascript.cljc
  src/main/frontend/modules/outliner/file.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
  tldraw/apps/tldraw-logseq/src/app.tsx
  tldraw/packages/core/src/lib/TLApi/TLApi.ts
  tldraw/packages/core/src/lib/TLApp/TLApp.ts
  tldraw/packages/core/src/lib/TLHistory.ts
  tldraw/packages/core/src/lib/TLPage/TLPage.ts
  tldraw/packages/core/src/lib/tools/TLDrawTool/states/CreatingState.tsx
  tldraw/packages/react/src/hooks/useCanvasEvents.ts
  tldraw/packages/react/src/hooks/useSetup.ts
Labels: :type/feature

#8704 dev: add lsp config
  .gitignore
  .lsp/config.edn
Labels: :type/dev

#8568 Enhance: Add more translations, remove unused ones and add linter for unused
  .github/workflows/build.yml
  bb.edn
  docs/contributing-to-translations.md
  scripts/src/logseq/tasks/dev.clj
  scripts/src/logseq/tasks/lang.clj
  src/main/frontend/components/content.cljs
  src/main/frontend/components/export.cljs
  src/main/frontend/components/shortcut.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/extensions/excalidraw.cljs
  src/main/frontend/extensions/latex.cljs
  src/main/frontend/handler/route.cljs
  src/main/frontend/page.cljs
Labels: :type/enhancement, i18n

#8695 Enhance: Add support for block refs in properties to backlink to blocks
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/test/logseq/graph_parser/block_test.cljs
Labels: :type/enhancement

#8714 fix(plugin): force disable the unloaded(error) plugin
  libs/src/LSPlugin.core.ts
  resources/js/lsplugin.core.js
Labels: :type/bug-fix

#8715 ci: re-enable codesign on macos
  .github/workflows/build-desktop-release.yml
  resources/forge.config.js
Labels: :type/dev

#8160 docs: overhaul README structure
  README.md
Labels: :type/enhancement, looking-for-review
