Repository logseq/logseq, pull requests merged in 2023-12, with the labels that each got.

#10607 fix: slides don't work on published sites that aren't under '/'
  src/main/frontend/extensions/slide.cljs
Labels: :type/bug-fix

#10590 fix: cross-platform shotcuts
  deps/shui/src/logseq/shui/button/v2.cljs
  deps/shui/src/logseq/shui/shortcut/v1.cljs
  resources/css/shui.css
  src/main/frontend/components/cmdk.cljs
  src/main/frontend/components/shortcut.cljs
  src/main/frontend/modules/shortcut/data_helper.cljs
Labels: :type/bug-fix

#10638 fix(ui): theme color related issues
  src/main/frontend/colors.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/components/shortcut.cljs
Labels: :type/bug-fix

#10640 chore(release): release 0.10.1
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10654 fix(ui): incorrect IME composition detection
  src/main/frontend/components/cmdk.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util.cljc
Labels: :type/bug-fix

#10662 fix(cmdk): missing current-page search impl
  src/main/frontend/components/cmdk.cljs
Labels: :type/bug-fix

#10668 Add missing zh translations
  src/resources/dicts/zh-cn.edn
  src/resources/dicts/zh-hant.edn
Labels: fix

#10645 fix: add back full page content search
  src/main/frontend/components/cmdk.cljs
Labels: :type/bug-fix

#10674 fix(editor): incorrect handling of pasting html list
  src/main/frontend/handler/paste.cljs
Labels: :type/bug-fix

#10399 Enhance: plugin APIs
  libs/CHANGELOG.md
  libs/package.json
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  libs/src/helpers.ts
  resources/js/lsplugin.core.js
  resources/js/lsplugin.user.js
  resources/js/lsplugin.user.js.LICENSE.txt
  src/electron/electron/git.cljs
  src/main/electron/listener.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/handler/command_palette.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/core.cljs
  src/main/logseq/api.cljs
  src/main/logseq/sdk/assets.cljs
  src/main/logseq/sdk/ui.cljs
Labels: :type/enhancement

#10693 fix(UI): incorrect graph node edge color from the theme accent color
  src/main/frontend/colors.cljs
  src/main/frontend/components/settings.cljs
Labels: :type/bug-fix

#10689 chore(deps): upgrade electron v27
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/bug-fix

#10705 chore(deps): Update datascript to latest version before our fork
  deps.edn
  deps/db/deps.edn
  src/main/frontend/db/utils.cljs
Labels: :type/dev

#10710 fix: don's treat blocks with headings as pre blocks
  deps/graph-parser/src/logseq/graph_parser/block.cljs
Labels: :type/bug-fix

#10724 fix(pdf): set up initial listeners for the pdf viewer inside system window
  src/electron/electron/handler.cljs
  src/main/frontend/extensions/pdf/windows.cljs
Labels: :type/bug-fix

#10726 Save transactions to disk db to avoid data-loss
  deps/db/src/logseq/db/sqlite/db.cljs
  src/electron/electron/core.cljs
  src/electron/electron/db.cljs
  src/electron/electron/handler.cljs
  src/main/frontend/db_worker.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/persist_db.cljs
  src/main/frontend/persist_db/browser.cljs
Labels: :type/enhancement

#10739 fix(ci): provide fallback for build-stage action
  .github/workflows/build-stage.yml
Labels: :type/bug-fix

#10741 fix(api): safety key string for the simple command key value
  src/main/logseq/api.cljs
Labels: :type/bug-fix

#10751 fix: do not use asar
  resources/forge.config.js
  resources/package.json
  static/yarn.lock
Labels: :type/bug-fix

#10757 chore(release): bump version 0.10.3
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10764 fix(e2e): do not use css to test selection
  e2e-tests/basic.spec.ts
Labels: :type/bug-fix

#10767 fix(api): missing git sdk
  src/main/logseq/api.cljs
Labels: :type/bug-fix

#10765 Enhance(ui): left sidebar
  deps/shui/src/logseq/shui/demo.cljs
  e2e-tests/accessibility.spec.ts
  src/main/frontend/components/container.cljs
  src/main/frontend/components/container.css
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/right_sidebar.css
  src/main/frontend/extensions/pdf/pdf.css
Labels: :type/enhancement
