Repository logseq/logseq, pull requests merged in 2023-05, with the labels that each got.

#9269 Chore: Organize property related fns for the editor
  .clj-kondo/config.edn
  src/main/frontend/components/content.cljs
  src/main/frontend/components/query.cljs
  src/main/frontend/components/query_table.cljs
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/fs/watcher_handler.cljs
  src/main/frontend/handler/dnd.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/editor/property.cljs
  src/main/logseq/api.cljs
Labels: :type/dev

#9305 fix(plugin): incorrect renderer for the pagebar ui items
  src/main/frontend/components/plugins.cljs
Labels: :type/bug-fix

#9235 feat(ui): Ordered(number) list
  .clj-kondo/config.edn
  deps/graph-parser/src/logseq/graph_parser/property.cljs
  src/main/frontend/commands.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/content.cljs
  src/main/frontend/components/query.cljs
  src/main/frontend/components/query_table.cljs
  src/main/frontend/dicts.cljc
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/srs.cljs
  src/main/frontend/fs/watcher_handler.cljs
  src/main/frontend/handler/block.cljs
  src/main/frontend/handler/dnd.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/editor/property.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/modules/outliner/core.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/modules/shortcut/dicts.cljc
  src/main/frontend/util.cljc
  src/main/frontend/util/thingatpt.cljs
  src/main/frontend/utils.js
  src/main/logseq/api.cljs
Labels: :type/feature

#9293 Fix: Page tags and aliases should be deleted when deleted by user
  src/main/frontend/modules/outliner/core.cljs
  src/test/frontend/modules/outliner/core_test.cljs
Labels: :type/bug-fix

#9335 fix(android): paste with native input device
  src/main/frontend/handler/paste.cljs
Labels: :type/bug-fix

#9328 fix: adjust repeater ui
  src/main/frontend/components/datetime.cljs
Labels: fix

#9142 enhance(perf): insert and delete blocks
  .carve/ignore
  e2e-tests/editor.spec.ts
  src/main/frontend/components/block.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/handler/block.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/modules/editor/undo_redo.cljs
  src/main/frontend/modules/outliner/core.cljs
  src/main/frontend/modules/outliner/datascript.cljc
  src/main/frontend/modules/outliner/transaction.cljc
  src/main/frontend/state.cljs
  src/main/logseq/api.cljs
  src/test/frontend/db/model_test.cljs
Labels: :type/enhancement

#9340 Enhance (Whiteboards): Add prefix to default keyboard shortcuts
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/enhancement, :type/hold

#9344 fix(export): export table err when empty table-header
  src/main/frontend/handler/export/text.cljs
Labels: :type/bug-fix

#9323 fix(fs): handle graph name with percent symbol on mobile
  src/main/frontend/util/text.cljs
Labels: :type/bug-fix

#9310 fix: reduce page-history err when page doesn't have file-id yet
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/handler/file_sync.cljs
Labels: :type/bug-fix

#9351 chore: refine #9310
  src/main/frontend/handler/file_sync.cljs
Labels: :type/dev

#9352 fix(sync): validate rsapi upload err
  src/main/frontend/dicts.cljc
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#9355 fix: refresh the page after deleting blocks in a long page
  src/main/frontend/db/model.cljs
Labels: :type/bug-fix

#9372 fix: api get current block
  src/main/logseq/api.cljs
  src/main/logseq/api/block.cljs
  src/test/frontend/fs_test.cljs
  src/test/frontend/handler/plugin_config_test.cljs
  src/test/frontend/test/helper.cljs
  src/test/frontend/test/node_helper.cljs
  src/test/logseq/api_test.cljs
Labels: :type/bug-fix

#9375 fix(ui): incorrect arrangement of ui items from pagebar
  src/main/frontend/components/plugins.css
Labels: :type/bug-fix

#9399 Enhance/minor UI tweaks
  src/main/frontend/components/block.css
Labels: :type/enhancement

#9401 fix: can't jump to the correct position when editing number list
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
Labels: :type/bug-fix

#9405 Fix/mobile UI tweaks
  src/main/frontend/components/block.css
Labels: :type/bug-fix

#9373 Enhance: version control settings description update
  src/main/frontend/components/settings.cljs
Labels: ux

#9429 enhance(export): add title when page opml-export
  src/main/frontend/handler/export/opml.cljs
Labels: :type/enhancement

#9427 fix(editor): show block bullet when a blank block has children
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#9443 Fix: graph-parser.cli ignoring incorrectly for relative dir
  deps/common/src/logseq/common/graph.cljs
  deps/graph-parser/src/logseq/graph_parser/cli.cljs
  deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
  deps/graph-parser/test/logseq/graph_parser/cli_test.cljs
  src/test/frontend/handler/repo_conversion_test.cljs
  src/test/frontend/handler/repo_test.cljs
Labels: :type/bug-fix

#9441 chore(mobile): drop support for ios 13
  ios/App/App.xcodeproj/project.pbxproj
Labels: :type/dev

#9462 fix(ios): wrong link when sharing asset link
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#9453 fix(android): apply url decode before fs watcher notifies
  android/app/src/main/java/com/logseq/app/FsWatcher.java
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#9444 enhance(editor): scroll the view when selecting multiple blocks
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util.cljc
Labels: fix

#9466 chore(release): bump version 0.9.7
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#9388 enhance(E2E): editor string formatting and symbols autopairing tests
  e2e-tests/editor.spec.ts
  e2e-tests/utils.ts
Labels: looking-for-review

#9478 Dev: run e2e tests when releasing binaries
  .github/workflows/build-desktop-release.yml
Labels: :type/dev

#9465 enhance: improve RU translation
  src/main/frontend/dicts/ru.cljc
Labels: :type/hold

#9470 Chore: Rename temp :block keys to be explicit about their use
  deps/graph-parser/src/logseq/graph_parser/extract.cljc
  src/main/frontend/components/block.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/modules/outliner/core.cljs
  src/main/frontend/modules/outliner/datascript.cljc
  src/main/frontend/state.cljs
Labels: :type/dev

#9480 Fix (Whiteboards): Various issues
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/handler/whiteboard.cljs
  tldraw/apps/tldraw-logseq/src/components/QuickLinks/QuickLinks.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/GroupShape.tsx
  tldraw/packages/core/src/lib/TLPage/TLPage.ts
  tldraw/packages/core/src/lib/shapes/TLGroupShape/TLGroupShape.tsx
Labels: :type/bug-fix

#9525 fix(query): missing `:block/properties-order` attr for the custom query blocks
  src/main/frontend/db/model.cljs
Labels: :type/bug-fix

#9496 fix(ux): drop assets not working for the right sidebar
  src/main/frontend/components/container.cljs
Labels: :type/bug-fix

#9483 Fix: resizing of pdf area highlight
  src/main/frontend/extensions/pdf/core.cljs
Labels: :type/bug-fix

#9519 enhance(ui): add more semantic class to the order-list block element
  src/main/frontend/components/block.cljs
Labels: :type/enhancement

#9531 Bump mldoc to 1.5.5
  package.json
  yarn.lock
Labels: :type/dev

#9442 Feat: Integrated title bar for Windows and Linux [minor change]
  .github/workflows/build-desktop-release.yml
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  e2e-tests/window.spec.ts
  src/electron/electron/handler.cljs
  src/electron/electron/window.cljs
  src/main/frontend/components/container.cljs
  src/main/frontend/components/container.css
  src/main/frontend/components/header.cljs
  src/main/frontend/components/header.css
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/svg.cljs
  src/main/frontend/components/theme.css
  src/main/frontend/components/window_controls.cljs
  src/main/frontend/components/window_controls.css
  src/main/frontend/handler/route.cljs
  src/main/frontend/handler/ui.cljs
  src/main/frontend/page.cljs
  src/main/frontend/state.cljs
  src/main/frontend/ui.cljs
  src/resources/dicts/en.edn
  src/resources/dicts/es.edn
Labels: :type/feature

#9543 Fix (Whiteboards): Onboarding triggered on existing whiteboard
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/handler/route.cljs
  src/main/frontend/handler/whiteboard.cljs
Labels: :type/bug-fix

#8421 fix(editor): handle backspace when at beginning of line in embed page/block
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util.cljc
  src/test/frontend/handler/editor_test.cljs
  src/test/frontend/test/helper.cljs
Labels: fix
