Repository logseq/logseq, pull requests merged in 2023-11, with the labels that each got.

#10444 fix(android): activity restart when bluetooth kbd connected
  android/app/src/main/AndroidManifest.xml
Labels: :type/bug-fix

#10443 enhance(i18n): amplify tips
  packages/amplify/src/LSAuthenticator.tsx
  packages/amplify/src/amplify.ts
Labels: :type/enhancement

#10403 chore(release): bump version 0.9.20
  android/app/build.gradle
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10452 chore(build): update clojure 1.11.1.1413
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
  .github/workflows/build-docker.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-ios.yml
  .github/workflows/build-stage.yml
  .github/workflows/build.yml
  .github/workflows/db.yml
  .github/workflows/e2e.yml
  .github/workflows/graph-parser.yml
  .github/workflows/logseq-common.yml
  .github/workflows/publishing.yml
Labels: :type/dev

#10474 fix(ci): lock python version in release build
  .github/workflows/build-desktop-release.yml
Labels: :type/bug-fix

#10488 enhance(pdf): export asset ref link as dataset value for the pdf asset
  src/main/frontend/components/block.cljs
Labels: :type/enhancement

#10485 fix: multiple bugs with query builder construction
  src/main/frontend/components/query/builder.cljs
Labels: :type/bug-fix

#10493 Feat/cmdk radix tweaks
  deps/shui/src/logseq/shui/button/v2.cljs
  deps/shui/src/logseq/shui/core.cljs
  deps/shui/src/logseq/shui/shortcut/v1.cljs
  resources/css/codemirror.lsradix.css
  resources/css/shui.css
  resources/img/dark-theme.png
  resources/img/file-sync-unavailale-nonbacker-dark.png
  resources/img/file-sync-unavailale-nonbacker-light.png
  resources/img/file-sync-welcome-backer-dark.png
  resources/img/file-sync-welcome-backer-light.png
  resources/img/light-theme.png
  resources/img/system-theme.png
  resources/img/whiteboard-welcome-dark.png
  resources/img/whiteboard-welcome-light.png
  src/main/frontend/common.css
  src/main/frontend/components/container.css
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/components/shortcut.cljs
  src/main/frontend/components/shortcut.css
  src/main/frontend/components/shortcut2.cljs
  src/main/frontend/components/shortcut_help.cljs
  src/main/frontend/extensions/code.css
  src/main/frontend/modules/shortcut/data_helper.cljs
  src/main/frontend/ui.cljs
Labels: :type/feature

#10495 chore(deps): upgrade rsapi, rm doh
  resources/package.json
  static/yarn.lock
Labels: :type/dev

#10497 fix(fs): missing mkdir-recur! for nfs and memory-fs
  src/main/frontend/fs/memory_fs.cljs
  src/main/frontend/fs/nfs.cljs
Labels: :type/bug-fix

#10502 fix: send parameters to ui/button :button-props
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#10506 enhance: remove the need to add a space to trigger search command
  src/main/frontend/components/cmdk.cljs
Labels: :type/enhancement

#10520 enhance(ui): polish accent color details
  e2e-tests/accessibility.spec.ts
  e2e-tests/logseq-url.spec.ts
  e2e-tests/page-rename.spec.ts
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/colors.cljs
  src/main/frontend/common.css
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/onboarding/index.css
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page.css
  src/main/frontend/components/plugins.css
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/settings.css
  src/main/frontend/components/shortcut.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/extensions/graph.cljs
  src/main/frontend/extensions/graph/pixi.cljs
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/util.cljc
  src/main/frontend/utils.js
Labels: :type/bug-fix

#10521 fix(build): disable win code sign
  .github/workflows/build-desktop-release.yml
Labels: :type/bug-fix

#10532 enhance: validate :file/writes chan
  src/main/frontend/fs/sync.cljs
  src/main/frontend/modules/outliner/file.cljs
  src/main/frontend/state.cljs
  src/main/frontend/util.cljc
Labels: :type/enhancement

#10533 fix(fs): impl mkdir-recur! for memory-fs
  src/main/frontend/config.cljs
  src/main/frontend/fs/memory_fs.cljs
Labels: :type/bug-fix

#10537 fix: redirect to alias if possible
  src/main/frontend/components/cmdk.cljs
Labels: :type/bug-fix

#10543 Feat: multi tab db worker
  package.json
  src/main/frontend/db/restore.cljs
  src/main/frontend/db_worker.cljs
  src/main/frontend/modules/shortcut/core.cljs
  src/main/frontend/persist_db/browser.cljs
  src/main/frontend/persist_db/node.cljs
  yarn.lock
Labels: :type/feature

#10544 enhance: reactive whiteboard
  src/main/frontend/components/whiteboard.cljs
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/handler/whiteboard.cljs
Labels: :type/enhancement

#10559 fix(cmdk): enter key while ime composing
  src/main/frontend/components/cmdk.cljs
Labels: :type/bug-fix

#10526 enhance: Add color option to publishing app
  deps/publishing/src/logseq/publishing.cljs
  scripts/src/logseq/tasks/dev/publishing.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/publishing.cljs
Labels: :type/enhancement

#10522 Chore: v0.10.0 release
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10561 fix(cmdk): shift key state handling
  src/main/frontend/components/cmdk.cljs
  src/main/frontend/mixins.cljs
Labels: :type/bug-fix

#10562 enhance(cmdk): click subsection heading to toggle result more or less
  src/main/frontend/components/cmdk.cljs
Labels: :type/enhancement

#10585 fix(ui): incorrect node edges color for the global graph view #10578
  src/main/frontend/colors.cljs
Labels: :type/bug-fix

#10582 fix(ui): incorrect background color for the left sidebar on mobile
  src/main/frontend/common.css
  src/main/frontend/components/container.css
Labels: :type/bug-fix
