Repository logseq/logseq, pull requests merged in 2023-01, with the labels that each got.

#8179 style(search): center content in search items
  src/main/frontend/components/command_palette.cljs
  src/main/frontend/components/search.cljs
Labels: css, ux, looking-for-review, fix

#8168 fix(perf): faster kebab-case to camel-case conversion
  src/main/frontend/rum.cljs
Labels: :type/bug-fix

#8177 fix: save code block resets cursor position
  src/main/frontend/extensions/code.cljs
Labels: :type/bug-fix

#8201 enhance: Rotate undo/redo button icons
  src/main/frontend/mobile/mobile_bar.cljs
Labels: :type/enhancement, ux, mobile, looking-for-review

#7177 ehhancement: Prevent Ctrl+A from selecting the whole document
  src/main/frontend/components/page.css
  src/main/frontend/components/sidebar.css
Labels: :type/enhancement, looking-for-review

#6405 enhance: namespace pages in page preview header
  src/main/frontend/components/block.cljs
Labels: looking-for-review

#8204 improve(ux): add delete option for blocks context menu
  src/main/frontend/components/content.cljs
Labels: :type/enhancement

#8210 enhance(dev): document labels and their descriptions
  docs/issue-labels.md
Labels: :type/enhancement, :type/dev, looking-for-review

#8176 enhance(api): no need to pass `isPageBlock` for api/insert_block
  src/main/logseq/api.cljs
Labels: :type/enhancement

#8214 enhance: add login fn for e2e test
  src/main/frontend/config.cljs
  src/main/frontend/handler/user.cljs
Labels: :type/dev

#8203 enhance(docs): Add note about auto-formatting in `dev-practices.md`
  docs/dev-practices.md
Labels: :type/enhancement, :type/dev, looking-for-review

#8215 fix: do not link to a specific cljfmt version docs
  docs/dev-practices.md
Labels: :type/bug-fix

#8198 Chore: Document components related to hide page-preview itself when hovered hierarchy ref in the preview
  src/main/frontend/components/block.cljs
Labels: looking-for-review, fix

#8212 fix(e2e-test): should not wait for selector when there is no onboarding button
  e2e-tests/utils.ts
Labels: looking-for-review, fix

#8220 improve(ui): remove warning of macro renderer slot for mobile
  src/main/frontend/components/block.cljs
Labels: :type/enhancement

#8202 Enhance/plugins
  e2e-tests/plugins.spec.ts
  libs/src/LSPlugin.caller.ts
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  libs/src/LSPlugin.user.ts
  resources/js/lsplugin.core.js
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/search.cljs
  src/main/frontend/components/search.css
  src/main/frontend/state.cljs
  src/main/logseq/api.cljs
Labels: :type/enhancement

#8197 fix(ios): wrong behavior when backspace with line-head text selection
  src/main/frontend/handler/editor.cljs
Labels: :type/bug-fix

#8234 improve(plugin): filter hooks of db block changes for performance
  src/main/frontend/handler/plugin.cljs
  src/main/logseq/api.cljs
Labels: :type/enhancement

#8246 fix(sync): sync immediately when android app switching to background
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#7692 Chore(deps): Upgrade electron to 20
  package.json
  resources/package.json
  src/electron/electron/window.cljs
  static/yarn.lock
  yarn.lock
Labels: :type/dev, looking-for-review

#8262 fix(dev): remove print steps from stale action
  .github/workflows/stale-issues.yml
Labels: looking-for-review, fix

#8199 enhance: allows empty content only for delete-blocks and move-blocks
  .gitignore
  src/main/frontend/modules/file/core.cljs
  src/main/frontend/modules/outliner/file.cljs
  src/main/frontend/modules/outliner/pipeline.cljs
Labels: :type/enhancement

#8283 fix: disable plugins e2e tests temporally
  e2e-tests/plugins.spec.ts
Labels: :type/bug-fix

#8221 docs: Update Logseq Code of Conduct
  CODE_OF_CONDUCT.md
Labels: looking-for-review

#8291 Feat/check app wake from sleep
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler.cljs
  src/main/frontend/util.cljc
Labels: :type/feature

#8266 fix(hierarchy): should update `:block/namespace` while renaming page
  src/main/frontend/handler/page.cljs
Labels: looking-for-review, fix

#8268 enhance(ui): remove non clickable space between links in sidebar
  src/main/frontend/components/sidebar.css
Labels: :type/enhancement, looking-for-review

#8290 Enhance: Allow :rules and built in rules to be used together
  src/main/frontend/db/query_custom.cljs
  src/test/frontend/db/query_custom_test.cljs
Labels: :type/enhancement

#8103 feat:pdf highlight drag & drop
  src/main/frontend/components/block.cljs
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/pdf/highlights.cljs
  src/main/frontend/handler/editor/keyboards.cljs
Labels: :type/feature

#8307 dev: update cider-nrepl to 0.29.0
  deps.edn
Labels: :type/dev

#8315 fix(test): e2e fail due to whiteboards zoom test
  e2e-tests/whiteboards.spec.ts
Labels: :type/bug-fix

#8312 feat: add frontend.pubsub ns
  .clj-kondo/config.edn
  src/main/frontend/fs/sync.cljs
  src/main/frontend/pubsub.cljc
  src/main/frontend/util.cljc
Labels: :type/feature

#8318 docs(dev): update linting to match bb dev:lint
  docs/dev-practices.md
Labels: build, :type/dev

#8323 perf: Reduce usage of remove-nils since it's too slow
  deps/graph-parser/.carve/ignore
  deps/graph-parser/src/logseq/graph_parser.cljs
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  deps/graph-parser/src/logseq/graph_parser/extract.cljc
  deps/graph-parser/src/logseq/graph_parser/util.cljs
  src/main/frontend/db/utils.cljs
  src/main/frontend/handler/repo.cljs
Labels: :type/performance

#8317 feat: bug report page & clipboard data inspector
  src/main/frontend/components/bug_report.cljs
  src/main/frontend/components/bug_report.css
  src/main/frontend/components/header.cljs
  src/main/frontend/routes.cljs
Labels: feature

#8328 fix(ui): error calling set-step! in bug-report
  src/main/frontend/components/bug_report.cljs
Labels: :type/bug-fix

#8240 enhance(pdf): make the weblink pdf filename to be human-readable for the annotations page
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/pdf/utils.cljs
  src/test/frontend/extensions/pdf/assets_test.cljs
Labels: :type/enhancement

#8321 chore: bump version 0.8.16
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#8326 feat: export login-callback fn
  src/main/frontend/handler/user.cljs
Labels: :type/feature

#8336 Fix: Page properties not being visible in the query table
  src/main/frontend/components/query_table.cljs
Labels: :type/bug-fix

#8200 fix: Add error notification if graph can't be opened
  src/electron/electron/handler.cljs
Labels: looking-for-review, fix

#8351 fix(mobile): not showing hide keyboard button
  src/main/frontend/mobile/mobile_bar.cljs
Labels: :type/bug-fix

#8350 fix(sync): update deps, fix expired token issue
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/bug-fix

#8265 dev: add malli-schema & generate kondo config
  .carve/ignore
  .clj-kondo/metosin/malli-types/config.edn
  bb.edn
  deps.edn
  scripts/src/logseq/tasks/dev.clj
  shadow-cljs.edn
  src/main/frontend/core.cljs
  src/main/frontend/handler/paste.cljs
  src/main/frontend/util.cljc
  src/main/gen_malli_kondo_config/collect.clj
  src/main/gen_malli_kondo_config/core.cljs
Labels: :type/dev

#8363 fix: Clarify the option to prefer pasting a file rather than text
  src/main/frontend/dicts.cljc
  templates/config.edn
Labels: fix

#8345 enhance: replace sync/sync-events-publication with pubsub/sync-events-pub
  src/main/frontend/fs/sync.cljs
  src/main/frontend/handler/file_sync.cljs
  src/main/frontend/pubsub.cljc
Labels: :type/enhancement

#8366 chore(deps): update rsapi, add upload retries
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/dev

#8164 fix(video): validate URL in `video` block
  src/main/frontend/components/block.cljs
Labels: awaiting-response, fix

#8358 Fix: rendering of inline symbols #7054
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#7676 fix(zotero): Missing PDF caused by incomplete linked file path.
  src/main/frontend/extensions/zotero/extractor.cljs
  src/test/frontend/extensions/zotero/extractor_test.cljs
Labels: integration:zotero, :type/dev, estimate: small

#8373 Fix search tippy component failing
  src/main/frontend/components/search.cljs
  src/main/frontend/state.cljs
Labels: :type/bug-fix

#8381 fix: remove extra braces for some incorrect macro usages
  src/main/frontend/components/block.cljs
Labels: fix

#8385 fix(ui): null while query .editor-wrapper
  src/main/frontend/components/editor.cljs
Labels: :type/bug-fix

#8299 enhance: add classes to macros
  src/main/frontend/components/block.cljs
Labels: :type/enhancement

#8388 fix(dev): bb gen-malli-kondo-config
  src/dev-cljs/gen_malli_kondo_config/core.cljs
Labels: :type/bug-fix

#8279 feat (whiteboards): add tweet shape
  e2e-tests/whiteboards.spec.ts
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/state.cljs
  tldraw/apps/tldraw-logseq/src/components/ContextBar/contextBarActionFactory.tsx
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
  tldraw/apps/tldraw-logseq/src/lib/logseq-context.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/IFrameShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/TextShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/TweetShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/YouTubeShape.tsx
  tldraw/apps/tldraw-logseq/src/lib/shapes/index.ts
  tldraw/apps/tldraw-logseq/src/styles.css
Labels: :type/bug-fix, :type/feature

#8404 Fix: :commands in config schema - fixes #8403
  bb.edn
  deps.edn
  src/main/frontend/schema/handler/common_config.cljc
Labels: :type/bug-fix

#8393 chore(dep): bump actions/checkout to v3.3.0
  .github/workflows/build-android.yml
  .github/workflows/build-desktop-release.yml
  .github/workflows/build-docker.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-ios.yml
  .github/workflows/build-stage.yml
  .github/workflows/build.yml
  .github/workflows/db.yml
  .github/workflows/e2e.yml
  .github/workflows/graph-parser.yml
Labels: :type/dev, looking-for-review, security

#8305 feat: support dragging the PDF viewer head to move the window, #7187
  src/main/frontend/extensions/pdf/pdf.css
  src/main/frontend/extensions/pdf/toolbar.cljs
Labels: feature, looking-for-review

#8417 Fix: Allow keywords for macros in config.edn
  src/main/frontend/schema/handler/common_config.cljc
Labels: :type/bug-fix

#8415 fix: CodeMirror indenting shortcuts cause page routing
  src/main/frontend/extensions/code.cljs
Labels: fix

#8416 Fix (Whiteboards): paste type order
  tldraw/apps/tldraw-logseq/src/hooks/usePaste.ts
  tldraw/apps/tldraw-logseq/src/lib/shapes/TweetShape.tsx
Labels: :type/bug-fix

#8425 fix (witeboards): disable onboarding tour on demo graph
  src/main/frontend/components/whiteboard.cljs
Labels: :type/bug-fix

#8429 fix: add missing user-config options
  templates/config.edn
Labels: :type/bug-fix, user-config

#8455 enhance(issue-template): add description to `ask-pr`
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: :type/dev

#8450 Enhancement: Add dev ast inspector menu items, dev commands and clear all notifications command
  .clj-kondo/config.edn
  src/main/frontend/components/content.cljs
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/handler/common/developer.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/modules/shortcut/config.cljs
Labels: :type/enhancement, looking-for-review

#8464 chore: Add Slovak language
  src/main/frontend/dicts.cljc
  src/main/frontend/modules/shortcut/dicts.cljc
  templates/dummy-notes-sk.md
  templates/tutorial-sk.md
Labels: chore, i18n

#8399 fix: searching in page defers while entering Chinese character using a Pinyin IME
  src/main/frontend/components/find_in_page.cljs
  src/main/frontend/handler/search.cljs
  src/main/frontend/util.cljc
Labels: lang:cjk, i18n, fix

#8479 fix(dev): md/stop! will rewrite malli-kondo config.edn with {}
  src/main/frontend/core.cljs
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#8481 i18n: update Turkish translation
  src/main/frontend/dicts.cljc
Labels: i18n

#8476 docs: Fix arch/sudo command in instructions
  docs/develop-logseq-on-mobile.md
Labels: :type/dev, looking-for-review
