Repository logseq/logseq, pull requests merged in 2024-12, with the labels that each got.

#11628 frontend/block code: set ClojureScript as a Clojure language
  src/main/frontend/components/block.cljs
Labels: :type/bug-fix

#11454 Update Korean translation
  src/resources/dicts/ko.edn
Labels: awaiting-response

#11636 Chore: Update actions to use Node 20
  .github/workflows/build-android.yml
  .github/workflows/build-demo.yml
  .github/workflows/build-desktop-release.yml
  .github/workflows/build-ios-release.yml
  .github/workflows/build-ios.yml
  .github/workflows/build-stage.yml
  .github/workflows/build.yml
  .github/workflows/db.yml
  .github/workflows/deploy-db-pages.yml
  .github/workflows/deploy-db-test-pages.yml
  .github/workflows/e2e.yml
  .github/workflows/graph-parser.yml
  .github/workflows/logseq-common.yml
  .github/workflows/outliner.yml
  .github/workflows/publishing.yml
Labels: :type/dev

#11642 fix(ci): change timestamp server
  .github/workflows/build-desktop-release.yml
Labels: :type/bug-fix

#11649 Enhance(UX): left sidebar
  packages/ui/@/hooks/use-mobile.tsx
  packages/ui/package.json
  packages/ui/src/ui.ts
  packages/ui/tailwind.config.js
  packages/ui/yarn.lock
  scripts/src/logseq/tasks/lang.clj
  src/main/frontend/components/cmdk/core.cljs
  src/main/frontend/components/container.cljs
  src/main/frontend/components/container.css
  src/main/frontend/components/header.css
  src/main/frontend/components/repo.cljs
  src/main/frontend/components/repo.css
  src/main/frontend/components/right_sidebar.css
  src/main/frontend/components/theme.css
  src/main/frontend/context/i18n.cljs
  src/main/frontend/handler/route.cljs
  src/main/frontend/state.cljs
Labels: :type/feature

#11654 feat: repeated tasks
  deps/common/package.json
  deps/common/src/logseq/common/util.cljs
  deps/common/src/logseq/common/util/date_time.cljs
  deps/common/yarn.lock
  deps/db/package.json
  deps/db/src/logseq/db/frontend/property.cljs
  deps/db/src/logseq/db/frontend/property/build.cljs
  deps/db/src/logseq/db/frontend/schema.cljs
  deps/db/src/logseq/db/frontend/validate.cljs
  deps/db/src/logseq/db/sqlite/common_db.cljs
  deps/db/src/logseq/db/sqlite/create_graph.cljs
  deps/db/src/logseq/db/sqlite/util.cljs
  deps/db/yarn.lock
  deps/graph-parser/package.json
  deps/graph-parser/src/logseq/graph_parser/exporter.cljs
  deps/graph-parser/test/logseq/graph_parser/exporter_test.cljs
  deps/graph-parser/yarn.lock
  deps/outliner/package.json
  deps/outliner/src/logseq/outliner/pipeline.cljs
  deps/outliner/src/logseq/outliner/property.cljs
  deps/outliner/test/logseq/outliner/validate_test.cljs
  deps/outliner/yarn.lock
  deps/publishing/package.json
  deps/publishing/yarn.lock
  deps/shui/src/logseq/shui/base/core.cljs
  deps/shui/src/logseq/shui/ui.cljs
  resources/css/shui.css
  scripts/package.json
  scripts/src/logseq/tasks/dev/db_and_file_graphs.clj
  scripts/yarn.lock
  src/main/frontend/commands.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/header.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/property.cljs
  src/main/frontend/components/property/config.cljs
  src/main/frontend/components/property/default_value.cljs
  src/main/frontend/components/property/value.cljs
  src/main/frontend/components/property/value.css
  src/main/frontend/components/repo.css
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/rtc/indicator.cljs
  src/main/frontend/components/server.cljs
  src/main/frontend/components/views.cljs
  src/main/frontend/date.cljs
  src/main/frontend/db/async.cljs
  src/main/frontend/extensions/fsrs.cljs
  src/main/frontend/template.cljs
  src/main/frontend/ui.cljs
  src/main/frontend/worker/commands.cljs
  src/main/frontend/worker/db/migrate.cljs
  src/main/frontend/worker/device.cljs
  src/main/frontend/worker/handler/page/db_based/page.cljs
  src/main/frontend/worker/pipeline.cljs
  src/rtc_e2e_test/client_steps.cljs
  src/rtc_e2e_test/helper.cljs
Labels: :type/feature
