Repository logseq/logseq, pull requests merged in 2024-09, with the labels that each got.

#11511 Feature: tag multiple views
  deps/db/src/logseq/db.cljs
  deps/db/src/logseq/db/frontend/property.cljs
  deps/db/src/logseq/db/frontend/schema.cljs
  src/main/frontend/components/objects.cljs
  src/main/frontend/components/views.cljs
  src/main/frontend/db/async.cljs
  src/main/frontend/worker/db/migrate.cljs
Labels: :type/feature

#11525 fix: Accessing date page from Graph View breaks Journals
  deps/db/src/logseq/db/frontend/property.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page_menu.cljs
  src/main/frontend/components/query/builder.cljs
  src/main/frontend/components/title.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/extensions/graph.cljs
  src/main/frontend/extensions/graph/pixi.cljs
  src/main/frontend/handler/common/page.cljs
  src/main/frontend/handler/graph.cljs
  src/test/frontend/db/model_test.cljs
Labels: :type/bug-fix

#11531 feat: support nlp date in node reference
  src/main/frontend/common/search_fuzzy.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/date.cljs
  src/main/frontend/db/react.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/ui.cljs
  src/rtc_e2e_test/example.cljs
  src/test/frontend/db/db_based_model_test.cljs
Labels: :type/enhancement

#11535 enhance(ux): use arrows for properties navigation
  src/main/frontend/components/block.cljs
  src/main/frontend/components/property.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util.cljc
  src/main/frontend/util/cursor.cljs
Labels: :type/enhancement

#11517 feat: support namespace pages and tags
  deps/db/src/logseq/db/frontend/entity_plus.cljc
  deps/db/src/logseq/db/sqlite/util.cljs
  deps/outliner/src/logseq/outliner/core.cljs
  scripts/src/logseq/tasks/dev/db_and_file_graphs.clj
  src/main/frontend/components/block.cljs
  src/main/frontend/components/class.cljs
  src/main/frontend/components/cmdk/core.cljs
  src/main/frontend/components/container.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/property/value.cljs
  src/main/frontend/handler/block.cljs
  src/main/frontend/handler/common/page.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/page.cljs
  src/main/frontend/modules/shortcut/config.cljs
  src/main/frontend/worker/handler/page/db_based/page.cljs
  src/main/frontend/worker/search.cljs
  src/main/logseq/api.cljs
Labels: :type/feature

#11537 enhance(ux):resize table columns
  deps/db/src/logseq/db/frontend/property.cljs
  deps/db/src/logseq/db/frontend/schema.cljs
  src/main/frontend/components/dnd.cljs
  src/main/frontend/components/table.css
  src/main/frontend/components/views.cljs
  src/main/frontend/worker/db/migrate.cljs
Labels: :type/enhancement

#11545 feat: code/quote/math block
  deps/db/src/logseq/db/frontend/property.cljs
  deps/db/src/logseq/db/frontend/schema.cljs
  deps/outliner/src/logseq/outliner/property.cljs
  src/main/frontend/commands.cljs
  src/main/frontend/common.css
  src/main/frontend/components/block.cljs
  src/main/frontend/components/property/value.cljs
  src/main/frontend/extensions/code.cljs
  src/main/frontend/extensions/latex.cljs
  src/main/frontend/handler/code.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/worker/db/migrate.cljs
  src/main/frontend/worker/rtc/db_listener.cljs
  validate.cljs
Labels: :type/feature

#11548 fix: slow query ux
  deps/db/src/logseq/db/frontend/property.cljs
  deps/outliner/src/logseq/outliner/property.cljs
  src/main/frontend/commands.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/components/property.cljs
  src/main/frontend/components/property/value.cljs
  src/main/frontend/components/query.cljs
  src/main/frontend/components/query/builder.cljs
  src/main/frontend/components/query/result.cljs
  src/main/frontend/components/query/view.cljs
  src/main/frontend/extensions/fsrs.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/worker/db/migrate.cljs
Labels: :type/enhancement

#11551 fix: custom query not updated
  src/main/frontend/components/block.cljs
  src/main/frontend/components/file_based/query.cljs
  src/main/frontend/components/query.cljs
  src/main/frontend/components/query/result.cljs
  src/main/frontend/util.cljc
  src/test/frontend/components/query/result_test.cljs
Labels: :type/bug-fix

#11468 Enhance (dev): Tabler icons
  deps/publishing/src/logseq/publishing/html.cljs
  gulpfile.js
  package.json
  public/index.html
  resources/index.html
  resources/js/prop-types.min.js
  resources/js/tabler-icons-react.min.js
  resources/js/tabler.min.js
  tailwind.all.css
  yarn.lock
Labels: :type/dev
