Repository logseq/logseq, pull requests merged in 2024-03, with the labels that each got.

#11068 fix(ux): support herf prop for the classical ui button component
  src/main/frontend/ui.cljs
Labels: :type/bug-fix

#11088 chore(deps): update rsapi and fix token expiration
  resources/package.json
  static/yarn.lock
Labels: :type/dev

#11102 Fix(db) css asset loading
  deps/graph-parser/src/logseq/graph_parser/exporter.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/config.cljs
  src/main/frontend/extensions/pdf/assets.cljs
  src/main/frontend/extensions/pdf/toolbar.cljs
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/handler/assets.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/ui.cljs
  src/main/logseq/sdk/assets.cljs
Labels: :type/bug-fix

#11133 chore(release): bump version 0.10.8
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#11140 dev: print global error message
  src/main/frontend/handler.cljs
Labels: :type/dev

#11147 fix(search): fine tune page title search strategy
  src/main/frontend/search/db.cljs
Labels: :type/bug-fix

#11130 dev: remove obsolete "@tailwindcss/line-clamp" dependency
  package.json
  tailwind.config.js
  yarn.lock
Labels: fix

#11055 New attribute for class parent
  deps/db/src/logseq/db.cljs
  deps/db/src/logseq/db/frontend/malli_schema.cljs
  deps/db/src/logseq/db/frontend/rules.cljc
  deps/db/src/logseq/db/frontend/schema.cljs
  deps/db/src/logseq/db/sqlite/db.cljs
  scripts/src/logseq/tasks/db_graph/create_graph_with_schema_org.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/class.cljs
  src/main/frontend/components/db_based/page.cljs
  src/main/frontend/components/hierarchy.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/property/value.cljs
  src/main/frontend/db/model.cljs
  src/main/frontend/handler/db_based/property.cljs
  src/test/frontend/db/db_based_model_test.cljs
  src/test/frontend/handler/db_based/property_test.cljs
Labels: :type/bug-fix

#11163 Fix: macOS release build
  .github/workflows/build-desktop-release.yml
  resources/forge.config.js
  resources/package.json
  static/yarn.lock
Labels: :type/bug-fix
