Repository logseq/logseq, pull requests merged in 2024-05, with the labels that each got.

#11280 fix(sync): cannot delete some nested files
  deps/common/src/logseq/common/graph.cljs
Labels: :type/bug-fix

#11301 Add MSI build for windows
  .github/workflows/build-desktop-release.yml
  resources/forge.config.js
  resources/package.json
  resources/windows/background.jpg
  resources/windows/banner.jpg
  resources/windows/wix.xml
  static/yarn.lock
Labels: :type/dev

#11304 Update Electron 28
  e2e-tests/fixtures.ts
  e2e-tests/logseq-api.spec.ts
  e2e-tests/plugins.spec.ts
  e2e-tests/utils.ts
  package.json
  resources/package.json
  static/yarn.lock
  yarn.lock
Labels: :type/dev

#11272 fix(mobile): incorrect theme color for the android status bar
  src/main/frontend/util.cljc
Labels: :type/bug-fix

#11341 fix(ios): add new ipad resolutions
  src/main/frontend/mobile/util.cljs
Labels: :type/bug-fix

#11343 chore: bump ios version, prepare for tf release
  ios/App/App.xcodeproj/project.pbxproj
Labels: :type/dev

#11325 Fix Twitter's rename breaking macro wrapping
  src/main/frontend/handler/paste.cljs
  src/main/frontend/quick_capture.cljs
  src/test/frontend/handler/paste_test.cljs
Labels: fix

#11338 chore(release): bump version 0.10.10
  android/app/build.gradle
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev
