Repository logseq/logseq, pull requests merged in 2024-08, with the labels that each got.

#11452 fix: copying non-png images from the image overlay toolbar
  src/main/frontend/util.cljc
Labels: :type/bug-fix

#10981 Enhance (dev)
  gulpfile.js
  package.json
  packages/tldraw/apps/tldraw-logseq/src/styles.css
  resources/electron.html
  resources/js/glide/glide.core.min.css
  resources/js/glide/glide.min.js
  resources/js/glide/glide.theme.min.css
  resources/js/react-dom.development.min.js
  resources/js/react-dom.production.min.js
  resources/js/react.development.js
  resources/js/react.production.min.js
  resources/js/ui.js
  src/electron/electron/window.cljs
  src/main/frontend/modules/instrumentation/sentry.cljs
  yarn.lock
Labels: :type/enhancement

#11483 safety: delete kvs row if only it's not used anymore
  .github/workflows/build-stage.yml
  deps.edn
  deps/db/deps.edn
  deps/db/src/logseq/db/sqlite/common_db.cljs
  deps/outliner/deps.edn
  src/main/frontend/components/export.cljs
  src/main/frontend/handler/export.cljs
  src/main/frontend/handler/export/common.cljs
  src/main/frontend/worker/db/migrate.cljs
  src/main/frontend/worker/db_worker.cljs
  src/main/frontend/worker/export.cljs
Labels: :type/bug-fix

#11492 test: add rtc-e2e-test
  .carve/config.edn
  bb.edn
  deps.edn
  karma.conf.js
  package.json
  scripts/src/logseq/tasks/dev.clj
  shadow-cljs.edn
  src/main/frontend/common/missionary_util.cljs
  src/main/frontend/worker/db_listener.cljs
  src/main/frontend/worker/pipeline.cljs
  src/main/frontend/worker/rtc/client.cljs
  src/main/frontend/worker/rtc/const.cljs
  src/main/frontend/worker/rtc/core.cljs
  src/main/frontend/worker/rtc/exception.cljs
  src/main/frontend/worker/rtc/full_upload_download_graph.cljs
  src/main/frontend/worker/rtc/log_and_state.cljs
  src/main/frontend/worker/rtc/remote_update.cljs
  src/main/frontend/worker/rtc/skeleton.cljs
  src/rtc_e2e_test/basic_edits_test.cljs
  src/rtc_e2e_test/client1_edits.cljs
  src/rtc_e2e_test/client2_edits.cljs
  src/rtc_e2e_test/const.cljs
  src/rtc_e2e_test/example.cljs
  src/rtc_e2e_test/fixture.cljs
  src/rtc_e2e_test/helper.cljs
Labels: :type/dev
