Repository logseq/logseq, pull requests merged in 2024-02, with the labels that each got.

#10945 enhance(editor): support time offset of youtube links
  src/main/frontend/components/block.cljs
  src/main/frontend/extensions/video/youtube.cljs
Labels: :type/enhancement

#10962 fix(editor): wrong new page link handling in graph view
  src/main/frontend/components/page.cljs
Labels: :type/bug-fix

#10935 chore: Release 0.10.6
  android/app/build.gradle
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10998 fix(config): wrong `:command/toggle-favorite` handling
  src/main/frontend/components/container.cljs
Labels: :type/bug-fix

#11016 fix(ui): shorter heading for pwd input box
  src/main/frontend/components/encryption.cljs
Labels: :type/bug-fix

#11048 Enhance(ux): better MacOS scrollbar for the auto scrolling mode
  src/main/frontend/components/theme.cljs
  src/main/frontend/components/theme.css
Labels: :type/bug-fix

#11054 chore(release): bump version 0.10.7
  android/app/build.gradle
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev
