Repository logseq/logseq, pull requests merged in 2024-01, with the labels that each got.

#10770 Import from graph folder to db graph
  deps/graph-parser/src/logseq/graph_parser.cljs
  deps/graph-parser/src/logseq/graph_parser/block.cljs
  src/main/frontend/components/imports.cljs
  src/main/frontend/handler/repo.cljs
Labels: :type/feature

#10798 fix(ui): incorrect position for the filter modal on ios platform
  src/main/frontend/ui.css
Labels: :type/bug-fix

#10759 fix(query): cannot toggle updated-at and created-at
  src/main/frontend/components/query_table.cljs
Labels: :type/bug-fix

#10813 fix(sync): do not notify when logged out
  src/main/frontend/fs/sync.cljs
Labels: :type/bug-fix

#10820 fix(ui): prevent button in modal from being clicked twice when pressing enter key
  src/main/frontend/ui.cljs
Labels: fix

#10832 fix(rsapi): refine build, supports old glibc
  resources/package.json
  static/yarn.lock
Labels: :type/bug-fix

#10845 fix(android/watcher): wrong relpath calculation
  android/app/src/main/java/com/logseq/app/FsWatcher.java
Labels: :type/bug-fix

#10807 fix(export): remove prefix spaces when no-indent
  src/main/frontend/handler/export/common.cljs
  src/main/frontend/handler/export/html.cljs
  src/main/frontend/handler/export/opml.cljs
  src/main/frontend/handler/export/text.cljs
  src/test/frontend/handler/export_test.cljs
Labels: :type/bug-fix

#10857 chore: upgrade @swc/core (adds 16k pages support)
  tldraw/demo/package.json
  tldraw/yarn.lock
Labels: fix

#10782 Enhance: APIs related issues
  libs/package.json
  libs/src/LSPlugin.caller.ts
  libs/src/LSPlugin.core.ts
  libs/src/LSPlugin.ts
  resources/js/lsplugin.core.js
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/query_table.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/plugin.cljs
  src/main/frontend/modules/outliner/core.cljs
  src/main/logseq/api.cljs
Labels: :type/enhancement

#10859 chore(release): bump version 0.10.4
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10880 chore(release): bump version 0.10.5
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#10790 Fix outdent-then-delete removing incorrect block
  src/main/frontend/handler/editor.cljs
Labels: editor, :type/bug-fix

#10912 chore(build): rm postcss version lock
  package.json
  yarn.lock
Labels: :type/dev

#10922 fix(android): sync crash caused by wrong logging
  package.json
  yarn.lock
Labels: :type/bug-fix

#10924 fix(mobile): cold start performance of block search
  src/main/frontend/search/db.cljs
Labels: :type/bug-fix
