Repository logseq/logseq, pull requests merged in 2024-04, with the labels that each got.

#11194 ci: self-hosted runner for codesign
  .github/workflows/build-desktop-release.yml
Labels: :type/dev

#11207 fix: feature request dead link
  .github/stale-issues.yml
  .github/workflows/stale-issues.yml
  CONTRIBUTING.md
  src/main/frontend/components/container.cljs
  src/main/frontend/components/onboarding.cljs
Labels: :type/bug-fix

#11215 ci(build): refine windows sign
  .github/workflows/build-desktop-release.yml
Labels: :type/bug-fix

#11247 fix(ui): missing default colors for mark tag
  src/main/frontend/common.css
Labels: :type/bug-fix

#11246 fix(macos): windows restore at current workspace
  src/electron/electron/window.cljs
Labels: :type/bug-fix

#11255 fix(editor): new block placeholder should accept tab and enter key
  src/main/frontend/components/page.cljs
  src/main/frontend/components/page.css
Labels: :type/bug-fix

#11219 chore(release): bump version 0.10.9
  android/app/build.gradle
  ios/App/App.xcodeproj/project.pbxproj
  resources/forge.config.js
  resources/package.json
  src/main/frontend/version.cljs
Labels: :type/dev

#11271 enhance(ux): better highlights page name for the search result items
  deps/shui/src/logseq/shui/list_item/v1.cljs
  src/main/frontend/components/cmdk.cljs
Labels: :type/enhancement
