Repository logseq/logseq, pull requests merged in 2025-04, with the labels that each got.

#11810 Bump React to 18
  deps.edn
  deps/shui/deps.edn
  deps/shui/src/logseq/shui/demo.cljs
  deps/shui/src/logseq/shui/demo2.cljs
  deps/shui/src/logseq/shui/dialog/core.cljs
  deps/shui/src/logseq/shui/hooks.cljs
  deps/shui/src/logseq/shui/select/multi.cljs
  deps/shui/src/logseq/shui/table/core.cljc
  deps/shui/src/logseq/shui/toaster/core.cljs
  package.json
  src/main/frontend/components/all_pages.cljs
  src/main/frontend/components/assets.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/components/bug_report.cljs
  src/main/frontend/components/cmdk/core.cljs
  src/main/frontend/components/cmdk/list_item.cljs
  src/main/frontend/components/container.cljs
  src/main/frontend/components/dnd.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/components/file_based/block.cljs
  src/main/frontend/components/file_based/git.cljs
  src/main/frontend/components/file_sync.cljs
  src/main/frontend/components/handbooks.cljs
  src/main/frontend/components/header.cljs
  src/main/frontend/components/icon.cljs
  src/main/frontend/components/imports.cljs
  src/main/frontend/components/objects.cljs
  src/main/frontend/components/page.cljs
  src/main/frontend/components/plugins.cljs
  src/main/frontend/components/plugins_settings.cljs
  src/main/frontend/components/property.cljs
  src/main/frontend/components/property/config.cljs
  src/main/frontend/components/property/value.cljs
  src/main/frontend/components/query.cljs
  src/main/frontend/components/query/builder.cljs
  src/main/frontend/components/right_sidebar.cljs
  src/main/frontend/components/server.cljs
  src/main/frontend/components/settings.cljs
  src/main/frontend/components/shortcut.cljs
  src/main/frontend/components/theme.cljs
  src/main/frontend/components/user/login.cljs
  src/main/frontend/components/views.cljs
  src/main/frontend/extensions/handbooks/core.cljs
  src/main/frontend/extensions/pdf/core.cljs
  src/main/frontend/extensions/pdf/toolbar.cljs
  src/main/frontend/extensions/tldraw.cljs
  src/main/frontend/extensions/zotero.cljs
  src/main/frontend/mobile/graph_picker.cljs
  src/main/frontend/rum.cljs
  src/main/frontend/ui.cljs
  yarn.lock
Labels: :type/dev

#11823 enhance:  / command input tolerance
  src/main/frontend/commands.cljs
  src/main/frontend/components/editor.cljs
  src/main/frontend/handler/editor.cljs
  src/test/frontend/handler/editor_test.cljs
Labels: :type/enhancement

#11825 enhance: property keyboard navigation
  src/main/frontend/components/block.cljs
  src/main/frontend/components/property.cljs
  src/main/frontend/components/property.css
  src/main/frontend/components/property/value.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/util.cljc
Labels: :type/enhancement

#11819 feat: multiple tabs/windows support
  .clj-kondo/config.edn
  deps/common/src/logseq/common/util.cljs
  src/electron/electron/core.cljs
  src/main/electron/listener.cljs
  src/main/frontend/db/conn.cljs
  src/main/frontend/db/restore.cljs
  src/main/frontend/db/rtc/debug_ui.cljs
  src/main/frontend/db/transact.cljs
  src/main/frontend/handler/db_based/rtc.cljs
  src/main/frontend/handler/editor/lifecycle.cljs
  src/main/frontend/handler/events.cljs
  src/main/frontend/handler/events/ui.cljs
  src/main/frontend/handler/history.cljs
  src/main/frontend/handler/repo.cljs
  src/main/frontend/handler/ui.cljs
  src/main/frontend/handler/user.cljs
  src/main/frontend/modules/outliner/pipeline.cljs
  src/main/frontend/modules/outliner/ui.cljc
  src/main/frontend/persist_db/browser.cljs
  src/main/frontend/state.cljs
  src/main/frontend/undo_redo.cljs
  src/main/frontend/util/page.cljs
  src/main/frontend/worker/db/validate.cljs
  src/main/frontend/worker/db_listener.cljs
  src/main/frontend/worker/db_worker.cljs
  src/main/frontend/worker/pipeline.cljs
  src/main/frontend/worker/rtc/core.cljs
  src/main/frontend/worker/rtc/full_upload_download_graph.cljs
  src/main/frontend/worker/rtc/log_and_state.cljs
  src/main/frontend/worker/rtc/skeleton.cljs
  src/main/frontend/worker/shared_service.cljs
  src/main/frontend/worker/state.cljs
  src/rtc_e2e_test/client_steps.cljs
  src/test/frontend/undo_redo_test.cljs
Labels: :type/bug-fix

#11828 enhance: add e2e tests for outliner ops
  .github/workflows/clj-e2e.yml
  .gitignore
  clj-e2e/.gitignore
  clj-e2e/README.md
  clj-e2e/bb.edn
  clj-e2e/build.clj
  clj-e2e/deps.edn
  clj-e2e/src/logseq/e2e.clj
  clj-e2e/test/logseq/editor_test.clj
  clj-e2e/test/logseq/fixtures.clj
  clj-e2e/test/logseq/outliner_test.clj
  clj-e2e/test/logseq/repl.clj
  clj-e2e/test/logseq/util.clj
  src/main/frontend/worker/export.cljs
Labels: :type/dev

#11833 enhance(ux): number property input
  src/main/frontend/components/property/value.cljs
  src/main/frontend/components/property/value.css
  src/main/frontend/handler/editor.cljs
Labels: :type/enhancement
