Repository logseq/logseq, pull requests merged in 2025-06, with the labels that each got.

#11914 enhance(dev): upgrade pdfjs
  deps.edn
  gulpfile.js
  package.json
  resources/index.html
  resources/js/pdf_viewer2.js
  resources/js/pdf_viewer3.mjs
  src/main/frontend/extensions/pdf/core.cljs
  src/main/frontend/extensions/pdf/utils.cljs
  yarn.lock
Labels: :type/bug-fix

#11912 fix: multiple default views created for linked references
  deps/common/src/logseq/common/uuid.cljs
  src/main/frontend/components/views.cljs
Labels: :type/bug-fix

#11920 fix: node property value dropdown doesn't allow choosing existing values
  src/main/frontend/components/property/value.cljs
Labels: :type/bug-fix

#11929 fix: bump nbb-logseq to include datascript and nbb fixes
  deps/common/package.json
  deps/common/yarn.lock
  deps/db/package.json
  deps/db/yarn.lock
  deps/graph-parser/package.json
  deps/graph-parser/yarn.lock
  deps/outliner/package.json
  deps/outliner/yarn.lock
  deps/publishing/package.json
  deps/publishing/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: :type/dev

#11943 chore: bump docs graph being tested
  .clj-kondo/config.edn
  deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
  deps/graph-parser/test/logseq/graph_parser/cli_test.cljs
  deps/graph-parser/test/logseq/graph_parser/exporter_test.cljs
  deps/graph-parser/test/logseq/graph_parser/mldoc_test.cljs
  src/test/frontend/handler/repo_test.cljs
Labels: :type/dev

#11940 fix: able to convert an existing page to a property
  deps/graph-parser/src/logseq/graph_parser/test/docs_graph_helper.cljs
  deps/graph-parser/test/logseq/graph_parser/cli_test.cljs
  deps/graph-parser/test/logseq/graph_parser/exporter_test.cljs
  deps/graph-parser/test/logseq/graph_parser/mldoc_test.cljs
  deps/outliner/src/logseq/outliner/property.cljs
  src/main/frontend/components/property.cljs
  src/main/frontend/worker/db/migrate.cljs
  src/test/frontend/handler/repo_test.cljs
Labels: :type/bug-fix

#11942 fix: match paste of x.com links for twitter
  src/main/frontend/handler/paste.cljs
Labels: :type/bug-fix

#11949 add plugin property validation
  deps/db/src/logseq/db/frontend/malli_schema.cljs
  deps/db/src/logseq/db/frontend/property.cljs
Labels: :type/enhancement

#11964 Enhance(UI): use dots menu for the asset actions
  public/index.html
  resources/index.html
  src/main/frontend/components/block.cljs
  src/main/frontend/components/block.css
  src/main/frontend/extensions/lightbox.cljs
  src/main/frontend/extensions/pdf/assets.cljs
  src/resources/dicts/en.edn
Labels: :type/enhancement

#11975 fix: indentation after an embeded node
  clj-e2e/test/logseq/e2e/outliner_basic_test.clj
  deps/outliner/src/logseq/outliner/core.cljs
Labels: :type/bug-fix
