Repository logseq/logseq, pull requests merged in 2025-09, with the labels that each got.

#12084 chore: bump to latest nbb w/ datascript update
  deps/cli/package.json
  deps/cli/yarn.lock
  deps/common/package.json
  deps/common/yarn.lock
  deps/db/package.json
  deps/db/yarn.lock
  deps/graph-parser/package.json
  deps/graph-parser/yarn.lock
  deps/outliner/package.json
  deps/outliner/yarn.lock
  deps/publishing/package.json
  deps/publishing/yarn.lock
  scripts/package.json
  scripts/yarn.lock
Labels: :type/dev

#12086 Fix(mobile): share contents between apps
  android/app/src/main/AndroidManifest.xml
  src/main/frontend/mobile/intent.cljs
Labels: :type/enhancement

#12085 fix: :and ref query should return nodes that having at least one ref
  deps/db/bb.edn
  deps/db/src/logseq/db/common/view.cljs
  deps/db/src/logseq/db/frontend/rules.cljc
  src/main/frontend/db/model.cljs
  src/main/frontend/db/query_dsl.cljs
  src/test/frontend/db/query_dsl_test.cljs
Labels: :type/bug-fix

#12101 refactor: RTC reuse :db/id for deleted blocks when undo/redo
  clj-e2e/src/logseq/e2e/block.clj
  clj-e2e/src/logseq/e2e/rtc.clj
  deps/db/src/logseq/db.cljs
  deps/outliner/src/logseq/outliner/core.cljs
  src/main/frontend/components/block.cljs
  src/main/frontend/handler/editor.cljs
  src/main/frontend/handler/worker.cljs
  src/main/frontend/undo_redo.cljs
  src/main/frontend/util.cljc
  src/main/frontend/worker/db_worker.cljs
  src/main/frontend/worker/handler/page.cljs
  src/main/frontend/worker/pipeline.cljs
  src/main/frontend/worker/rtc/remote_update.cljs
  src/main/frontend/worker/state.cljs
Labels: :type/bug-fix
